#define XWS_IMPLEMENTATION
#include "../../single/xws.h"



#if !defined(TEST_SINGLE_WS_HTTP_PROXY_BACKEND)
	#define TEST_SINGLE_WS_HTTP_PROXY_BACKEND XNET_PORT_SELECT
	#define TEST_SINGLE_WS_HTTP_PROXY_BACKEND_NAME "select"
#endif

#define TEST_WS_HTTP_PROXY_BACKEND TEST_SINGLE_WS_HTTP_PROXY_BACKEND
#define TEST_WS_HTTP_PROXY_BACKEND_NAME TEST_SINGLE_WS_HTTP_PROXY_BACKEND_NAME
#include "../websocket/test_http_proxy.c"
