/* 验证调用取消会摘除尚未完成的正文 Future waiter。 */
#define TEST_HTTP_CLIENT_STREAM_RESPONSE ""
#define TEST_HTTP_CLIENT_STREAM_STATUS 0
#define TEST_HTTP_CLIENT_STREAM_BODY ""
#define TEST_HTTP_CLIENT_STREAM_REMAINDER ""
#define TEST_HTTP_CLIENT_STREAM_REUSABLE 0
#define TEST_HTTP_CLIENT_STREAM_UPGRADED 0
#define TEST_HTTP_CLIENT_STREAM_CANCEL 1
#define TEST_HTTP_CLIENT_STREAM_RESUME 1
#define TEST_HTTP_CLIENT_STREAM_BODY_TERMINAL 0
#define TEST_HTTP_CLIENT_STREAM_SCENARIO "pending body cancellation"
#include "test_http_client_stream.c"
