/* 此文件由 tools/generate_extension_features.py 生成，请勿直接修改。 */
#ifndef XRUNTIME_FEATURES_H
#define XRUNTIME_FEATURES_H

/* runtime_dynamic_field 及其直接依赖。 */
#if defined(XRUNTIME_MODULE_ALL) || defined(XRUNTIME_MODULE_RUNTIME_DYNAMIC_FIELD)
#ifndef XRUNTIME_FEATURE_RUNTIME_DYNAMIC_FIELD
#define XRUNTIME_FEATURE_RUNTIME_DYNAMIC_FIELD
#endif
#ifndef XRUNTIME_MODULE_RUNTIME_FIELD
#define XRUNTIME_MODULE_RUNTIME_FIELD
#endif
#ifndef XRUNTIME_MODULE_TYPED_DICT
#define XRUNTIME_MODULE_TYPED_DICT
#endif
#ifndef XRUNTIME_MODULE_RUNTIME_OBJECT_GRAPH
#define XRUNTIME_MODULE_RUNTIME_OBJECT_GRAPH
#endif
#ifndef XRUNTIME_MODULE_RUNTIME_VALUE_TRACE
#define XRUNTIME_MODULE_RUNTIME_VALUE_TRACE
#endif
#endif

/* runtime_value_roots 及其直接依赖。 */
#if defined(XRUNTIME_MODULE_ALL) || defined(XRUNTIME_MODULE_RUNTIME_VALUE_ROOTS)
#ifndef XRUNTIME_FEATURE_RUNTIME_VALUE_ROOTS
#define XRUNTIME_FEATURE_RUNTIME_VALUE_ROOTS
#endif
#ifndef XRUNTIME_MODULE_RUNTIME_VALUE_TRACE
#define XRUNTIME_MODULE_RUNTIME_VALUE_TRACE
#endif
#ifndef XRUNTIME_MODULE_RUNTIME_OBJECT_GRAPH
#define XRUNTIME_MODULE_RUNTIME_OBJECT_GRAPH
#endif
#endif

/* runtime_value_trace 及其直接依赖。 */
#if defined(XRUNTIME_MODULE_ALL) || defined(XRUNTIME_MODULE_RUNTIME_VALUE_TRACE)
#ifndef XRUNTIME_FEATURE_RUNTIME_VALUE_TRACE
#define XRUNTIME_FEATURE_RUNTIME_VALUE_TRACE
#endif
#ifndef XRUNTIME_MODULE_RUNTIME_VALUE_TYPE
#define XRUNTIME_MODULE_RUNTIME_VALUE_TYPE
#endif
#ifndef XRUNTIME_MODULE_RUNTIME_VALUE_OBJECT
#define XRUNTIME_MODULE_RUNTIME_VALUE_OBJECT
#endif
#endif

/* runtime_value_type 及其直接依赖。 */
#if defined(XRUNTIME_MODULE_ALL) || defined(XRUNTIME_MODULE_RUNTIME_VALUE_TYPE)
#ifndef XRUNTIME_FEATURE_RUNTIME_VALUE_TYPE
#define XRUNTIME_FEATURE_RUNTIME_VALUE_TYPE
#endif
#ifndef XRUNTIME_MODULE_RUNTIME_TYPE
#define XRUNTIME_MODULE_RUNTIME_TYPE
#endif
#ifndef XRT_MODULE_VALUE_GRAPH
#define XRT_MODULE_VALUE_GRAPH
#endif
#endif

/* runtime_value_weak 及其直接依赖。 */
#if defined(XRUNTIME_MODULE_ALL) || defined(XRUNTIME_MODULE_RUNTIME_VALUE_WEAK)
#ifndef XRUNTIME_FEATURE_RUNTIME_VALUE_WEAK
#define XRUNTIME_FEATURE_RUNTIME_VALUE_WEAK
#endif
#ifndef XRUNTIME_MODULE_RUNTIME_OBJECT
#define XRUNTIME_MODULE_RUNTIME_OBJECT
#endif
#ifndef XRT_MODULE_VALUE
#define XRT_MODULE_VALUE
#endif
#endif

/* runtime_value_future 及其直接依赖。 */
#if defined(XRUNTIME_MODULE_ALL) || defined(XRUNTIME_MODULE_RUNTIME_VALUE_FUTURE)
#ifndef XRUNTIME_FEATURE_RUNTIME_VALUE_FUTURE
#define XRUNTIME_FEATURE_RUNTIME_VALUE_FUTURE
#endif
#ifndef XRUNTIME_MODULE_RUNTIME_TYPE_FUTURE
#define XRUNTIME_MODULE_RUNTIME_TYPE_FUTURE
#endif
#ifndef XRT_MODULE_VALUE
#define XRT_MODULE_VALUE
#endif
#endif

/* runtime_value_callable 及其直接依赖。 */
#if defined(XRUNTIME_MODULE_ALL) || defined(XRUNTIME_MODULE_RUNTIME_VALUE_CALLABLE)
#ifndef XRUNTIME_FEATURE_RUNTIME_VALUE_CALLABLE
#define XRUNTIME_FEATURE_RUNTIME_VALUE_CALLABLE
#endif
#ifndef XRUNTIME_MODULE_RUNTIME_CALL
#define XRUNTIME_MODULE_RUNTIME_CALL
#endif
#endif

/* runtime_value_object 及其直接依赖。 */
#if defined(XRUNTIME_MODULE_ALL) || defined(XRUNTIME_MODULE_RUNTIME_VALUE_OBJECT)
#ifndef XRUNTIME_FEATURE_RUNTIME_VALUE_OBJECT
#define XRUNTIME_FEATURE_RUNTIME_VALUE_OBJECT
#endif
#ifndef XRUNTIME_MODULE_RUNTIME_OBJECT
#define XRUNTIME_MODULE_RUNTIME_OBJECT
#endif
#ifndef XRT_MODULE_VALUE
#define XRT_MODULE_VALUE
#endif
#endif

/* runtime_call 及其直接依赖。 */
#if defined(XRUNTIME_MODULE_ALL) || defined(XRUNTIME_MODULE_RUNTIME_CALL)
#ifndef XRUNTIME_FEATURE_RUNTIME_CALL
#define XRUNTIME_FEATURE_RUNTIME_CALL
#endif
#ifndef XRUNTIME_MODULE_RUNTIME_TYPE
#define XRUNTIME_MODULE_RUNTIME_TYPE
#endif
#ifndef XRT_MODULE_VALUE
#define XRT_MODULE_VALUE
#endif
#endif

/* typed_dict_value 及其直接依赖。 */
#if defined(XRUNTIME_MODULE_ALL) || defined(XRUNTIME_MODULE_TYPED_DICT_VALUE)
#ifndef XRUNTIME_FEATURE_TYPED_DICT_VALUE
#define XRUNTIME_FEATURE_TYPED_DICT_VALUE
#endif
#ifndef XRUNTIME_MODULE_TYPED_VALUE
#define XRUNTIME_MODULE_TYPED_VALUE
#endif
#ifndef XRUNTIME_MODULE_TYPED_DICT
#define XRUNTIME_MODULE_TYPED_DICT
#endif
#ifndef XRT_MODULE_VALUE_CONTAINER
#define XRT_MODULE_VALUE_CONTAINER
#endif
#endif

/* typed_set_value 及其直接依赖。 */
#if defined(XRUNTIME_MODULE_ALL) || defined(XRUNTIME_MODULE_TYPED_SET_VALUE)
#ifndef XRUNTIME_FEATURE_TYPED_SET_VALUE
#define XRUNTIME_FEATURE_TYPED_SET_VALUE
#endif
#ifndef XRUNTIME_MODULE_TYPED_VALUE
#define XRUNTIME_MODULE_TYPED_VALUE
#endif
#ifndef XRUNTIME_MODULE_TYPED_SET
#define XRUNTIME_MODULE_TYPED_SET
#endif
#ifndef XRT_MODULE_VALUE_CONTAINER
#define XRT_MODULE_VALUE_CONTAINER
#endif
#endif

/* typed_list_value 及其直接依赖。 */
#if defined(XRUNTIME_MODULE_ALL) || defined(XRUNTIME_MODULE_TYPED_LIST_VALUE)
#ifndef XRUNTIME_FEATURE_TYPED_LIST_VALUE
#define XRUNTIME_FEATURE_TYPED_LIST_VALUE
#endif
#ifndef XRUNTIME_MODULE_TYPED_VALUE
#define XRUNTIME_MODULE_TYPED_VALUE
#endif
#ifndef XRUNTIME_MODULE_TYPED_LIST
#define XRUNTIME_MODULE_TYPED_LIST
#endif
#ifndef XRT_MODULE_VALUE_CONTAINER
#define XRT_MODULE_VALUE_CONTAINER
#endif
#endif

/* typed_array_value 及其直接依赖。 */
#if defined(XRUNTIME_MODULE_ALL) || defined(XRUNTIME_MODULE_TYPED_ARRAY_VALUE)
#ifndef XRUNTIME_FEATURE_TYPED_ARRAY_VALUE
#define XRUNTIME_FEATURE_TYPED_ARRAY_VALUE
#endif
#ifndef XRUNTIME_MODULE_TYPED_VALUE
#define XRUNTIME_MODULE_TYPED_VALUE
#endif
#ifndef XRUNTIME_MODULE_TYPED_ARRAY
#define XRUNTIME_MODULE_TYPED_ARRAY
#endif
#ifndef XRT_MODULE_VALUE_CONTAINER
#define XRT_MODULE_VALUE_CONTAINER
#endif
#endif

/* typed_dict 及其直接依赖。 */
#if defined(XRUNTIME_MODULE_ALL) || defined(XRUNTIME_MODULE_TYPED_DICT)
#ifndef XRUNTIME_FEATURE_TYPED_DICT
#define XRUNTIME_FEATURE_TYPED_DICT
#endif
#ifndef XRT_MODULE_MAP
#define XRT_MODULE_MAP
#endif
#ifndef XRUNTIME_MODULE_RUNTIME_TYPE
#define XRUNTIME_MODULE_RUNTIME_TYPE
#endif
#endif

/* typed_set 及其直接依赖。 */
#if defined(XRUNTIME_MODULE_ALL) || defined(XRUNTIME_MODULE_TYPED_SET)
#ifndef XRUNTIME_FEATURE_TYPED_SET
#define XRUNTIME_FEATURE_TYPED_SET
#endif
#ifndef XRT_MODULE_SET
#define XRT_MODULE_SET
#endif
#ifndef XRUNTIME_MODULE_RUNTIME_TYPE
#define XRUNTIME_MODULE_RUNTIME_TYPE
#endif
#endif

/* typed_list 及其直接依赖。 */
#if defined(XRUNTIME_MODULE_ALL) || defined(XRUNTIME_MODULE_TYPED_LIST)
#ifndef XRUNTIME_FEATURE_TYPED_LIST
#define XRUNTIME_FEATURE_TYPED_LIST
#endif
#ifndef XRT_MODULE_INT_MAP
#define XRT_MODULE_INT_MAP
#endif
#ifndef XRUNTIME_MODULE_RUNTIME_TYPE
#define XRUNTIME_MODULE_RUNTIME_TYPE
#endif
#endif

/* typed_tree 及其直接依赖。 */
#if defined(XRUNTIME_MODULE_ALL) || defined(XRUNTIME_MODULE_TYPED_TREE)
#ifndef XRUNTIME_FEATURE_TYPED_TREE
#define XRUNTIME_FEATURE_TYPED_TREE
#endif
#ifndef XRT_MODULE_AVL_TREE
#define XRT_MODULE_AVL_TREE
#endif
#ifndef XRUNTIME_MODULE_RUNTIME_TYPE
#define XRUNTIME_MODULE_RUNTIME_TYPE
#endif
#endif

/* typed_stack 及其直接依赖。 */
#if defined(XRUNTIME_MODULE_ALL) || defined(XRUNTIME_MODULE_TYPED_STACK)
#ifndef XRUNTIME_FEATURE_TYPED_STACK
#define XRUNTIME_FEATURE_TYPED_STACK
#endif
#ifndef XRUNTIME_MODULE_TYPED_ARRAY
#define XRUNTIME_MODULE_TYPED_ARRAY
#endif
#endif

/* runtime_object_graph 及其直接依赖。 */
#if defined(XRUNTIME_MODULE_ALL) || defined(XRUNTIME_MODULE_RUNTIME_OBJECT_GRAPH)
#ifndef XRUNTIME_FEATURE_RUNTIME_OBJECT_GRAPH
#define XRUNTIME_FEATURE_RUNTIME_OBJECT_GRAPH
#endif
#ifndef XRUNTIME_MODULE_RUNTIME_OBJECT
#define XRUNTIME_MODULE_RUNTIME_OBJECT
#endif
#endif

/* runtime_object 及其直接依赖。 */
#if defined(XRUNTIME_MODULE_ALL) || defined(XRUNTIME_MODULE_RUNTIME_OBJECT)
#ifndef XRUNTIME_FEATURE_RUNTIME_OBJECT
#define XRUNTIME_FEATURE_RUNTIME_OBJECT
#endif
#ifndef XRUNTIME_MODULE_RUNTIME_TYPE
#define XRUNTIME_MODULE_RUNTIME_TYPE
#endif
#endif

/* typed_queue_mpmc 及其直接依赖。 */
#if defined(XRUNTIME_MODULE_ALL) || defined(XRUNTIME_MODULE_TYPED_QUEUE_MPMC)
#ifndef XRUNTIME_FEATURE_TYPED_QUEUE_MPMC
#define XRUNTIME_FEATURE_TYPED_QUEUE_MPMC
#endif
#ifndef XRUNTIME_MODULE_TYPED_QUEUE
#define XRUNTIME_MODULE_TYPED_QUEUE
#endif
#ifndef XRT_MODULE_QUEUE_MPMC
#define XRT_MODULE_QUEUE_MPMC
#endif
#endif

/* typed_queue_mpsc 及其直接依赖。 */
#if defined(XRUNTIME_MODULE_ALL) || defined(XRUNTIME_MODULE_TYPED_QUEUE_MPSC)
#ifndef XRUNTIME_FEATURE_TYPED_QUEUE_MPSC
#define XRUNTIME_FEATURE_TYPED_QUEUE_MPSC
#endif
#ifndef XRUNTIME_MODULE_TYPED_QUEUE
#define XRUNTIME_MODULE_TYPED_QUEUE
#endif
#ifndef XRT_MODULE_QUEUE_MPSC
#define XRT_MODULE_QUEUE_MPSC
#endif
#ifndef XRT_MODULE_QUEUE_MPMC
#define XRT_MODULE_QUEUE_MPMC
#endif
#endif

/* typed_queue_spsc 及其直接依赖。 */
#if defined(XRUNTIME_MODULE_ALL) || defined(XRUNTIME_MODULE_TYPED_QUEUE_SPSC)
#ifndef XRUNTIME_FEATURE_TYPED_QUEUE_SPSC
#define XRUNTIME_FEATURE_TYPED_QUEUE_SPSC
#endif
#ifndef XRUNTIME_MODULE_TYPED_QUEUE
#define XRUNTIME_MODULE_TYPED_QUEUE
#endif
#ifndef XRT_MODULE_QUEUE_SPSC
#define XRT_MODULE_QUEUE_SPSC
#endif
#endif

/* typed_queue 及其直接依赖。 */
#if defined(XRUNTIME_MODULE_ALL) || defined(XRUNTIME_MODULE_TYPED_QUEUE)
#ifndef XRUNTIME_FEATURE_TYPED_QUEUE
#define XRUNTIME_FEATURE_TYPED_QUEUE
#endif
#ifndef XRT_MODULE_QUEUE
#define XRT_MODULE_QUEUE
#endif
#ifndef XRUNTIME_MODULE_RUNTIME_TYPE
#define XRUNTIME_MODULE_RUNTIME_TYPE
#endif
#endif

/* typed_array 及其直接依赖。 */
#if defined(XRUNTIME_MODULE_ALL) || defined(XRUNTIME_MODULE_TYPED_ARRAY)
#ifndef XRUNTIME_FEATURE_TYPED_ARRAY
#define XRUNTIME_FEATURE_TYPED_ARRAY
#endif
#ifndef XRT_MODULE_ARRAY
#define XRT_MODULE_ARRAY
#endif
#ifndef XRUNTIME_MODULE_RUNTIME_TYPE
#define XRUNTIME_MODULE_RUNTIME_TYPE
#endif
#endif

/* runtime_field 及其直接依赖。 */
#if defined(XRUNTIME_MODULE_ALL) || defined(XRUNTIME_MODULE_RUNTIME_FIELD)
#ifndef XRUNTIME_FEATURE_RUNTIME_FIELD
#define XRUNTIME_FEATURE_RUNTIME_FIELD
#endif
#ifndef XRUNTIME_MODULE_RUNTIME_TYPE
#define XRUNTIME_MODULE_RUNTIME_TYPE
#endif
#endif

/* runtime_type_future 及其直接依赖。 */
#if defined(XRUNTIME_MODULE_ALL) || defined(XRUNTIME_MODULE_RUNTIME_TYPE_FUTURE)
#ifndef XRUNTIME_FEATURE_RUNTIME_TYPE_FUTURE
#define XRUNTIME_FEATURE_RUNTIME_TYPE_FUTURE
#endif
#ifndef XRT_MODULE_FUTURE
#define XRT_MODULE_FUTURE
#endif
#ifndef XRUNTIME_MODULE_RUNTIME_TYPE
#define XRUNTIME_MODULE_RUNTIME_TYPE
#endif
#endif

/* runtime_type_string_value 及其直接依赖。 */
#if defined(XRUNTIME_MODULE_ALL) || defined(XRUNTIME_MODULE_RUNTIME_TYPE_STRING_VALUE)
#ifndef XRUNTIME_FEATURE_RUNTIME_TYPE_STRING_VALUE
#define XRUNTIME_FEATURE_RUNTIME_TYPE_STRING_VALUE
#endif
#ifndef XRUNTIME_MODULE_RUNTIME_TYPE_STRING
#define XRUNTIME_MODULE_RUNTIME_TYPE_STRING
#endif
#ifndef XRUNTIME_MODULE_TYPED_VALUE
#define XRUNTIME_MODULE_TYPED_VALUE
#endif
#endif

/* typed_value 及其直接依赖。 */
#if defined(XRUNTIME_MODULE_ALL) || defined(XRUNTIME_MODULE_TYPED_VALUE)
#ifndef XRUNTIME_FEATURE_TYPED_VALUE
#define XRUNTIME_FEATURE_TYPED_VALUE
#endif
#ifndef XRUNTIME_MODULE_RUNTIME_TYPE
#define XRUNTIME_MODULE_RUNTIME_TYPE
#endif
#ifndef XRT_MODULE_VALUE
#define XRT_MODULE_VALUE
#endif
#endif

/* value_convert_string 及其直接依赖。 */
#if defined(XRUNTIME_MODULE_ALL) || defined(XRUNTIME_MODULE_VALUE_CONVERT_STRING)
#ifndef XRUNTIME_FEATURE_VALUE_CONVERT_STRING
#define XRUNTIME_FEATURE_VALUE_CONVERT_STRING
#endif
#ifndef XRUNTIME_MODULE_VALUE_CONVERT
#define XRUNTIME_MODULE_VALUE_CONVERT
#endif
#ifndef XRUNTIME_MODULE_RUNTIME_CONVERT_STRING
#define XRUNTIME_MODULE_RUNTIME_CONVERT_STRING
#endif
#endif

/* value_convert 及其直接依赖。 */
#if defined(XRUNTIME_MODULE_ALL) || defined(XRUNTIME_MODULE_VALUE_CONVERT)
#ifndef XRUNTIME_FEATURE_VALUE_CONVERT
#define XRUNTIME_FEATURE_VALUE_CONVERT
#endif
#ifndef XRUNTIME_MODULE_RUNTIME_CONVERT
#define XRUNTIME_MODULE_RUNTIME_CONVERT
#endif
#ifndef XRT_MODULE_VALUE
#define XRT_MODULE_VALUE
#endif
#endif

/* runtime_convert_string 及其直接依赖。 */
#if defined(XRUNTIME_MODULE_ALL) || defined(XRUNTIME_MODULE_RUNTIME_CONVERT_STRING)
#ifndef XRUNTIME_FEATURE_RUNTIME_CONVERT_STRING
#define XRUNTIME_FEATURE_RUNTIME_CONVERT_STRING
#endif
#ifndef XRUNTIME_MODULE_RUNTIME_CONVERT
#define XRUNTIME_MODULE_RUNTIME_CONVERT
#endif
#ifndef XRUNTIME_MODULE_RUNTIME_TYPE_STRING
#define XRUNTIME_MODULE_RUNTIME_TYPE_STRING
#endif
#ifndef XRT_MODULE_NUMBER_INTEGER
#define XRT_MODULE_NUMBER_INTEGER
#endif
#ifndef XRT_MODULE_NUMBER_FLOAT
#define XRT_MODULE_NUMBER_FLOAT
#endif
#ifndef XRT_MODULE_TIME_TEXT
#define XRT_MODULE_TIME_TEXT
#endif
#endif

/* runtime_type_string 及其直接依赖。 */
#if defined(XRUNTIME_MODULE_ALL) || defined(XRUNTIME_MODULE_RUNTIME_TYPE_STRING)
#ifndef XRUNTIME_FEATURE_RUNTIME_TYPE_STRING
#define XRUNTIME_FEATURE_RUNTIME_TYPE_STRING
#endif
#ifndef XRT_MODULE_STRING
#define XRT_MODULE_STRING
#endif
#ifndef XRT_MODULE_HASH64
#define XRT_MODULE_HASH64
#endif
#ifndef XRUNTIME_MODULE_RUNTIME_TYPE
#define XRUNTIME_MODULE_RUNTIME_TYPE
#endif
#endif

/* runtime_convert 及其直接依赖。 */
#if defined(XRUNTIME_MODULE_ALL) || defined(XRUNTIME_MODULE_RUNTIME_CONVERT)
#ifndef XRUNTIME_FEATURE_RUNTIME_CONVERT
#define XRUNTIME_FEATURE_RUNTIME_CONVERT
#endif
#ifndef XRUNTIME_MODULE_RUNTIME_TYPE
#define XRUNTIME_MODULE_RUNTIME_TYPE
#endif
#endif

/* runtime_type 及其直接依赖。 */
#if defined(XRUNTIME_MODULE_ALL) || defined(XRUNTIME_MODULE_RUNTIME_TYPE)
#ifndef XRUNTIME_FEATURE_RUNTIME_TYPE
#define XRUNTIME_FEATURE_RUNTIME_TYPE
#endif
#endif

#endif /* XRUNTIME_FEATURES_H */
