/* Public, deliberately predictable keys for isolated certificate contract tests.
 * Certificates are signed by scalar-3 P-256 CA; EC leaf key is scalar 2.
 * These fixture keys are not secrets and must never be used by applications. */
#ifndef XACME_TEST_CERT_FIXTURE_H
#define XACME_TEST_CERT_FIXTURE_H

#define ACME_FIXTURE_KEY \
    "-----BEGIN PRIVATE KEY-----\n" \
    "MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgAAAAAAAAAAAAAAAA\n" \
    "AAAAAAAAAAAAAAAAAAAAAAAAAAKhRANCAAR88nsYjQNPfopSOAMEtRrDwIlp4nfy\n" \
    "GzWmC0j8R2aZeAd3VRDbjtBAKT2axp90MNu6fa3mPOmCKZ4Et50ieHPR\n" \
    "-----END PRIVATE KEY-----\n"

#define ACME_FIXTURE_RSA_KEY \
    "-----BEGIN PRIVATE KEY-----\n" \
    "MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC4uYKMigsCkQ9o\n" \
    "BSx88+GAYdpxPINd+Xv7egfgpxVC/kMZxAjK3SkNw93jpM3lcXy9WPIPt4OUjwUk\n" \
    "blPQkRSjkMBx+zTKgxoP//EGam6kucv5O3kNbVNpU4QNlELQc7PQtSFanBZMUWVA\n" \
    "n0S6JbFmdme5J9J/Fn54Uo+geGhQcsLViuGy4367pHKMkIKjIvh+Sn2RHe3y3OSc\n" \
    "LPzDDhOpL2lcNZ1diLGvw5VSUunVlTaaxiJPuwuqK7jBTrpcmHyIslp3ld66yRxY\n" \
    "LoOwRBI73dD4dbWUi0JsqMEAvY6C4YVHQF+ywxvVgUHCckJiHoHxdX0gAdHqyHcK\n" \
    "x0MWNd/JAgMBAAECggEACjAdDaA9bDZQ6bVDV17iBIEhGZazThcI6f04ewDsEMZS\n" \
    "MBUaQQoCjiJL1hbMTke8j/rcWtaNuL9Mks5M7BdcUosUuhSXPEYPxWshwW9US9x9\n" \
    "bfEEQ6PQcmIrSc5wAuwmsi+TN9qc9jeVBIPkN/oFNzf3j4QtPVohvoQbLMgHRMx/\n" \
    "iI4ZXHXvqpLs+aOPwZk7L4u4Vn3bbp7FUbh4b9Cia9TPAJnf02RfNaB1xfsG2k2t\n" \
    "1DPgMxt6RUylBicJqDD1bCjxZeMSEfMtHsDnLLaX8C3gbKqv/GRh/HIqP1OSjDws\n" \
    "shwgJ4RxlsUdQOc9uyr6zbp7vERSwwyQnoCt4zRvowKBgQDfOI/VMtJoMY8Eb+m3\n" \
    "0Ew0A3TswGdEoSjRth6y8BuBYTkLEambBdb6LsZxbrAQ0fQ6Z4xeuqGZGB3d9+il\n" \
    "utuXf2e4o2reJO8P2Pny7tSrZ35vbEH7ArAkMJBmRuia5V1e/wYZfTb40ZmsjMeL\n" \
    "VKjb7h88WqqJw94ISZYzQPREHwKBgQDT2cZ3cWuPHqJnzcjLzcaZXNiek29zkF6y\n" \
    "k3zfLO0+JHZcxlv1gRPx724CHAcT/RxRqOx26iYQLH7wyuG4eJ2Cwc1ob705q2aZ\n" \
    "BTTIc69Pr4VWGzEGzuG2qgGR+H10iC6PuL9EN0aUCcTOQjQSfsQXEl35wA9tTyg3\n" \
    "XTMos3wfFwKBgQCynnYp6eMIUS/aIxtoZRu1O1bi5As+lZ8uQIdMNGouG3gj7VxE\n" \
    "mmWuCKPuvN3Sd87wtU9Ttg/9i5jKt8fIZj+1eNOsocewPum1SrCnvokbJ1O7IWui\n" \
    "ykHck6fYz8Dtwb/3diaRWusUK9TGiFhcm8ALTP5ds0dnuf3/r7KrDLzpjQKBgEUa\n" \
    "6tSXmOBsu8lkpTVmAHySfs7rhRWLaHiUB829F/6HYlzND747xsfKtHXXsq9gh1ZT\n" \
    "5h68LoJkIVxmsc68+ZRnp5uDp5QiRytvOVKR+gPiW3pFEG8KGTK+rhhxmGrk6VtU\n" \
    "hn+4EDvGG/60Ncw6sbhc826+qcmcYp/8tO137ustAoGATzRW0Zf5di9Rlg4ixZrM\n" \
    "y0Y/SX0EXV+9HSuRJzXgXEuQx8atPND2h+BZ14wgtqJjgSYQSbF7MqDTQOAN7KOP\n" \
    "UUTeuxEIpEhHcrlgtVryurZoc4uRyn9mWFj4fOkhFCVUhV5Ln9JioahUsr0R3chG\n" \
    "nOe4InSuwGedFeuk6F55alY=\n" \
    "-----END PRIVATE KEY-----\n"

#define ACME_FIXTURE_CA \
    "-----BEGIN CERTIFICATE-----\n" \
    "MIIBSDCB8KADAgECAgEBMAoGCCqGSM49BAMCMCMxITAfBgNVBAMMGEFDTUUgY29u\n" \
    "dHJhY3QgZml4dHVyZSBDQTAgFw0wMDAxMDEwMDAwMDBaGA8yMDk5MDEwMTAwMDAw\n" \
    "MFowIzEhMB8GA1UEAwwYQUNNRSBjb250cmFjdCBmaXh0dXJlIENBMFkwEwYHKoZI\n" \
    "zj0CAQYIKoZIzj0DAQcDQgAEXsvk0aYzCkTI9++VHUvxZebGtyHvramF+0FmG8bn\n" \
    "/WyHNGQMSZj/fjdLBs4aZKLs2CqwNjhPuD2aebEnon1QMqMTMBEwDwYDVR0TAQH/\n" \
    "BAUwAwEB/zAKBggqhkjOPQQDAgNHADBEAiBsblihKLKDBWu5/p51+Ox7YGDBvuBP\n" \
    "Zno7heXIU42JNgIgAcvmv2++jVo9TFkfjZ5pViKTdirQ8X5Z6XBULHBd0HQ=\n" \
    "-----END CERTIFICATE-----\n"

#define ACME_FIXTURE_LEAF \
    "-----BEGIN CERTIFICATE-----\n" \
    "MIIBUDCB+KADAgECAgECMAoGCCqGSM49BAMCMCMxITAfBgNVBAMMGEFDTUUgY29u\n" \
    "dHJhY3QgZml4dHVyZSBDQTAgFw0wMDAxMDEwMDAwMDBaGA8yMDk5MDEwMTAwMDAw\n" \
    "MFowFjEUMBIGA1UEAwwLZXhhbXBsZS5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMB\n" \
    "BwNCAAR88nsYjQNPfopSOAMEtRrDwIlp4nfyGzWmC0j8R2aZeAd3VRDbjtBAKT2a\n" \
    "xp90MNu6fa3mPOmCKZ4Et50ieHPRoygwJjAMBgNVHRMBAf8EAjAAMBYGA1UdEQQP\n" \
    "MA2CC2V4YW1wbGUuY29tMAoGCCqGSM49BAMCA0cAMEQCIC5d6lyUjooQinSCCFZ+\n" \
    "mPo6TTVUQE5/wKyfrQSuQhtjAiAm0nloz1LJCUAqrdnzQXvirLtFHQ61ddDtgnt6\n" \
    "q31o0Q==\n" \
    "-----END CERTIFICATE-----\n"

#define ACME_FIXTURE_OTHER_KEY_LEAF \
    "-----BEGIN CERTIFICATE-----\n" \
    "MIIBUTCB+KADAgECAgEDMAoGCCqGSM49BAMCMCMxITAfBgNVBAMMGEFDTUUgY29u\n" \
    "dHJhY3QgZml4dHVyZSBDQTAgFw0wMDAxMDEwMDAwMDBaGA8yMDk5MDEwMTAwMDAw\n" \
    "MFowFjEUMBIGA1UEAwwLZXhhbXBsZS5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMB\n" \
    "BwNCAATiU0o1MtCPu6At3mWe5ivQAx/i23hVlu9QkwJEawMIUuDxV1pMYzzHGd/u\n" \
    "X9qGLXZO/JbD8w7gBVxCwj8YTtjGoygwJjAMBgNVHRMBAf8EAjAAMBYGA1UdEQQP\n" \
    "MA2CC2V4YW1wbGUuY29tMAoGCCqGSM49BAMCA0gAMEUCIDu+mavby3WIN2vdqdRW\n" \
    "4ODtgzpsRHwGFBKIqs32rHzvAiEA+tT07sdBDmGpDGSvUrR/4erMWPYgpV3KlaS2\n" \
    "8SZq5yo=\n" \
    "-----END CERTIFICATE-----\n"

#define ACME_FIXTURE_OTHER_DOMAIN_LEAF \
    "-----BEGIN CERTIFICATE-----\n" \
    "MIIBUTCB+KADAgECAgEEMAoGCCqGSM49BAMCMCMxITAfBgNVBAMMGEFDTUUgY29u\n" \
    "dHJhY3QgZml4dHVyZSBDQTAgFw0wMDAxMDEwMDAwMDBaGA8yMDk5MDEwMTAwMDAw\n" \
    "MFowFjEUMBIGA1UEAwwLZXhhbXBsZS5uZXQwWTATBgcqhkjOPQIBBggqhkjOPQMB\n" \
    "BwNCAAR88nsYjQNPfopSOAMEtRrDwIlp4nfyGzWmC0j8R2aZeAd3VRDbjtBAKT2a\n" \
    "xp90MNu6fa3mPOmCKZ4Et50ieHPRoygwJjAMBgNVHRMBAf8EAjAAMBYGA1UdEQQP\n" \
    "MA2CC2V4YW1wbGUubmV0MAoGCCqGSM49BAMCA0gAMEUCIQD4Fx9M994/Uw6su3dL\n" \
    "3sTodU56WGZOcD3Pxn6hwuvWcgIgOYiVeLn64pDoyrQUr0sEcU5cdhnHSp3t8MxE\n" \
    "/DOof64=\n" \
    "-----END CERTIFICATE-----\n"

#define ACME_FIXTURE_OTHER_LEAF \
    "-----BEGIN CERTIFICATE-----\n" \
    "MIIBUTCB+KADAgECAgEFMAoGCCqGSM49BAMCMCMxITAfBgNVBAMMGEFDTUUgY29u\n" \
    "dHJhY3QgZml4dHVyZSBDQTAgFw0wMDAxMDEwMDAwMDBaGA8yMDk5MDEwMTAwMDAw\n" \
    "MFowFjEUMBIGA1UEAwwLZXhhbXBsZS5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMB\n" \
    "BwNCAAR88nsYjQNPfopSOAMEtRrDwIlp4nfyGzWmC0j8R2aZeAd3VRDbjtBAKT2a\n" \
    "xp90MNu6fa3mPOmCKZ4Et50ieHPRoygwJjAMBgNVHRMBAf8EAjAAMBYGA1UdEQQP\n" \
    "MA2CC2V4YW1wbGUuY29tMAoGCCqGSM49BAMCA0gAMEUCIGiVsgN58e4DGXOjptXS\n" \
    "LDZeGJCRSoAb6UaObn/mcvAJAiEAmw1YwjGMgRJ5Qx3/5RHVa4GQDh7FuGY3lBqW\n" \
    "xwOuHao=\n" \
    "-----END CERTIFICATE-----\n"

#define ACME_FIXTURE_EXPIRED_LEAF \
    "-----BEGIN CERTIFICATE-----\n" \
    "MIIBTjCB9qADAgECAgEGMAoGCCqGSM49BAMCMCMxITAfBgNVBAMMGEFDTUUgY29u\n" \
    "dHJhY3QgZml4dHVyZSBDQTAeFw0wMDAxMDEwMDAwMDBaFw0wMTAxMDEwMDAwMDBa\n" \
    "MBYxFDASBgNVBAMMC2V4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcD\n" \
    "QgAEfPJ7GI0DT36KUjgDBLUaw8CJaeJ38hs1pgtI/EdmmXgHd1UQ247QQCk9msaf\n" \
    "dDDbun2t5jzpgimeBLedInhz0aMoMCYwDAYDVR0TAQH/BAIwADAWBgNVHREEDzAN\n" \
    "ggtleGFtcGxlLmNvbTAKBggqhkjOPQQDAgNHADBEAiA5aYGlax7djfGhK+AdIaVo\n" \
    "2n9iTsPSBbOzo4YCWrEsgAIgJCMPYazUuxAOTJGyDTt5G086mrTmVXaetC6VM4T4\n" \
    "d80=\n" \
    "-----END CERTIFICATE-----\n"

#define ACME_FIXTURE_FUTURE_LEAF \
    "-----BEGIN CERTIFICATE-----\n" \
    "MIIBVDCB+qADAgECAgEHMAoGCCqGSM49BAMCMCMxITAfBgNVBAMMGEFDTUUgY29u\n" \
    "dHJhY3QgZml4dHVyZSBDQTAiGA8yMDk4MDEwMTAwMDAwMFoYDzIwOTkwMTAxMDAw\n" \
    "MDAwWjAWMRQwEgYDVQQDDAtleGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49\n" \
    "AwEHA0IABHzyexiNA09+ilI4AwS1GsPAiWnid/IbNaYLSPxHZpl4B3dVENuO0EAp\n" \
    "PZrGn3Qw27p9reY86YIpngS3nSJ4c9GjKDAmMAwGA1UdEwEB/wQCMAAwFgYDVR0R\n" \
    "BA8wDYILZXhhbXBsZS5jb20wCgYIKoZIzj0EAwIDSQAwRgIhAIjjhXQjBkJIPzU6\n" \
    "PSXBRTgUWjJ7rVg7Sa1I0pc1QoM1AiEAkg75SQWx5cnIi2UVHrMg/Kwz4R8v4Hxl\n" \
    "kkldWogeMEA=\n" \
    "-----END CERTIFICATE-----\n"

#define ACME_FIXTURE_RSA_LEAF \
    "-----BEGIN CERTIFICATE-----\n" \
    "MIICHDCCAcOgAwIBAgIBCDAKBggqhkjOPQQDAjAjMSEwHwYDVQQDDBhBQ01FIGNv\n" \
    "bnRyYWN0IGZpeHR1cmUgQ0EwIBcNMDAwMTAxMDAwMDAwWhgPMjA5OTAxMDEwMDAw\n" \
    "MDBaMBYxFDASBgNVBAMMC2V4YW1wbGUuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOC\n" \
    "AQ8AMIIBCgKCAQEAuLmCjIoLApEPaAUsfPPhgGHacTyDXfl7+3oH4KcVQv5DGcQI\n" \
    "yt0pDcPd46TN5XF8vVjyD7eDlI8FJG5T0JEUo5DAcfs0yoMaD//xBmpupLnL+Tt5\n" \
    "DW1TaVOEDZRC0HOz0LUhWpwWTFFlQJ9EuiWxZnZnuSfSfxZ+eFKPoHhoUHLC1Yrh\n" \
    "suN+u6RyjJCCoyL4fkp9kR3t8tzknCz8ww4TqS9pXDWdXYixr8OVUlLp1ZU2msYi\n" \
    "T7sLqiu4wU66XJh8iLJad5XeuskcWC6DsEQSO93Q+HW1lItCbKjBAL2OguGFR0Bf\n" \
    "ssMb1YFBwnJCYh6B8XV9IAHR6sh3CsdDFjXfyQIDAQABoygwJjAMBgNVHRMBAf8E\n" \
    "AjAAMBYGA1UdEQQPMA2CC2V4YW1wbGUuY29tMAoGCCqGSM49BAMCA0cAMEQCICU8\n" \
    "82lJLKooryuNInWDrFMQhy9uNha40MrHike3+S6WAiBtbSKvzZDO28iRbBeNrjrA\n" \
    "Gp8h0W+8RAKK+p2XH/p41Q==\n" \
    "-----END CERTIFICATE-----\n"

#define ACME_FIXTURE_CHAIN ACME_FIXTURE_LEAF ACME_FIXTURE_CA

#define ACME_FIXTURE_ALT_CA \
    "-----BEGIN CERTIFICATE-----\n" \
    "MIIBTDCB86ADAgECAgEJMAoGCCqGSM49BAMCMCYxJDAiBgNVBAMMG0FDTUUgYWx0\n" \
    "ZXJuYXRlIGZpeHR1cmUgcm9vdDAgFw0wMDAxMDEwMDAwMDBaGA8yMDk5MDEwMTAw\n" \
    "MDAwMFowIzEhMB8GA1UEAwwYQUNNRSBjb250cmFjdCBmaXh0dXJlIENBMFkwEwYH\n" \
    "KoZIzj0CAQYIKoZIzj0DAQcDQgAEXsvk0aYzCkTI9++VHUvxZebGtyHvramF+0Fm\n" \
    "G8bn/WyHNGQMSZj/fjdLBs4aZKLs2CqwNjhPuD2aebEnon1QMqMTMBEwDwYDVR0T\n" \
    "AQH/BAUwAwEB/zAKBggqhkjOPQQDAgNIADBFAiAYJ7lTyAeeo8BsLX9We2JplNjT\n" \
    "aqE+Kd7zUlV7U/5/YQIhAK5k67Cz/tUjCyczmtp36ng/21Tz0q/m2wCS/R/e+Op7\n" \
    "-----END CERTIFICATE-----\n"

#define ACME_FIXTURE_EXTRA_DOMAIN_LEAF \
    "-----BEGIN CERTIFICATE-----\n" \
    "MIIBXjCCAQWgAwIBAgIBCjAKBggqhkjOPQQDAjAjMSEwHwYDVQQDDBhBQ01FIGNv\n" \
    "bnRyYWN0IGZpeHR1cmUgQ0EwIBcNMDAwMTAxMDAwMDAwWhgPMjA5OTAxMDEwMDAw\n" \
    "MDBaMBYxFDASBgNVBAMMC2V4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0D\n" \
    "AQcDQgAEfPJ7GI0DT36KUjgDBLUaw8CJaeJ38hs1pgtI/EdmmXgHd1UQ247QQCk9\n" \
    "msafdDDbun2t5jzpgimeBLedInhz0aM1MDMwDAYDVR0TAQH/BAIwADAjBgNVHREE\n" \
    "HDAaggtleGFtcGxlLmNvbYILZXhhbXBsZS5uZXQwCgYIKoZIzj0EAwIDRwAwRAIg\n" \
    "b3HDZ/w4EMx5RvN3ZvR8h4r8/teZfDE2pDYKlqzXU5YCIBCR+SVv8+3qY1t8L2w0\n" \
    "NsUTygHvO1V8UsxrBgoDs185\n" \
    "-----END CERTIFICATE-----\n"

#define ACME_FIXTURE_NO_SAN_LEAF \
    "-----BEGIN CERTIFICATE-----\n" \
    "MIIBOTCB4KADAgECAgELMAoGCCqGSM49BAMCMCMxITAfBgNVBAMMGEFDTUUgY29u\n" \
    "dHJhY3QgZml4dHVyZSBDQTAgFw0wMDAxMDEwMDAwMDBaGA8yMDk5MDEwMTAwMDAw\n" \
    "MFowFjEUMBIGA1UEAwwLZXhhbXBsZS5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMB\n" \
    "BwNCAAR88nsYjQNPfopSOAMEtRrDwIlp4nfyGzWmC0j8R2aZeAd3VRDbjtBAKT2a\n" \
    "xp90MNu6fa3mPOmCKZ4Et50ieHPRoxAwDjAMBgNVHRMBAf8EAjAAMAoGCCqGSM49\n" \
    "BAMCA0gAMEUCIGY5++KQX/Y/9zj0HjaKHtqjdWRBG2B661vFM8X7K0WVAiEA0NUb\n" \
    "gHQAMqvvN/AuT7rPZHpH6iC2ykKIhaI6KX/P6q8=\n" \
    "-----END CERTIFICATE-----\n"

#define ACME_FIXTURE_IP_SAN_LEAF \
    "-----BEGIN CERTIFICATE-----\n" \
    "MIIBVzCB/qADAgECAgEMMAoGCCqGSM49BAMCMCMxITAfBgNVBAMMGEFDTUUgY29u\n" \
    "dHJhY3QgZml4dHVyZSBDQTAgFw0wMDAxMDEwMDAwMDBaGA8yMDk5MDEwMTAwMDAw\n" \
    "MFowFjEUMBIGA1UEAwwLZXhhbXBsZS5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMB\n" \
    "BwNCAAR88nsYjQNPfopSOAMEtRrDwIlp4nfyGzWmC0j8R2aZeAd3VRDbjtBAKT2a\n" \
    "xp90MNu6fa3mPOmCKZ4Et50ieHPRoy4wLDAMBgNVHRMBAf8EAjAAMBwGA1UdEQQV\n" \
    "MBOCC2V4YW1wbGUuY29thwR/AAABMAoGCCqGSM49BAMCA0gAMEUCIBDmrl1EqbIM\n" \
    "uxPGzA7CZNAYYFVg7RROFzkOujTYNjbMAiEArYeCeXvpYMtAHcP3ZcqneLaqplWV\n" \
    "B4vaR+mz3DXsGNs=\n" \
    "-----END CERTIFICATE-----\n"

#define ACME_FIXTURE_WRONG_CA \
    "-----BEGIN CERTIFICATE-----\n" \
    "MIIBSDCB8KADAgECAgENMAoGCCqGSM49BAMCMCMxITAfBgNVBAMMGEFDTUUgY29u\n" \
    "dHJhY3QgZml4dHVyZSBDQTAgFw0wMDAxMDEwMDAwMDBaGA8yMDk5MDEwMTAwMDAw\n" \
    "MFowIzEhMB8GA1UEAwwYQUNNRSBjb250cmFjdCBmaXh0dXJlIENBMFkwEwYHKoZI\n" \
    "zj0CAQYIKoZIzj0DAQcDQgAE4lNKNTLQj7ugLd5lnuYr0AMf4tt4VZbvUJMCRGsD\n" \
    "CFLg8VdaTGM8xxnf7l/ahi12TvyWw/MO4AVcQsI/GE7YxqMTMBEwDwYDVR0TAQH/\n" \
    "BAUwAwEB/zAKBggqhkjOPQQDAgNHADBEAiBmwCV+UpbP9T6qHwPgV0x7G/wZzQ/x\n" \
    "tOBBHCoAVqsLQwIgQfKcGKvWFimph6XXX40mFTuavo0YRS/E88hoQ1Y7iG8=\n" \
    "-----END CERTIFICATE-----\n"

#define ACME_FIXTURE_BAD_SIGNATURE_LEAF \
    "-----BEGIN CERTIFICATE-----\n" \
    "MIIBUDCB+KADAgECAgECMAoGCCqGSM49BAMCMCMxITAfBgNVBAMMGEFDTUUgY29u\n" \
    "dHJhY3QgZml4dHVyZSBDQTAgFw0wMDAxMDEwMDAwMDBaGA8yMDk5MDEwMTAwMDAw\n" \
    "MFowFjEUMBIGA1UEAwwLZXhhbXBsZS5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMB\n" \
    "BwNCAAR88nsYjQNPfopSOAMEtRrDwIlp4nfyGzWmC0j8R2aZeAd3VRDbjtBAKT2a\n" \
    "xp90MNu6fa3mPOmCKZ4Et50ieHPRoygwJjAMBgNVHRMBAf8EAjAAMBYGA1UdEQQP\n" \
    "MA2CC2V4YW1wbGUuY29tMAoGCCqGSM49BAMCA0cAMEQCIC5d6lyUjooQinSCCFZ+\n" \
    "mPo6TTVUQE5/wKyfrQSuQhtjAiAm0nloz1LJCUAqrdnzQXvirLtFHQ61ddDtgnt6\n" \
    "q31o0A==\n" \
    "-----END CERTIFICATE-----\n"


#define ACME_FIXTURE_NAME_CA \
    "-----BEGIN CERTIFICATE-----\n" \
    "MIIECTCCA7CgAwIBAgIBDjAKBggqhkjOPQQDAjCCAYExITAfBgNVBAMMGEFDTUUg\n" \
    "Y29udHJhY3QgZml4dHVyZSBDQTEPMA0GA1UECwwGdW5pdCAwMQ8wDQYDVQQLDAZ1\n" \
    "bml0IDExDzANBgNVBAsMBnVuaXQgMjEPMA0GA1UECwwGdW5pdCAzMQ8wDQYDVQQL\n" \
    "DAZ1bml0IDQxDzANBgNVBAsMBnVuaXQgNTEPMA0GA1UECwwGdW5pdCA2MQ8wDQYD\n" \
    "VQQLDAZ1bml0IDcxDzANBgNVBAsMBnVuaXQgODEPMA0GA1UECwwGdW5pdCA5MRAw\n" \
    "DgYDVQQLDAd1bml0IDEwMRAwDgYDVQQLDAd1bml0IDExMRAwDgYDVQQLDAd1bml0\n" \
    "IDEyMRAwDgYDVQQLDAd1bml0IDEzMRAwDgYDVQQLDAd1bml0IDE0MRAwDgYDVQQL\n" \
    "DAd1bml0IDE1MRAwDgYDVQQLDAd1bml0IDE2MRAwDgYDVQQLDAd1bml0IDE3MRAw\n" \
    "DgYDVQQLDAd1bml0IDE4MRAwDgYDVQQLDAd1bml0IDE5MCAXDTAwMDEwMTAwMDAw\n" \
    "MFoYDzIwOTkwMTAxMDAwMDAwWjCCAYExITAfBgNVBAMMGEFDTUUgY29udHJhY3Qg\n" \
    "Zml4dHVyZSBDQTEPMA0GA1UECwwGdW5pdCAwMQ8wDQYDVQQLDAZ1bml0IDExDzAN\n" \
    "BgNVBAsMBnVuaXQgMjEPMA0GA1UECwwGdW5pdCAzMQ8wDQYDVQQLDAZ1bml0IDQx\n" \
    "DzANBgNVBAsMBnVuaXQgNTEPMA0GA1UECwwGdW5pdCA2MQ8wDQYDVQQLDAZ1bml0\n" \
    "IDcxDzANBgNVBAsMBnVuaXQgODEPMA0GA1UECwwGdW5pdCA5MRAwDgYDVQQLDAd1\n" \
    "bml0IDEwMRAwDgYDVQQLDAd1bml0IDExMRAwDgYDVQQLDAd1bml0IDEyMRAwDgYD\n" \
    "VQQLDAd1bml0IDEzMRAwDgYDVQQLDAd1bml0IDE0MRAwDgYDVQQLDAd1bml0IDE1\n" \
    "MRAwDgYDVQQLDAd1bml0IDE2MRAwDgYDVQQLDAd1bml0IDE3MRAwDgYDVQQLDAd1\n" \
    "bml0IDE4MRAwDgYDVQQLDAd1bml0IDE5MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcD\n" \
    "QgAEXsvk0aYzCkTI9++VHUvxZebGtyHvramF+0FmG8bn/WyHNGQMSZj/fjdLBs4a\n" \
    "ZKLs2CqwNjhPuD2aebEnon1QMqMTMBEwDwYDVR0TAQH/BAUwAwEB/zAKBggqhkjO\n" \
    "PQQDAgNHADBEAiBvWT98qPJV+irlZ+pQWlUtyul76IH5IYvBCKNaFE3euAIgT7bA\n" \
    "AE03rZgOIfRoRBa5i8E7Y70qqcV+fbPiQj6Avj4=\n" \
    "-----END CERTIFICATE-----\n"

#define ACME_FIXTURE_NAME_LEAF \
    "-----BEGIN CERTIFICATE-----\n" \
    "MIICszCCAligAwIBAgIBDzAKBggqhkjOPQQDAjCCAYExITAfBgNVBAMMGEFDTUUg\n" \
    "Y29udHJhY3QgZml4dHVyZSBDQTEPMA0GA1UECwwGdW5pdCAwMQ8wDQYDVQQLDAZ1\n" \
    "bml0IDExDzANBgNVBAsMBnVuaXQgMjEPMA0GA1UECwwGdW5pdCAzMQ8wDQYDVQQL\n" \
    "DAZ1bml0IDQxDzANBgNVBAsMBnVuaXQgNTEPMA0GA1UECwwGdW5pdCA2MQ8wDQYD\n" \
    "VQQLDAZ1bml0IDcxDzANBgNVBAsMBnVuaXQgODEPMA0GA1UECwwGdW5pdCA5MRAw\n" \
    "DgYDVQQLDAd1bml0IDEwMRAwDgYDVQQLDAd1bml0IDExMRAwDgYDVQQLDAd1bml0\n" \
    "IDEyMRAwDgYDVQQLDAd1bml0IDEzMRAwDgYDVQQLDAd1bml0IDE0MRAwDgYDVQQL\n" \
    "DAd1bml0IDE1MRAwDgYDVQQLDAd1bml0IDE2MRAwDgYDVQQLDAd1bml0IDE3MRAw\n" \
    "DgYDVQQLDAd1bml0IDE4MRAwDgYDVQQLDAd1bml0IDE5MCAXDTAwMDEwMTAwMDAw\n" \
    "MFoYDzIwOTkwMTAxMDAwMDAwWjAWMRQwEgYDVQQDDAtleGFtcGxlLmNvbTBZMBMG\n" \
    "ByqGSM49AgEGCCqGSM49AwEHA0IABHzyexiNA09+ilI4AwS1GsPAiWnid/IbNaYL\n" \
    "SPxHZpl4B3dVENuO0EApPZrGn3Qw27p9reY86YIpngS3nSJ4c9GjKDAmMAwGA1Ud\n" \
    "EwEB/wQCMAAwFgYDVR0RBA8wDYILZXhhbXBsZS5jb20wCgYIKoZIzj0EAwIDSQAw\n" \
    "RgIhALANNU1qRS3xD6NU8U80ZF8PPld1JD7kwtDLNmkEUfQEAiEA+h+MUzF/yazG\n" \
    "D1MAb90fVIEMI8r/VXw51mJCuQrNaT8=\n" \
    "-----END CERTIFICATE-----\n"


#define ACME_FIXTURE_RSA_CA \
    "-----BEGIN CERTIFICATE-----\n" \
    "MIICzDCCAbSgAwIBAgIBEDANBgkqhkiG9w0BAQsFADAeMRwwGgYDVQQDDBNBQ01F\n" \
    "IFJTQSBmaXh0dXJlIENBMCAXDTAwMDEwMTAwMDAwMFoYDzIwOTkwMTAxMDAwMDAw\n" \
    "WjAeMRwwGgYDVQQDDBNBQ01FIFJTQSBmaXh0dXJlIENBMIIBIjANBgkqhkiG9w0B\n" \
    "AQEFAAOCAQ8AMIIBCgKCAQEAuLmCjIoLApEPaAUsfPPhgGHacTyDXfl7+3oH4KcV\n" \
    "Qv5DGcQIyt0pDcPd46TN5XF8vVjyD7eDlI8FJG5T0JEUo5DAcfs0yoMaD//xBmpu\n" \
    "pLnL+Tt5DW1TaVOEDZRC0HOz0LUhWpwWTFFlQJ9EuiWxZnZnuSfSfxZ+eFKPoHho\n" \
    "UHLC1YrhsuN+u6RyjJCCoyL4fkp9kR3t8tzknCz8ww4TqS9pXDWdXYixr8OVUlLp\n" \
    "1ZU2msYiT7sLqiu4wU66XJh8iLJad5XeuskcWC6DsEQSO93Q+HW1lItCbKjBAL2O\n" \
    "guGFR0BfssMb1YFBwnJCYh6B8XV9IAHR6sh3CsdDFjXfyQIDAQABoxMwETAPBgNV\n" \
    "HRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQCC/jHde6+HPIVmyc0zB4bc\n" \
    "7QlIPDIXS1y/qv9YZGhdkkjp12VZqgmSgJUbvnRE/lm/k/1Ne4zC6B0qbTwMcXFX\n" \
    "UGLV7yzaJb/5v/kGww3/YVDjG7YYF0ChN8305ByF5l0zCqIR+k3leD8JRbTPRhnJ\n" \
    "9k6ZTVjs3hLm50rfkHVkqaL+Pd4k87VLZcp9krLodD9u1C/VY0QqZDeREaNi4xvg\n" \
    "4YuV+3XWT6sa0dKJY/uzr8Jagr79mwGh5CYCiZJo/3iecSUqSJcA71ARsXhgSfPN\n" \
    "MLWgWmoMTI3qKf9GjRM+Y8nozk72cz7hL9qZbH8NBQAfq8r32BCoe958ZjG6mYDH\n" \
    "-----END CERTIFICATE-----\n"

#define ACME_FIXTURE_RSA_SIGNED_LEAF \
    "-----BEGIN CERTIFICATE-----\n" \
    "MIICDTCB9qADAgECAgERMA0GCSqGSIb3DQEBCwUAMB4xHDAaBgNVBAMME0FDTUUg\n" \
    "UlNBIGZpeHR1cmUgQ0EwIBcNMDAwMTAxMDAwMDAwWhgPMjA5OTAxMDEwMDAwMDBa\n" \
    "MBYxFDASBgNVBAMMC2V4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcD\n" \
    "QgAEfPJ7GI0DT36KUjgDBLUaw8CJaeJ38hs1pgtI/EdmmXgHd1UQ247QQCk9msaf\n" \
    "dDDbun2t5jzpgimeBLedInhz0aMoMCYwDAYDVR0TAQH/BAIwADAWBgNVHREEDzAN\n" \
    "ggtleGFtcGxlLmNvbTANBgkqhkiG9w0BAQsFAAOCAQEAsWTmJIRSdsbWEaDnFm2o\n" \
    "jG8Uxe8rT3y8/Lq+zWYN2NSvxA0fGt9JPlcXV/6tBacC7vlYsVL5Bi6IwoR2iZJb\n" \
    "0nOM6jJ7aBqHkj8CTkSDmGzZ+2FfklH/MmV7ZbRbpnwm/HEUBCrJfcNhJmEorpR9\n" \
    "QorItMqASvw/gk+UqfGB8k8yX5uC0VptZ+OKBrDGv5zbaTF4FY3x/Lwr3r5bJqJ3\n" \
    "HGl18dSS8qka0bUE0IIlzqUErzTFMmO01+FOFfzd5oyvAFL0s1V8+832WZR+UjL8\n" \
    "F5m12nh+YhppyurujIaoeVZUTlSQKy978wj2rqfubR0TDbmOEYpOpn/iSxwiOeVk\n" \
    "Fw==\n" \
    "-----END CERTIFICATE-----\n"

#endif
