#!/usr/bin/env python3
"""Generate a reduced operator config from an ONNX model graph."""

from __future__ import annotations

import argparse
from collections import defaultdict
from pathlib import Path

import onnx


def normalize_domain(domain: str) -> str:
    return "ai.onnx" if not domain else domain


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model", required=True, help="Path to the ONNX model.")
    parser.add_argument("--output", required=True, help="Path to the config file.")
    args = parser.parse_args()

    model_path = Path(args.model)
    output_path = Path(args.output)

    model = onnx.load_model(model_path)

    opsets: dict[str, int] = {}
    for opset in model.opset_import:
        opsets[normalize_domain(opset.domain)] = opset.version

    required_ops: dict[str, set[str]] = defaultdict(set)
    for node in model.graph.node:
        required_ops[normalize_domain(node.domain)].add(node.op_type)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write("# Auto-generated by generate_reduced_ops_config.py\n")
        handle.write(f"# Source model: {model_path.name}\n")
        for domain in sorted(required_ops):
            opset = opsets.get(domain, 1)
            ops = ",".join(sorted(required_ops[domain]))
            handle.write(f"{domain};{opset};{ops}\n")

    print(f"Wrote reduced operator config to {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
