/* 此文件由 tools/generate_extension_features.py 生成，请勿直接修改。 */
#ifndef XWS_FEATURES_H
#define XWS_FEATURES_H

/* websocket_group_future 及其直接依赖。 */
#if defined(XWS_MODULE_ALL) || defined(XWS_MODULE_WEBSOCKET_GROUP_FUTURE)
#ifndef XWS_FEATURE_WEBSOCKET_GROUP_FUTURE
#define XWS_FEATURE_WEBSOCKET_GROUP_FUTURE
#endif
#ifndef XWS_MODULE_WEBSOCKET_GROUP
#define XWS_MODULE_WEBSOCKET_GROUP
#endif
#ifndef XWS_MODULE_WEBSOCKET_CONNECTION_REF_FUTURE
#define XWS_MODULE_WEBSOCKET_CONNECTION_REF_FUTURE
#endif
#ifndef XRT_MODULE_FUTURE
#define XRT_MODULE_FUTURE
#endif
#endif

/* websocket_group 及其直接依赖。 */
#if defined(XWS_MODULE_ALL) || defined(XWS_MODULE_WEBSOCKET_GROUP)
#ifndef XWS_FEATURE_WEBSOCKET_GROUP
#define XWS_FEATURE_WEBSOCKET_GROUP
#endif
#ifndef XWS_MODULE_WEBSOCKET_CONNECTION
#define XWS_MODULE_WEBSOCKET_CONNECTION
#endif
#ifndef XRT_MODULE_SET
#define XRT_MODULE_SET
#endif
#ifndef XRT_MODULE_MUTEX
#define XRT_MODULE_MUTEX
#endif
#endif

/* websocket_connection_ref_future 及其直接依赖。 */
#if defined(XWS_MODULE_ALL) || defined(XWS_MODULE_WEBSOCKET_CONNECTION_REF_FUTURE)
#ifndef XWS_FEATURE_WEBSOCKET_CONNECTION_REF_FUTURE
#define XWS_FEATURE_WEBSOCKET_CONNECTION_REF_FUTURE
#endif
#ifndef XWS_MODULE_WEBSOCKET_CONNECTION_REF
#define XWS_MODULE_WEBSOCKET_CONNECTION_REF
#endif
#ifndef XWS_MODULE_WEBSOCKET_CONNECTION_FUTURE
#define XWS_MODULE_WEBSOCKET_CONNECTION_FUTURE
#endif
#endif

/* websocket_connection_future 及其直接依赖。 */
#if defined(XWS_MODULE_ALL) || defined(XWS_MODULE_WEBSOCKET_CONNECTION_FUTURE)
#ifndef XWS_FEATURE_WEBSOCKET_CONNECTION_FUTURE
#define XWS_FEATURE_WEBSOCKET_CONNECTION_FUTURE
#endif
#ifndef XWS_MODULE_WEBSOCKET_CONNECTION
#define XWS_MODULE_WEBSOCKET_CONNECTION
#endif
#ifndef XRT_MODULE_FUTURE
#define XRT_MODULE_FUTURE
#endif
#endif

/* websocket_writer_ref 及其直接依赖。 */
#if defined(XWS_MODULE_ALL) || defined(XWS_MODULE_WEBSOCKET_WRITER_REF)
#ifndef XWS_FEATURE_WEBSOCKET_WRITER_REF
#define XWS_FEATURE_WEBSOCKET_WRITER_REF
#endif
#ifndef XWS_MODULE_WEBSOCKET_WRITER
#define XWS_MODULE_WEBSOCKET_WRITER
#endif
#ifndef XWS_MODULE_WEBSOCKET_CONNECTION_REF
#define XWS_MODULE_WEBSOCKET_CONNECTION_REF
#endif
#endif

/* websocket_writer_deflate 及其直接依赖。 */
#if defined(XWS_MODULE_ALL) || defined(XWS_MODULE_WEBSOCKET_WRITER_DEFLATE)
#ifndef XWS_FEATURE_WEBSOCKET_WRITER_DEFLATE
#define XWS_FEATURE_WEBSOCKET_WRITER_DEFLATE
#endif
#ifndef XWS_MODULE_WEBSOCKET_WRITER
#define XWS_MODULE_WEBSOCKET_WRITER
#endif
#ifndef XWS_MODULE_WEBSOCKET_CONNECTION_DEFLATE
#define XWS_MODULE_WEBSOCKET_CONNECTION_DEFLATE
#endif
#endif

/* websocket_writer 及其直接依赖。 */
#if defined(XWS_MODULE_ALL) || defined(XWS_MODULE_WEBSOCKET_WRITER)
#ifndef XWS_FEATURE_WEBSOCKET_WRITER
#define XWS_FEATURE_WEBSOCKET_WRITER
#endif
#ifndef XWS_MODULE_WEBSOCKET_CONNECTION
#define XWS_MODULE_WEBSOCKET_CONNECTION
#endif
#endif

/* websocket_connection_ref 及其直接依赖。 */
#if defined(XWS_MODULE_ALL) || defined(XWS_MODULE_WEBSOCKET_CONNECTION_REF)
#ifndef XWS_FEATURE_WEBSOCKET_CONNECTION_REF
#define XWS_FEATURE_WEBSOCKET_CONNECTION_REF
#endif
#ifndef XWS_MODULE_WEBSOCKET_CONNECTION
#define XWS_MODULE_WEBSOCKET_CONNECTION
#endif
#endif

/* websocket_client_deflate 及其直接依赖。 */
#if defined(XWS_MODULE_ALL) || defined(XWS_MODULE_WEBSOCKET_CLIENT_DEFLATE)
#ifndef XWS_FEATURE_WEBSOCKET_CLIENT_DEFLATE
#define XWS_FEATURE_WEBSOCKET_CLIENT_DEFLATE
#endif
#ifndef XWS_MODULE_WEBSOCKET_CLIENT
#define XWS_MODULE_WEBSOCKET_CLIENT
#endif
#ifndef XWS_MODULE_WEBSOCKET_CONNECTION_DEFLATE
#define XWS_MODULE_WEBSOCKET_CONNECTION_DEFLATE
#endif
#ifndef XRT_MODULE_WEBSOCKET_DEFLATE
#define XRT_MODULE_WEBSOCKET_DEFLATE
#endif
#endif

/* websocket_client_future 及其直接依赖。 */
#if defined(XWS_MODULE_ALL) || defined(XWS_MODULE_WEBSOCKET_CLIENT_FUTURE)
#ifndef XWS_FEATURE_WEBSOCKET_CLIENT_FUTURE
#define XWS_FEATURE_WEBSOCKET_CLIENT_FUTURE
#endif
#ifndef XWS_MODULE_WEBSOCKET_CLIENT
#define XWS_MODULE_WEBSOCKET_CLIENT
#endif
#ifndef XWS_MODULE_WEBSOCKET_HTTP_FUTURE
#define XWS_MODULE_WEBSOCKET_HTTP_FUTURE
#endif
#ifndef XRT_MODULE_FUTURE_BRIDGE
#define XRT_MODULE_FUTURE_BRIDGE
#endif
#endif

/* websocket_server_deflate 及其直接依赖。 */
#if defined(XWS_MODULE_ALL) || defined(XWS_MODULE_WEBSOCKET_SERVER_DEFLATE)
#ifndef XWS_FEATURE_WEBSOCKET_SERVER_DEFLATE
#define XWS_FEATURE_WEBSOCKET_SERVER_DEFLATE
#endif
#ifndef XWS_MODULE_WEBSOCKET_SERVER
#define XWS_MODULE_WEBSOCKET_SERVER
#endif
#ifndef XWS_MODULE_WEBSOCKET_CONNECTION_DEFLATE
#define XWS_MODULE_WEBSOCKET_CONNECTION_DEFLATE
#endif
#ifndef XRT_MODULE_WEBSOCKET_DEFLATE
#define XRT_MODULE_WEBSOCKET_DEFLATE
#endif
#endif

/* websocket_connection_deflate 及其直接依赖。 */
#if defined(XWS_MODULE_ALL) || defined(XWS_MODULE_WEBSOCKET_CONNECTION_DEFLATE)
#ifndef XWS_FEATURE_WEBSOCKET_CONNECTION_DEFLATE
#define XWS_FEATURE_WEBSOCKET_CONNECTION_DEFLATE
#endif
#ifndef XWS_MODULE_WEBSOCKET_CONNECTION
#define XWS_MODULE_WEBSOCKET_CONNECTION
#endif
#ifndef XRT_MODULE_WEBSOCKET_INFLATER
#define XRT_MODULE_WEBSOCKET_INFLATER
#endif
#ifndef XRT_MODULE_WEBSOCKET_DEFLATER
#define XRT_MODULE_WEBSOCKET_DEFLATER
#endif
#endif

/* websocket_server_future 及其直接依赖。 */
#if defined(XWS_MODULE_ALL) || defined(XWS_MODULE_WEBSOCKET_SERVER_FUTURE)
#ifndef XWS_FEATURE_WEBSOCKET_SERVER_FUTURE
#define XWS_FEATURE_WEBSOCKET_SERVER_FUTURE
#endif
#ifndef XWS_MODULE_WEBSOCKET_SERVER
#define XWS_MODULE_WEBSOCKET_SERVER
#endif
#ifndef XWS_MODULE_WEBSOCKET_HTTP_FUTURE
#define XWS_MODULE_WEBSOCKET_HTTP_FUTURE
#endif
#ifndef XRT_MODULE_FUTURE_BRIDGE
#define XRT_MODULE_FUTURE_BRIDGE
#endif
#endif

/* websocket_client_https 及其直接依赖。 */
#if defined(XWS_MODULE_ALL) || defined(XWS_MODULE_WEBSOCKET_CLIENT_HTTPS)
#ifndef XWS_FEATURE_WEBSOCKET_CLIENT_HTTPS
#define XWS_FEATURE_WEBSOCKET_CLIENT_HTTPS
#endif
#ifndef XWS_MODULE_WEBSOCKET_CLIENT
#define XWS_MODULE_WEBSOCKET_CLIENT
#endif
#ifndef XWS_MODULE_WEBSOCKET_CONNECTION_TLS
#define XWS_MODULE_WEBSOCKET_CONNECTION_TLS
#endif
#ifndef XHTTP_MODULE_HTTP_CLIENT_HTTPS
#define XHTTP_MODULE_HTTP_CLIENT_HTTPS
#endif
#endif

/* websocket_server_tls 及其直接依赖。 */
#if defined(XWS_MODULE_ALL) || defined(XWS_MODULE_WEBSOCKET_SERVER_TLS)
#ifndef XWS_FEATURE_WEBSOCKET_SERVER_TLS
#define XWS_FEATURE_WEBSOCKET_SERVER_TLS
#endif
#ifndef XWS_MODULE_WEBSOCKET_SERVER
#define XWS_MODULE_WEBSOCKET_SERVER
#endif
#ifndef XWS_MODULE_WEBSOCKET_CONNECTION_TLS
#define XWS_MODULE_WEBSOCKET_CONNECTION_TLS
#endif
#ifndef XHTTP_MODULE_HTTP_SERVER_TLS
#define XHTTP_MODULE_HTTP_SERVER_TLS
#endif
#endif

/* websocket_connection_tls 及其直接依赖。 */
#if defined(XWS_MODULE_ALL) || defined(XWS_MODULE_WEBSOCKET_CONNECTION_TLS)
#ifndef XWS_FEATURE_WEBSOCKET_CONNECTION_TLS
#define XWS_FEATURE_WEBSOCKET_CONNECTION_TLS
#endif
#ifndef XWS_MODULE_WEBSOCKET_CONNECTION
#define XWS_MODULE_WEBSOCKET_CONNECTION
#endif
#ifndef XRT_MODULE_TLS_STREAM
#define XRT_MODULE_TLS_STREAM
#endif
#endif

/* websocket_client 及其直接依赖。 */
#if defined(XWS_MODULE_ALL) || defined(XWS_MODULE_WEBSOCKET_CLIENT)
#ifndef XWS_FEATURE_WEBSOCKET_CLIENT
#define XWS_FEATURE_WEBSOCKET_CLIENT
#endif
#ifndef XRT_MODULE_WEBSOCKET_KEYGEN
#define XRT_MODULE_WEBSOCKET_KEYGEN
#endif
#ifndef XWS_MODULE_WEBSOCKET_CONNECTION
#define XWS_MODULE_WEBSOCKET_CONNECTION
#endif
#ifndef XRT_MODULE_HTTP_UPGRADE
#define XRT_MODULE_HTTP_UPGRADE
#endif
#ifndef XHTTP_MODULE_HTTP_CLIENT
#define XHTTP_MODULE_HTTP_CLIENT
#endif
#endif

/* websocket_server_router 及其直接依赖。 */
#if defined(XWS_MODULE_ALL) || defined(XWS_MODULE_WEBSOCKET_SERVER_ROUTER)
#ifndef XWS_FEATURE_WEBSOCKET_SERVER_ROUTER
#define XWS_FEATURE_WEBSOCKET_SERVER_ROUTER
#endif
#ifndef XWS_MODULE_WEBSOCKET_SERVER
#define XWS_MODULE_WEBSOCKET_SERVER
#endif
#ifndef XHTTP_MODULE_HTTP_SERVER_ROUTER
#define XHTTP_MODULE_HTTP_SERVER_ROUTER
#endif
#endif

/* websocket_server 及其直接依赖。 */
#if defined(XWS_MODULE_ALL) || defined(XWS_MODULE_WEBSOCKET_SERVER)
#ifndef XWS_FEATURE_WEBSOCKET_SERVER
#define XWS_FEATURE_WEBSOCKET_SERVER
#endif
#ifndef XRT_MODULE_WEBSOCKET_HANDSHAKE
#define XRT_MODULE_WEBSOCKET_HANDSHAKE
#endif
#ifndef XWS_MODULE_WEBSOCKET_CONNECTION
#define XWS_MODULE_WEBSOCKET_CONNECTION
#endif
#ifndef XRT_MODULE_HTTP_UPGRADE
#define XRT_MODULE_HTTP_UPGRADE
#endif
#ifndef XHTTP_MODULE_HTTP_SERVER_UPGRADE
#define XHTTP_MODULE_HTTP_SERVER_UPGRADE
#endif
#endif

/* websocket_http_future 及其直接依赖。 */
#if defined(XWS_MODULE_ALL) || defined(XWS_MODULE_WEBSOCKET_HTTP_FUTURE)
#ifndef XWS_FEATURE_WEBSOCKET_HTTP_FUTURE
#define XWS_FEATURE_WEBSOCKET_HTTP_FUTURE
#endif
#ifndef XWS_MODULE_WEBSOCKET_CONNECTION
#define XWS_MODULE_WEBSOCKET_CONNECTION
#endif
#endif

/* websocket_connection 及其直接依赖。 */
#if defined(XWS_MODULE_ALL) || defined(XWS_MODULE_WEBSOCKET_CONNECTION)
#ifndef XWS_FEATURE_WEBSOCKET_CONNECTION
#define XWS_FEATURE_WEBSOCKET_CONNECTION
#endif
#ifndef XRT_MODULE_WEBSOCKET_MESSAGE
#define XRT_MODULE_WEBSOCKET_MESSAGE
#endif
#ifndef XRT_MODULE_RANDOM_SECURE
#define XRT_MODULE_RANDOM_SECURE
#endif
#ifndef XRT_MODULE_NET_TCP
#define XRT_MODULE_NET_TCP
#endif
#ifndef XRT_MODULE_SPIN
#define XRT_MODULE_SPIN
#endif
#endif

#endif /* XWS_FEATURES_H */
