#define XRT_IMPLEMENTATION
#include "../../single/xrt.h"



#if !defined(TEST_SINGLE_TLS_STREAM_BACKEND)
	#define TEST_SINGLE_TLS_STREAM_BACKEND XNET_PORT_SELECT
	#define TEST_SINGLE_TLS_STREAM_BACKEND_NAME "single select"
#endif

#define TEST_TLS_STREAM_BACKEND TEST_SINGLE_TLS_STREAM_BACKEND
#define TEST_TLS_STREAM_BACKEND_NAME TEST_SINGLE_TLS_STREAM_BACKEND_NAME
#include "../tls/test_tls_stream.c"
