/* 此文件由 tools/generate_extension_features.py 生成，请勿直接修改。 */
#ifndef XHTTP_FEATURES_H
#define XHTTP_FEATURES_H

/* http_server_router_tls 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_SERVER_ROUTER_TLS)
#ifndef XHTTP_FEATURE_HTTP_SERVER_ROUTER_TLS
#define XHTTP_FEATURE_HTTP_SERVER_ROUTER_TLS
#endif
#ifndef XHTTP_MODULE_HTTP_SERVER_ROUTER
#define XHTTP_MODULE_HTTP_SERVER_ROUTER
#endif
#ifndef XHTTP_MODULE_HTTP_SERVER_TLS
#define XHTTP_MODULE_HTTP_SERVER_TLS
#endif
#endif

/* http_server_mux_tls 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_SERVER_MUX_TLS)
#ifndef XHTTP_FEATURE_HTTP_SERVER_MUX_TLS
#define XHTTP_FEATURE_HTTP_SERVER_MUX_TLS
#endif
#ifndef XHTTP_MODULE_HTTP_SERVER_MUX
#define XHTTP_MODULE_HTTP_SERVER_MUX
#endif
#ifndef XHTTP_MODULE_HTTP_SERVER_TLS
#define XHTTP_MODULE_HTTP_SERVER_TLS
#endif
#endif

/* http_server_mux 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_SERVER_MUX)
#ifndef XHTTP_FEATURE_HTTP_SERVER_MUX
#define XHTTP_FEATURE_HTTP_SERVER_MUX
#endif
#ifndef XHTTP_MODULE_HTTP_SERVER_ROUTER
#define XHTTP_MODULE_HTTP_SERVER_ROUTER
#endif
#ifndef XRT_MODULE_RWLOCK
#define XRT_MODULE_RWLOCK
#endif
#endif

/* http_server_middleware 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_SERVER_MIDDLEWARE)
#ifndef XHTTP_FEATURE_HTTP_SERVER_MIDDLEWARE
#define XHTTP_FEATURE_HTTP_SERVER_MIDDLEWARE
#endif
#ifndef XHTTP_MODULE_HTTP_SERVER_ROUTER
#define XHTTP_MODULE_HTTP_SERVER_ROUTER
#endif
#endif

/* http_server_router 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_SERVER_ROUTER)
#ifndef XHTTP_FEATURE_HTTP_SERVER_ROUTER
#define XHTTP_FEATURE_HTTP_SERVER_ROUTER
#endif
#ifndef XHTTP_MODULE_HTTP_ROUTER
#define XHTTP_MODULE_HTTP_ROUTER
#endif
#ifndef XHTTP_MODULE_HTTP_SERVER
#define XHTTP_MODULE_HTTP_SERVER
#endif
#endif

/* http_server_compress 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_SERVER_COMPRESS)
#ifndef XHTTP_FEATURE_HTTP_SERVER_COMPRESS
#define XHTTP_FEATURE_HTTP_SERVER_COMPRESS
#endif
#ifndef XHTTP_MODULE_HTTP_REPLY_COMPRESS
#define XHTTP_MODULE_HTTP_REPLY_COMPRESS
#endif
#ifndef XHTTP_MODULE_HTTP_SERVER_REQUEST
#define XHTTP_MODULE_HTTP_SERVER_REQUEST
#endif
#endif

/* http_reply_compress 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_REPLY_COMPRESS)
#ifndef XHTTP_FEATURE_HTTP_REPLY_COMPRESS
#define XHTTP_FEATURE_HTTP_REPLY_COMPRESS
#endif
#ifndef XHTTP_MODULE_HTTP_SERVER_REPLY
#define XHTTP_MODULE_HTTP_SERVER_REPLY
#endif
#ifndef XRT_MODULE_HTTP_ENCODING
#define XRT_MODULE_HTTP_ENCODING
#endif
#ifndef XHTTP_MODULE_HTTP_VARY
#define XHTTP_MODULE_HTTP_VARY
#endif
#ifndef XHTTP_MODULE_HTTP_CACHE
#define XHTTP_MODULE_HTTP_CACHE
#endif
#ifndef XHTTP_MODULE_HTTP_BODY_DEFLATE
#define XHTTP_MODULE_HTTP_BODY_DEFLATE
#endif
#ifndef XHTTP_MODULE_MIME
#define XHTTP_MODULE_MIME
#endif
#ifndef XHTTP_MODULE_HTTP_ETAG
#define XHTTP_MODULE_HTTP_ETAG
#endif
#endif

/* http_router 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_ROUTER)
#ifndef XHTTP_FEATURE_HTTP_ROUTER
#define XHTTP_FEATURE_HTTP_ROUTER
#endif
#ifndef XHTTP_MODULE_HTTP_ROUTE
#define XHTTP_MODULE_HTTP_ROUTE
#endif
#endif

/* http_route 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_ROUTE)
#ifndef XHTTP_FEATURE_HTTP_ROUTE
#define XHTTP_FEATURE_HTTP_ROUTE
#endif
#ifndef XRT_MODULE_HTTP
#define XRT_MODULE_HTTP
#endif
#endif

/* http_server_static 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_SERVER_STATIC)
#ifndef XHTTP_FEATURE_HTTP_SERVER_STATIC
#define XHTTP_FEATURE_HTTP_SERVER_STATIC
#endif
#ifndef XRT_MODULE_CODEC_HEX
#define XRT_MODULE_CODEC_HEX
#endif
#ifndef XHTTP_MODULE_HTTP_SERVER_FUTURE
#define XHTTP_MODULE_HTTP_SERVER_FUTURE
#endif
#ifndef XHTTP_MODULE_HTTP_SERVER_BODY_ASYNC
#define XHTTP_MODULE_HTTP_SERVER_BODY_ASYNC
#endif
#ifndef XHTTP_MODULE_HTTP_STATIC_PATH
#define XHTTP_MODULE_HTTP_STATIC_PATH
#endif
#ifndef XHTTP_MODULE_HTTP_STATIC_FILE
#define XHTTP_MODULE_HTTP_STATIC_FILE
#endif
#ifndef XHTTP_MODULE_HTTP_STATIC_PLAN
#define XHTTP_MODULE_HTTP_STATIC_PLAN
#endif
#ifndef XHTTP_MODULE_HTTP_STATIC_RESPONSE
#define XHTTP_MODULE_HTTP_STATIC_RESPONSE
#endif
#ifndef XHTTP_MODULE_HTTP_STATIC_MULTIPART_BODY
#define XHTTP_MODULE_HTTP_STATIC_MULTIPART_BODY
#endif
#ifndef XHTTP_MODULE_MIME_TYPES
#define XHTTP_MODULE_MIME_TYPES
#endif
#ifndef XRT_MODULE_RANDOM_SECURE
#define XRT_MODULE_RANDOM_SECURE
#endif
#endif

/* http_server_file 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_SERVER_FILE)
#ifndef XHTTP_FEATURE_HTTP_SERVER_FILE
#define XHTTP_FEATURE_HTTP_SERVER_FILE
#endif
#ifndef XHTTP_MODULE_HTTP_SERVER_FUTURE
#define XHTTP_MODULE_HTTP_SERVER_FUTURE
#endif
#ifndef XHTTP_MODULE_HTTP_BODY_FILE
#define XHTTP_MODULE_HTTP_BODY_FILE
#endif
#ifndef XHTTP_MODULE_HTTP_SERVER_BODY_ASYNC
#define XHTTP_MODULE_HTTP_SERVER_BODY_ASYNC
#endif
#endif

/* http_server_future 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_SERVER_FUTURE)
#ifndef XHTTP_FEATURE_HTTP_SERVER_FUTURE
#define XHTTP_FEATURE_HTTP_SERVER_FUTURE
#endif
#ifndef XHTTP_MODULE_HTTP_SERVER
#define XHTTP_MODULE_HTTP_SERVER
#endif
#ifndef XRT_MODULE_FUTURE_CONTINUE
#define XRT_MODULE_FUTURE_CONTINUE
#endif
#endif

/* http_server_upgrade 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_SERVER_UPGRADE)
#ifndef XHTTP_FEATURE_HTTP_SERVER_UPGRADE
#define XHTTP_FEATURE_HTTP_SERVER_UPGRADE
#endif
#ifndef XHTTP_MODULE_HTTP_SERVER
#define XHTTP_MODULE_HTTP_SERVER
#endif
#endif

/* http_server_raw 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_SERVER_RAW)
#ifndef XHTTP_FEATURE_HTTP_SERVER_RAW
#define XHTTP_FEATURE_HTTP_SERVER_RAW
#endif
#ifndef XHTTP_MODULE_HTTP_SERVER
#define XHTTP_MODULE_HTTP_SERVER
#endif
#endif

/* http_server_body_async 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_SERVER_BODY_ASYNC)
#ifndef XHTTP_FEATURE_HTTP_SERVER_BODY_ASYNC
#define XHTTP_FEATURE_HTTP_SERVER_BODY_ASYNC
#endif
#ifndef XHTTP_MODULE_HTTP_SERVER
#define XHTTP_MODULE_HTTP_SERVER
#endif
#ifndef XHTTP_MODULE_HTTP_SERVER_RESPONSE_ASYNC
#define XHTTP_MODULE_HTTP_SERVER_RESPONSE_ASYNC
#endif
#endif

/* http_server_tls 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_SERVER_TLS)
#ifndef XHTTP_FEATURE_HTTP_SERVER_TLS
#define XHTTP_FEATURE_HTTP_SERVER_TLS
#endif
#ifndef XHTTP_MODULE_HTTP_SERVER
#define XHTTP_MODULE_HTTP_SERVER
#endif
#ifndef XRT_MODULE_TLS_STREAM
#define XRT_MODULE_TLS_STREAM
#endif
#endif

/* http_server 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_SERVER)
#ifndef XHTTP_FEATURE_HTTP_SERVER
#define XHTTP_FEATURE_HTTP_SERVER
#endif
#ifndef XHTTP_MODULE_HTTP_SERVER_EXCHANGE
#define XHTTP_MODULE_HTTP_SERVER_EXCHANGE
#endif
#ifndef XHTTP_MODULE_HTTP_SERVER_RESPONSE
#define XHTTP_MODULE_HTTP_SERVER_RESPONSE
#endif
#ifndef XRT_MODULE_NET_TCP_SERVER
#define XRT_MODULE_NET_TCP_SERVER
#endif
#endif

/* mime_types 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_MIME_TYPES)
#ifndef XHTTP_FEATURE_MIME_TYPES
#define XHTTP_FEATURE_MIME_TYPES
#endif
#endif

/* http_body_decode 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_BODY_DECODE)
#ifndef XHTTP_FEATURE_HTTP_BODY_DECODE
#define XHTTP_FEATURE_HTTP_BODY_DECODE
#endif
#ifndef XHTTP_MODULE_HTTP_BODY_INFLATE
#define XHTTP_MODULE_HTTP_BODY_INFLATE
#endif
#ifndef XRT_MODULE_HTTP_ENCODING
#define XRT_MODULE_HTTP_ENCODING
#endif
#endif

/* http_body_inflate 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_BODY_INFLATE)
#ifndef XHTTP_FEATURE_HTTP_BODY_INFLATE
#define XHTTP_FEATURE_HTTP_BODY_INFLATE
#endif
#ifndef XHTTP_MODULE_HTTP_BODY_TRANSFORM
#define XHTTP_MODULE_HTTP_BODY_TRANSFORM
#endif
#ifndef XRT_MODULE_INFLATE
#define XRT_MODULE_INFLATE
#endif
#endif

/* http_body_deflate 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_BODY_DEFLATE)
#ifndef XHTTP_FEATURE_HTTP_BODY_DEFLATE
#define XHTTP_FEATURE_HTTP_BODY_DEFLATE
#endif
#ifndef XHTTP_MODULE_HTTP_BODY_TRANSFORM
#define XHTTP_MODULE_HTTP_BODY_TRANSFORM
#endif
#ifndef XRT_MODULE_DEFLATE
#define XRT_MODULE_DEFLATE
#endif
#endif

/* http_body_transform 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_BODY_TRANSFORM)
#ifndef XHTTP_FEATURE_HTTP_BODY_TRANSFORM
#define XHTTP_FEATURE_HTTP_BODY_TRANSFORM
#endif
#ifndef XHTTP_MODULE_HTTP_BODY
#define XHTTP_MODULE_HTTP_BODY
#endif
#endif

/* http_server_response_async 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_SERVER_RESPONSE_ASYNC)
#ifndef XHTTP_FEATURE_HTTP_SERVER_RESPONSE_ASYNC
#define XHTTP_FEATURE_HTTP_SERVER_RESPONSE_ASYNC
#endif
#ifndef XHTTP_MODULE_HTTP_SERVER_RESPONSE
#define XHTTP_MODULE_HTTP_SERVER_RESPONSE
#endif
#ifndef XHTTP_MODULE_HTTP_BODY_ASYNC
#define XHTTP_MODULE_HTTP_BODY_ASYNC
#endif
#endif

/* http_client_stream_async 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_CLIENT_STREAM_ASYNC)
#ifndef XHTTP_FEATURE_HTTP_CLIENT_STREAM_ASYNC
#define XHTTP_FEATURE_HTTP_CLIENT_STREAM_ASYNC
#endif
#ifndef XHTTP_MODULE_HTTP_CLIENT_STREAM
#define XHTTP_MODULE_HTTP_CLIENT_STREAM
#endif
#ifndef XHTTP_MODULE_HTTP_EXCHANGE_ASYNC
#define XHTTP_MODULE_HTTP_EXCHANGE_ASYNC
#endif
#endif

/* http_exchange_async 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_EXCHANGE_ASYNC)
#ifndef XHTTP_FEATURE_HTTP_EXCHANGE_ASYNC
#define XHTTP_FEATURE_HTTP_EXCHANGE_ASYNC
#endif
#ifndef XHTTP_MODULE_HTTP_EXCHANGE
#define XHTTP_MODULE_HTTP_EXCHANGE
#endif
#ifndef XHTTP_MODULE_HTTP_BODY_ASYNC
#define XHTTP_MODULE_HTTP_BODY_ASYNC
#endif
#endif

/* http_server_response 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_SERVER_RESPONSE)
#ifndef XHTTP_FEATURE_HTTP_SERVER_RESPONSE
#define XHTTP_FEATURE_HTTP_SERVER_RESPONSE
#endif
#ifndef XHTTP_MODULE_HTTP_SERVER_REQUEST
#define XHTTP_MODULE_HTTP_SERVER_REQUEST
#endif
#ifndef XHTTP_MODULE_HTTP_SERVER_REPLY
#define XHTTP_MODULE_HTTP_SERVER_REPLY
#endif
#ifndef XRT_MODULE_HTTP1_BODY
#define XRT_MODULE_HTTP1_BODY
#endif
#ifndef XRT_MODULE_HTTP_TRAILER
#define XRT_MODULE_HTTP_TRAILER
#endif
#endif

/* http_server_exchange 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_SERVER_EXCHANGE)
#ifndef XHTTP_FEATURE_HTTP_SERVER_EXCHANGE
#define XHTTP_FEATURE_HTTP_SERVER_EXCHANGE
#endif
#ifndef XHTTP_MODULE_HTTP_SERVER_REQUEST
#define XHTTP_MODULE_HTTP_SERVER_REQUEST
#endif
#ifndef XRT_MODULE_HTTP_HOST
#define XRT_MODULE_HTTP_HOST
#endif
#ifndef XRT_MODULE_HTTP_TARGET
#define XRT_MODULE_HTTP_TARGET
#endif
#ifndef XRT_MODULE_HTTP_EXPECT
#define XRT_MODULE_HTTP_EXPECT
#endif
#ifndef XRT_MODULE_HTTP_TE
#define XRT_MODULE_HTTP_TE
#endif
#ifndef XRT_MODULE_HTTP_CONNECTION
#define XRT_MODULE_HTTP_CONNECTION
#endif
#ifndef XRT_MODULE_HTTP_TRAILER
#define XRT_MODULE_HTTP_TRAILER
#endif
#endif

/* http_server_form_data 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_SERVER_FORM_DATA)
#ifndef XHTTP_FEATURE_HTTP_SERVER_FORM_DATA
#define XHTTP_FEATURE_HTTP_SERVER_FORM_DATA
#endif
#ifndef XHTTP_MODULE_HTTP_SERVER_CONTENT_TYPE
#define XHTTP_MODULE_HTTP_SERVER_CONTENT_TYPE
#endif
#ifndef XHTTP_MODULE_FORM_DATA_PARSE
#define XHTTP_MODULE_FORM_DATA_PARSE
#endif
#endif

/* http_server_form 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_SERVER_FORM)
#ifndef XHTTP_FEATURE_HTTP_SERVER_FORM
#define XHTTP_FEATURE_HTTP_SERVER_FORM
#endif
#ifndef XHTTP_MODULE_HTTP_SERVER_CONTENT_TYPE
#define XHTTP_MODULE_HTTP_SERVER_CONTENT_TYPE
#endif
#ifndef XHTTP_MODULE_QUERY_PARAMS
#define XHTTP_MODULE_QUERY_PARAMS
#endif
#endif

/* http_server_content_type 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_SERVER_CONTENT_TYPE)
#ifndef XHTTP_FEATURE_HTTP_SERVER_CONTENT_TYPE
#define XHTTP_FEATURE_HTTP_SERVER_CONTENT_TYPE
#endif
#ifndef XHTTP_MODULE_HTTP_SERVER_REQUEST
#define XHTTP_MODULE_HTTP_SERVER_REQUEST
#endif
#ifndef XHTTP_MODULE_MIME
#define XHTTP_MODULE_MIME
#endif
#endif

/* http_server_cookie 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_SERVER_COOKIE)
#ifndef XHTTP_FEATURE_HTTP_SERVER_COOKIE
#define XHTTP_FEATURE_HTTP_SERVER_COOKIE
#endif
#ifndef XHTTP_MODULE_HTTP_SERVER_REQUEST
#define XHTTP_MODULE_HTTP_SERVER_REQUEST
#endif
#ifndef XHTTP_MODULE_COOKIE
#define XHTTP_MODULE_COOKIE
#endif
#endif

/* http_server_query 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_SERVER_QUERY)
#ifndef XHTTP_FEATURE_HTTP_SERVER_QUERY
#define XHTTP_FEATURE_HTTP_SERVER_QUERY
#endif
#ifndef XHTTP_MODULE_HTTP_SERVER_REQUEST
#define XHTTP_MODULE_HTTP_SERVER_REQUEST
#endif
#ifndef XHTTP_MODULE_QUERY_PARAMS
#define XHTTP_MODULE_QUERY_PARAMS
#endif
#endif

/* http_client_set_cookie 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_CLIENT_SET_COOKIE)
#ifndef XHTTP_FEATURE_HTTP_CLIENT_SET_COOKIE
#define XHTTP_FEATURE_HTTP_CLIENT_SET_COOKIE
#endif
#ifndef XHTTP_MODULE_HTTP_CLIENT_RESPONSE
#define XHTTP_MODULE_HTTP_CLIENT_RESPONSE
#endif
#ifndef XHTTP_MODULE_SET_COOKIE
#define XHTTP_MODULE_SET_COOKIE
#endif
#endif

/* http_client_content_type 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_CLIENT_CONTENT_TYPE)
#ifndef XHTTP_FEATURE_HTTP_CLIENT_CONTENT_TYPE
#define XHTTP_FEATURE_HTTP_CLIENT_CONTENT_TYPE
#endif
#ifndef XHTTP_MODULE_HTTP_CLIENT_RESPONSE
#define XHTTP_MODULE_HTTP_CLIENT_RESPONSE
#endif
#ifndef XHTTP_MODULE_MIME
#define XHTTP_MODULE_MIME
#endif
#endif

/* http_client_request_form_data_random 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_CLIENT_REQUEST_FORM_DATA_RANDOM)
#ifndef XHTTP_FEATURE_HTTP_CLIENT_REQUEST_FORM_DATA_RANDOM
#define XHTTP_FEATURE_HTTP_CLIENT_REQUEST_FORM_DATA_RANDOM
#endif
#ifndef XHTTP_MODULE_HTTP_CLIENT_REQUEST_FORM_DATA
#define XHTTP_MODULE_HTTP_CLIENT_REQUEST_FORM_DATA
#endif
#ifndef XHTTP_MODULE_FORM_DATA_RANDOM
#define XHTTP_MODULE_FORM_DATA_RANDOM
#endif
#endif

/* http_client_request_form_data 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_CLIENT_REQUEST_FORM_DATA)
#ifndef XHTTP_FEATURE_HTTP_CLIENT_REQUEST_FORM_DATA
#define XHTTP_FEATURE_HTTP_CLIENT_REQUEST_FORM_DATA
#endif
#ifndef XHTTP_MODULE_HTTP_CLIENT_REQUEST
#define XHTTP_MODULE_HTTP_CLIENT_REQUEST
#endif
#ifndef XHTTP_MODULE_FORM_DATA_MULTIPART
#define XHTTP_MODULE_FORM_DATA_MULTIPART
#endif
#endif

/* http_client_request_form 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_CLIENT_REQUEST_FORM)
#ifndef XHTTP_FEATURE_HTTP_CLIENT_REQUEST_FORM
#define XHTTP_FEATURE_HTTP_CLIENT_REQUEST_FORM
#endif
#ifndef XHTTP_MODULE_HTTP_CLIENT_REQUEST
#define XHTTP_MODULE_HTTP_CLIENT_REQUEST
#endif
#ifndef XHTTP_MODULE_QUERY_PARAMS
#define XHTTP_MODULE_QUERY_PARAMS
#endif
#endif

/* http_client_request_query 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_CLIENT_REQUEST_QUERY)
#ifndef XHTTP_FEATURE_HTTP_CLIENT_REQUEST_QUERY
#define XHTTP_FEATURE_HTTP_CLIENT_REQUEST_QUERY
#endif
#ifndef XHTTP_MODULE_HTTP_CLIENT_REQUEST
#define XHTTP_MODULE_HTTP_CLIENT_REQUEST
#endif
#ifndef XHTTP_MODULE_QUERY_PARAMS
#define XHTTP_MODULE_QUERY_PARAMS
#endif
#endif

/* form_data_random 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_FORM_DATA_RANDOM)
#ifndef XHTTP_FEATURE_FORM_DATA_RANDOM
#define XHTTP_FEATURE_FORM_DATA_RANDOM
#endif
#ifndef XHTTP_MODULE_FORM_DATA_MULTIPART
#define XHTTP_MODULE_FORM_DATA_MULTIPART
#endif
#ifndef XHTTP_MODULE_MULTIPART_RANDOM
#define XHTTP_MODULE_MULTIPART_RANDOM
#endif
#endif

/* form_data_parse 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_FORM_DATA_PARSE)
#ifndef XHTTP_FEATURE_FORM_DATA_PARSE
#define XHTTP_FEATURE_FORM_DATA_PARSE
#endif
#ifndef XHTTP_MODULE_FORM_DATA
#define XHTTP_MODULE_FORM_DATA
#endif
#ifndef XHTTP_MODULE_MULTIPART
#define XHTTP_MODULE_MULTIPART
#endif
#endif

/* form_data_multipart 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_FORM_DATA_MULTIPART)
#ifndef XHTTP_FEATURE_FORM_DATA_MULTIPART
#define XHTTP_FEATURE_FORM_DATA_MULTIPART
#endif
#ifndef XHTTP_MODULE_FORM_DATA
#define XHTTP_MODULE_FORM_DATA
#endif
#ifndef XHTTP_MODULE_MULTIPART_WRITE
#define XHTTP_MODULE_MULTIPART_WRITE
#endif
#ifndef XHTTP_MODULE_HTTP_BODY_COMPOSE
#define XHTTP_MODULE_HTTP_BODY_COMPOSE
#endif
#endif

/* form_data 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_FORM_DATA)
#ifndef XHTTP_FEATURE_FORM_DATA
#define XHTTP_FEATURE_FORM_DATA
#endif
#ifndef XHTTP_MODULE_MIME
#define XHTTP_MODULE_MIME
#endif
#ifndef XHTTP_MODULE_HTTP_BODY
#define XHTTP_MODULE_HTTP_BODY
#endif
#endif

/* http_body_compose 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_BODY_COMPOSE)
#ifndef XHTTP_FEATURE_HTTP_BODY_COMPOSE
#define XHTTP_FEATURE_HTTP_BODY_COMPOSE
#endif
#ifndef XHTTP_MODULE_HTTP_BODY
#define XHTTP_MODULE_HTTP_BODY
#endif
#endif

/* multipart_random 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_MULTIPART_RANDOM)
#ifndef XHTTP_FEATURE_MULTIPART_RANDOM
#define XHTTP_FEATURE_MULTIPART_RANDOM
#endif
#ifndef XHTTP_MODULE_MULTIPART
#define XHTTP_MODULE_MULTIPART
#endif
#ifndef XRT_MODULE_RANDOM_SECURE
#define XRT_MODULE_RANDOM_SECURE
#endif
#endif

/* multipart_stream 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_MULTIPART_STREAM)
#ifndef XHTTP_FEATURE_MULTIPART_STREAM
#define XHTTP_FEATURE_MULTIPART_STREAM
#endif
#ifndef XHTTP_MODULE_MULTIPART
#define XHTTP_MODULE_MULTIPART
#endif
#endif

/* multipart_write 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_MULTIPART_WRITE)
#ifndef XHTTP_FEATURE_MULTIPART_WRITE
#define XHTTP_FEATURE_MULTIPART_WRITE
#endif
#ifndef XHTTP_MODULE_MULTIPART
#define XHTTP_MODULE_MULTIPART
#endif
#endif

/* query_params 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_QUERY_PARAMS)
#ifndef XHTTP_FEATURE_QUERY_PARAMS
#define XHTTP_FEATURE_QUERY_PARAMS
#endif
#ifndef XHTTP_MODULE_QUERY
#define XHTTP_MODULE_QUERY
#endif
#ifndef XHTTP_MODULE_FORM_URLENCODED
#define XHTTP_MODULE_FORM_URLENCODED
#endif
#endif

/* form_urlencoded 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_FORM_URLENCODED)
#ifndef XHTTP_FEATURE_FORM_URLENCODED
#define XHTTP_FEATURE_FORM_URLENCODED
#endif
#ifndef XRT_MODULE_CODEC_PERCENT
#define XRT_MODULE_CODEC_PERCENT
#endif
#ifndef XHTTP_MODULE_QUERY
#define XHTTP_MODULE_QUERY
#endif
#endif

/* query_codec 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_QUERY_CODEC)
#ifndef XHTTP_FEATURE_QUERY_CODEC
#define XHTTP_FEATURE_QUERY_CODEC
#endif
#ifndef XHTTP_MODULE_QUERY
#define XHTTP_MODULE_QUERY
#endif
#ifndef XRT_MODULE_CODEC_PERCENT
#define XRT_MODULE_CODEC_PERCENT
#endif
#endif

/* query 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_QUERY)
#ifndef XHTTP_FEATURE_QUERY
#define XHTTP_FEATURE_QUERY
#endif
#endif

/* http_sse_server 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_SSE_SERVER)
#ifndef XHTTP_FEATURE_HTTP_SSE_SERVER
#define XHTTP_FEATURE_HTTP_SSE_SERVER
#endif
#ifndef XHTTP_MODULE_HTTP_SSE_HTTP
#define XHTTP_MODULE_HTTP_SSE_HTTP
#endif
#ifndef XHTTP_MODULE_HTTP_BODY_STREAM
#define XHTTP_MODULE_HTTP_BODY_STREAM
#endif
#ifndef XHTTP_MODULE_HTTP_SERVER_REPLY
#define XHTTP_MODULE_HTTP_SERVER_REPLY
#endif
#endif

/* http_body_stream 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_BODY_STREAM)
#ifndef XHTTP_FEATURE_HTTP_BODY_STREAM
#define XHTTP_FEATURE_HTTP_BODY_STREAM
#endif
#ifndef XHTTP_MODULE_HTTP_BODY_ASYNC
#define XHTTP_MODULE_HTTP_BODY_ASYNC
#endif
#ifndef XRT_MODULE_MUTEX
#define XRT_MODULE_MUTEX
#endif
#endif

/* http_sse_client 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_SSE_CLIENT)
#ifndef XHTTP_FEATURE_HTTP_SSE_CLIENT
#define XHTTP_FEATURE_HTTP_SSE_CLIENT
#endif
#ifndef XHTTP_MODULE_HTTP_SSE_HTTP
#define XHTTP_MODULE_HTTP_SSE_HTTP
#endif
#ifndef XHTTP_MODULE_HTTP_SSE_PARSER
#define XHTTP_MODULE_HTTP_SSE_PARSER
#endif
#ifndef XHTTP_MODULE_HTTP_CLIENT_REDIRECT
#define XHTTP_MODULE_HTTP_CLIENT_REDIRECT
#endif
#endif

/* http_sse_parser 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_SSE_PARSER)
#ifndef XHTTP_FEATURE_HTTP_SSE_PARSER
#define XHTTP_FEATURE_HTTP_SSE_PARSER
#endif
#ifndef XHTTP_MODULE_HTTP_SSE
#define XHTTP_MODULE_HTTP_SSE
#endif
#ifndef XRT_MODULE_BUFFER
#define XRT_MODULE_BUFFER
#endif
#endif

/* http_sse_http 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_SSE_HTTP)
#ifndef XHTTP_FEATURE_HTTP_SSE_HTTP
#define XHTTP_FEATURE_HTTP_SSE_HTTP
#endif
#ifndef XHTTP_MODULE_HTTP_SSE
#define XHTTP_MODULE_HTTP_SSE
#endif
#ifndef XHTTP_MODULE_HTTP_HEADERS
#define XHTTP_MODULE_HTTP_HEADERS
#endif
#ifndef XHTTP_MODULE_MIME
#define XHTTP_MODULE_MIME
#endif
#endif

/* http_sse 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_SSE)
#ifndef XHTTP_FEATURE_HTTP_SSE
#define XHTTP_FEATURE_HTTP_SSE
#endif
#ifndef XRT_MODULE_HTTP
#define XRT_MODULE_HTTP
#endif
#ifndef XRT_MODULE_UNICODE
#define XRT_MODULE_UNICODE
#endif
#endif

/* http_static_multipart_body 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_STATIC_MULTIPART_BODY)
#ifndef XHTTP_FEATURE_HTTP_STATIC_MULTIPART_BODY
#define XHTTP_FEATURE_HTTP_STATIC_MULTIPART_BODY
#endif
#ifndef XHTTP_MODULE_HTTP_RANGE_MULTIPART
#define XHTTP_MODULE_HTTP_RANGE_MULTIPART
#endif
#ifndef XHTTP_MODULE_HTTP_STATIC_FILE
#define XHTTP_MODULE_HTTP_STATIC_FILE
#endif
#ifndef XHTTP_MODULE_HTTP_BODY_FILE
#define XHTTP_MODULE_HTTP_BODY_FILE
#endif
#endif

/* http_static_file 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_STATIC_FILE)
#ifndef XHTTP_FEATURE_HTTP_STATIC_FILE
#define XHTTP_FEATURE_HTTP_STATIC_FILE
#endif
#ifndef XRT_MODULE_ATOMIC
#define XRT_MODULE_ATOMIC
#endif
#ifndef XRT_MODULE_FILE_ROOT
#define XRT_MODULE_FILE_ROOT
#endif
#ifndef XHTTP_MODULE_HTTP_BODY_FILE
#define XHTTP_MODULE_HTTP_BODY_FILE
#endif
#ifndef XHTTP_MODULE_HTTP_PRECONDITION
#define XHTTP_MODULE_HTTP_PRECONDITION
#endif
#endif

/* http_body_file 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_BODY_FILE)
#ifndef XHTTP_FEATURE_HTTP_BODY_FILE
#define XHTTP_FEATURE_HTTP_BODY_FILE
#endif
#ifndef XHTTP_MODULE_HTTP_BODY_ASYNC
#define XHTTP_MODULE_HTTP_BODY_ASYNC
#endif
#ifndef XRT_MODULE_FILE_ASYNC
#define XRT_MODULE_FILE_ASYNC
#endif
#endif

/* http_body_async 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_BODY_ASYNC)
#ifndef XHTTP_FEATURE_HTTP_BODY_ASYNC
#define XHTTP_FEATURE_HTTP_BODY_ASYNC
#endif
#ifndef XHTTP_MODULE_HTTP_BODY
#define XHTTP_MODULE_HTTP_BODY
#endif
#ifndef XRT_MODULE_FUTURE
#define XRT_MODULE_FUTURE
#endif
#endif

/* http_static_response 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_STATIC_RESPONSE)
#ifndef XHTTP_FEATURE_HTTP_STATIC_RESPONSE
#define XHTTP_FEATURE_HTTP_STATIC_RESPONSE
#endif
#ifndef XHTTP_MODULE_HTTP_STATIC_PLAN
#define XHTTP_MODULE_HTTP_STATIC_PLAN
#endif
#ifndef XHTTP_MODULE_HTTP_RANGE_MULTIPART
#define XHTTP_MODULE_HTTP_RANGE_MULTIPART
#endif
#endif

/* http_static_plan 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_STATIC_PLAN)
#ifndef XHTTP_FEATURE_HTTP_STATIC_PLAN
#define XHTTP_FEATURE_HTTP_STATIC_PLAN
#endif
#ifndef XHTTP_MODULE_HTTP_PRECONDITION
#define XHTTP_MODULE_HTTP_PRECONDITION
#endif
#ifndef XHTTP_MODULE_HTTP_RANGE
#define XHTTP_MODULE_HTTP_RANGE
#endif
#endif

/* http_static_path 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_STATIC_PATH)
#ifndef XHTTP_FEATURE_HTTP_STATIC_PATH
#define XHTTP_FEATURE_HTTP_STATIC_PATH
#endif
#ifndef XRT_MODULE_CODEC_PERCENT
#define XRT_MODULE_CODEC_PERCENT
#endif
#ifndef XRT_MODULE_PATH_SAFE
#define XRT_MODULE_PATH_SAFE
#endif
#endif

/* http_via_write 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_VIA_WRITE)
#ifndef XHTTP_FEATURE_HTTP_VIA_WRITE
#define XHTTP_FEATURE_HTTP_VIA_WRITE
#endif
#ifndef XHTTP_MODULE_HTTP_VIA
#define XHTTP_MODULE_HTTP_VIA
#endif
#endif

/* http_via 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_VIA)
#ifndef XHTTP_FEATURE_HTTP_VIA
#define XHTTP_FEATURE_HTTP_VIA
#endif
#ifndef XRT_MODULE_HTTP
#define XRT_MODULE_HTTP
#endif
#endif

/* http_origin_write 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_ORIGIN_WRITE)
#ifndef XHTTP_FEATURE_HTTP_ORIGIN_WRITE
#define XHTTP_FEATURE_HTTP_ORIGIN_WRITE
#endif
#ifndef XHTTP_MODULE_HTTP_ORIGIN
#define XHTTP_MODULE_HTTP_ORIGIN
#endif
#endif

/* http_forwarded_write 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_FORWARDED_WRITE)
#ifndef XHTTP_FEATURE_HTTP_FORWARDED_WRITE
#define XHTTP_FEATURE_HTTP_FORWARDED_WRITE
#endif
#ifndef XHTTP_MODULE_HTTP_FORWARDED
#define XHTTP_MODULE_HTTP_FORWARDED
#endif
#endif

/* http_forwarded 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_FORWARDED)
#ifndef XHTTP_FEATURE_HTTP_FORWARDED
#define XHTTP_FEATURE_HTTP_FORWARDED
#endif
#ifndef XRT_MODULE_HTTP_PARAM_HOST
#define XRT_MODULE_HTTP_PARAM_HOST
#endif
#endif

/* http_link_write 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_LINK_WRITE)
#ifndef XHTTP_FEATURE_HTTP_LINK_WRITE
#define XHTTP_FEATURE_HTTP_LINK_WRITE
#endif
#ifndef XHTTP_MODULE_HTTP_LINK
#define XHTTP_MODULE_HTTP_LINK
#endif
#endif

/* http_link 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_LINK)
#ifndef XHTTP_FEATURE_HTTP_LINK
#define XHTTP_FEATURE_HTTP_LINK
#endif
#ifndef XHTTP_MODULE_HTTP_EXT_VALUE
#define XHTTP_MODULE_HTTP_EXT_VALUE
#endif
#ifndef XHTTP_MODULE_HTTP_LANGUAGE
#define XHTTP_MODULE_HTTP_LANGUAGE
#endif
#ifndef XHTTP_MODULE_URL_PARAM
#define XHTTP_MODULE_URL_PARAM
#endif
#endif

/* http_client_cache 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_CLIENT_CACHE)
#ifndef XHTTP_FEATURE_HTTP_CLIENT_CACHE
#define XHTTP_FEATURE_HTTP_CLIENT_CACHE
#endif
#ifndef XHTTP_MODULE_HTTP_CLIENT
#define XHTTP_MODULE_HTTP_CLIENT
#endif
#ifndef XHTTP_MODULE_HTTP_CACHE_STORE
#define XHTTP_MODULE_HTTP_CACHE_STORE
#endif
#ifndef XHTTP_MODULE_HTTP_CACHE_RANGE
#define XHTTP_MODULE_HTTP_CACHE_RANGE
#endif
#ifndef XHTTP_MODULE_HTTP_RANGE_MULTIPART
#define XHTTP_MODULE_HTTP_RANGE_MULTIPART
#endif
#ifndef XHTTP_MODULE_MULTIPART
#define XHTTP_MODULE_MULTIPART
#endif
#ifndef XRT_MODULE_CODEC_HEX
#define XRT_MODULE_CODEC_HEX
#endif
#ifndef XRT_MODULE_RANDOM_SECURE
#define XRT_MODULE_RANDOM_SECURE
#endif
#endif

/* multipart 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_MULTIPART)
#ifndef XHTTP_FEATURE_MULTIPART
#define XHTTP_FEATURE_MULTIPART
#endif
#ifndef XHTTP_MODULE_HTTP_CONTENT_DISPOSITION
#define XHTTP_MODULE_HTTP_CONTENT_DISPOSITION
#endif
#endif

/* http_content_disposition 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_CONTENT_DISPOSITION)
#ifndef XHTTP_FEATURE_HTTP_CONTENT_DISPOSITION
#define XHTTP_FEATURE_HTTP_CONTENT_DISPOSITION
#endif
#ifndef XHTTP_MODULE_MIME
#define XHTTP_MODULE_MIME
#endif
#ifndef XHTTP_MODULE_HTTP_EXT_VALUE
#define XHTTP_MODULE_HTTP_EXT_VALUE
#endif
#ifndef XRT_MODULE_UNICODE
#define XRT_MODULE_UNICODE
#endif
#endif

/* http_range_multipart 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_RANGE_MULTIPART)
#ifndef XHTTP_FEATURE_HTTP_RANGE_MULTIPART
#define XHTTP_FEATURE_HTTP_RANGE_MULTIPART
#endif
#ifndef XHTTP_MODULE_HTTP_RANGE
#define XHTTP_MODULE_HTTP_RANGE
#endif
#endif

/* http_client_decompress 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_CLIENT_DECOMPRESS)
#ifndef XHTTP_FEATURE_HTTP_CLIENT_DECOMPRESS
#define XHTTP_FEATURE_HTTP_CLIENT_DECOMPRESS
#endif
#ifndef XHTTP_MODULE_HTTP_CLIENT
#define XHTTP_MODULE_HTTP_CLIENT
#endif
#ifndef XRT_MODULE_HTTP_ENCODING
#define XRT_MODULE_HTTP_ENCODING
#endif
#ifndef XRT_MODULE_INFLATE
#define XRT_MODULE_INFLATE
#endif
#endif

/* http_client_cookies 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_CLIENT_COOKIES)
#ifndef XHTTP_FEATURE_HTTP_CLIENT_COOKIES
#define XHTTP_FEATURE_HTTP_CLIENT_COOKIES
#endif
#ifndef XHTTP_MODULE_HTTP_CLIENT
#define XHTTP_MODULE_HTTP_CLIENT
#endif
#ifndef XHTTP_MODULE_COOKIE_JAR_HEADERS
#define XHTTP_MODULE_COOKIE_JAR_HEADERS
#endif
#endif

/* cookie_jar_headers 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_COOKIE_JAR_HEADERS)
#ifndef XHTTP_FEATURE_COOKIE_JAR_HEADERS
#define XHTTP_FEATURE_COOKIE_JAR_HEADERS
#endif
#ifndef XHTTP_MODULE_COOKIE_JAR
#define XHTTP_MODULE_COOKIE_JAR
#endif
#ifndef XHTTP_MODULE_HTTP_HEADERS
#define XHTTP_MODULE_HTTP_HEADERS
#endif
#endif

/* cookie_jar 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_COOKIE_JAR)
#ifndef XHTTP_FEATURE_COOKIE_JAR
#define XHTTP_FEATURE_COOKIE_JAR
#endif
#ifndef XHTTP_MODULE_SET_COOKIE
#define XHTTP_MODULE_SET_COOKIE
#endif
#ifndef XHTTP_MODULE_URL
#define XHTTP_MODULE_URL
#endif
#ifndef XRT_MODULE_MUTEX
#define XRT_MODULE_MUTEX
#endif
#endif

/* set_cookie 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_SET_COOKIE)
#ifndef XHTTP_FEATURE_SET_COOKIE
#define XHTTP_FEATURE_SET_COOKIE
#endif
#ifndef XHTTP_MODULE_COOKIE
#define XHTTP_MODULE_COOKIE
#endif
#ifndef XRT_MODULE_TIME_TEXT
#define XRT_MODULE_TIME_TEXT
#endif
#endif

/* cookie 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_COOKIE)
#ifndef XHTTP_FEATURE_COOKIE
#define XHTTP_FEATURE_COOKIE
#endif
#ifndef XRT_MODULE_HTTP
#define XRT_MODULE_HTTP
#endif
#endif

/* http_client_pool 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_CLIENT_POOL)
#ifndef XHTTP_FEATURE_HTTP_CLIENT_POOL
#define XHTTP_FEATURE_HTTP_CLIENT_POOL
#endif
#ifndef XHTTP_MODULE_HTTP_CLIENT
#define XHTTP_MODULE_HTTP_CLIENT
#endif
#ifndef XRT_MODULE_MUTEX
#define XRT_MODULE_MUTEX
#endif
#endif

/* http_client_proxy 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_CLIENT_PROXY)
#ifndef XHTTP_FEATURE_HTTP_CLIENT_PROXY
#define XHTTP_FEATURE_HTTP_CLIENT_PROXY
#endif
#ifndef XHTTP_MODULE_HTTP_CLIENT
#define XHTTP_MODULE_HTTP_CLIENT
#endif
#ifndef XRT_MODULE_NET_PROXY_DIAL
#define XRT_MODULE_NET_PROXY_DIAL
#endif
#endif

/* http_client_request_trailers 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_CLIENT_REQUEST_TRAILERS)
#ifndef XHTTP_FEATURE_HTTP_CLIENT_REQUEST_TRAILERS
#define XHTTP_FEATURE_HTTP_CLIENT_REQUEST_TRAILERS
#endif
#ifndef XHTTP_MODULE_HTTP_CLIENT_REQUEST
#define XHTTP_MODULE_HTTP_CLIENT_REQUEST
#endif
#endif

/* http_client_request_te 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_CLIENT_REQUEST_TE)
#ifndef XHTTP_FEATURE_HTTP_CLIENT_REQUEST_TE
#define XHTTP_FEATURE_HTTP_CLIENT_REQUEST_TE
#endif
#ifndef XHTTP_MODULE_HTTP_CLIENT_REQUEST
#define XHTTP_MODULE_HTTP_CLIENT_REQUEST
#endif
#ifndef XRT_MODULE_HTTP_CONNECTION
#define XRT_MODULE_HTTP_CONNECTION
#endif
#ifndef XRT_MODULE_HTTP_TE
#define XRT_MODULE_HTTP_TE
#endif
#endif

/* http_client_easy_future 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_CLIENT_EASY_FUTURE)
#ifndef XHTTP_FEATURE_HTTP_CLIENT_EASY_FUTURE
#define XHTTP_FEATURE_HTTP_CLIENT_EASY_FUTURE
#endif
#ifndef XHTTP_MODULE_HTTP_CLIENT_EASY
#define XHTTP_MODULE_HTTP_CLIENT_EASY
#endif
#ifndef XHTTP_MODULE_HTTP_CLIENT_FUTURE
#define XHTTP_MODULE_HTTP_CLIENT_FUTURE
#endif
#endif

/* http_client_future 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_CLIENT_FUTURE)
#ifndef XHTTP_FEATURE_HTTP_CLIENT_FUTURE
#define XHTTP_FEATURE_HTTP_CLIENT_FUTURE
#endif
#ifndef XHTTP_MODULE_HTTP_CLIENT
#define XHTTP_MODULE_HTTP_CLIENT
#endif
#ifndef XRT_MODULE_FUTURE_BRIDGE
#define XRT_MODULE_FUTURE_BRIDGE
#endif
#ifndef XRT_MODULE_SPIN
#define XRT_MODULE_SPIN
#endif
#endif

/* http_client_easy 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_CLIENT_EASY)
#ifndef XHTTP_FEATURE_HTTP_CLIENT_EASY
#define XHTTP_FEATURE_HTTP_CLIENT_EASY
#endif
#ifndef XHTTP_MODULE_HTTP_CLIENT
#define XHTTP_MODULE_HTTP_CLIENT
#endif
#endif

/* http_client_resume 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_CLIENT_RESUME)
#ifndef XHTTP_FEATURE_HTTP_CLIENT_RESUME
#define XHTTP_FEATURE_HTTP_CLIENT_RESUME
#endif
#ifndef XHTTP_MODULE_HTTP_CLIENT_HTTPS
#define XHTTP_MODULE_HTTP_CLIENT_HTTPS
#endif
#ifndef XRT_MODULE_TLS_CLIENT_RESUME
#define XRT_MODULE_TLS_CLIENT_RESUME
#endif
#ifndef XRT_MODULE_MUTEX
#define XRT_MODULE_MUTEX
#endif
#endif

/* http_client_https 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_CLIENT_HTTPS)
#ifndef XHTTP_FEATURE_HTTP_CLIENT_HTTPS
#define XHTTP_FEATURE_HTTP_CLIENT_HTTPS
#endif
#ifndef XHTTP_MODULE_HTTP_CLIENT
#define XHTTP_MODULE_HTTP_CLIENT
#endif
#ifndef XHTTP_MODULE_HTTP_CLIENT_TLS
#define XHTTP_MODULE_HTTP_CLIENT_TLS
#endif
#ifndef XRT_MODULE_TLS_STREAM_DIAL
#define XRT_MODULE_TLS_STREAM_DIAL
#endif
#ifndef XRT_MODULE_TLS_CLIENT_VERIFY
#define XRT_MODULE_TLS_CLIENT_VERIFY
#endif
#ifndef XRT_MODULE_X509_STORE_SYSTEM
#define XRT_MODULE_X509_STORE_SYSTEM
#endif
#endif

/* http_client_tls 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_CLIENT_TLS)
#ifndef XHTTP_FEATURE_HTTP_CLIENT_TLS
#define XHTTP_FEATURE_HTTP_CLIENT_TLS
#endif
#ifndef XHTTP_MODULE_HTTP_CLIENT_STREAM
#define XHTTP_MODULE_HTTP_CLIENT_STREAM
#endif
#ifndef XRT_MODULE_TLS_STREAM
#define XRT_MODULE_TLS_STREAM
#endif
#endif

/* http_client_retry 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_CLIENT_RETRY)
#ifndef XHTTP_FEATURE_HTTP_CLIENT_RETRY
#define XHTTP_FEATURE_HTTP_CLIENT_RETRY
#endif
#ifndef XHTTP_MODULE_HTTP_CLIENT
#define XHTTP_MODULE_HTTP_CLIENT
#endif
#ifndef XHTTP_MODULE_HTTP_RETRY
#define XHTTP_MODULE_HTTP_RETRY
#endif
#ifndef XRT_MODULE_RANDOM
#define XRT_MODULE_RANDOM
#endif
#endif

/* http_client_redirect 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_CLIENT_REDIRECT)
#ifndef XHTTP_FEATURE_HTTP_CLIENT_REDIRECT
#define XHTTP_FEATURE_HTTP_CLIENT_REDIRECT
#endif
#ifndef XHTTP_MODULE_HTTP_CLIENT
#define XHTTP_MODULE_HTTP_CLIENT
#endif
#ifndef XHTTP_MODULE_URL
#define XHTTP_MODULE_URL
#endif
#endif

/* http_client 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_CLIENT)
#ifndef XHTTP_FEATURE_HTTP_CLIENT
#define XHTTP_FEATURE_HTTP_CLIENT
#endif
#ifndef XHTTP_MODULE_HTTP_CLIENT_STREAM
#define XHTTP_MODULE_HTTP_CLIENT_STREAM
#endif
#ifndef XRT_MODULE_NET_TCP_DIAL
#define XRT_MODULE_NET_TCP_DIAL
#endif
#ifndef XRT_MODULE_CANCEL
#define XRT_MODULE_CANCEL
#endif
#ifndef XRT_MODULE_SPIN
#define XRT_MODULE_SPIN
#endif
#endif

/* http_client_stream 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_CLIENT_STREAM)
#ifndef XHTTP_FEATURE_HTTP_CLIENT_STREAM
#define XHTTP_FEATURE_HTTP_CLIENT_STREAM
#endif
#ifndef XHTTP_MODULE_HTTP_EXCHANGE
#define XHTTP_MODULE_HTTP_EXCHANGE
#endif
#ifndef XRT_MODULE_NET_TCP
#define XRT_MODULE_NET_TCP
#endif
#ifndef XRT_MODULE_SPIN
#define XRT_MODULE_SPIN
#endif
#endif

/* http_exchange 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_EXCHANGE)
#ifndef XHTTP_FEATURE_HTTP_EXCHANGE
#define XHTTP_FEATURE_HTTP_EXCHANGE
#endif
#ifndef XHTTP_MODULE_HTTP_CLIENT_PREPARE
#define XHTTP_MODULE_HTTP_CLIENT_PREPARE
#endif
#ifndef XHTTP_MODULE_HTTP_CLIENT_RESPONSE
#define XHTTP_MODULE_HTTP_CLIENT_RESPONSE
#endif
#ifndef XRT_MODULE_HTTP1_BODY
#define XRT_MODULE_HTTP1_BODY
#endif
#ifndef XRT_MODULE_HTTP_TRAILER
#define XRT_MODULE_HTTP_TRAILER
#endif
#endif

/* http_retry 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_RETRY)
#ifndef XHTTP_FEATURE_HTTP_RETRY
#define XHTTP_FEATURE_HTTP_RETRY
#endif
#ifndef XRT_MODULE_HTTP
#define XRT_MODULE_HTTP
#endif
#ifndef XRT_MODULE_TIME_TEXT
#define XRT_MODULE_TIME_TEXT
#endif
#endif

/* http_server_reply_auth_digest_info 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_SERVER_REPLY_AUTH_DIGEST_INFO)
#ifndef XHTTP_FEATURE_HTTP_SERVER_REPLY_AUTH_DIGEST_INFO
#define XHTTP_FEATURE_HTTP_SERVER_REPLY_AUTH_DIGEST_INFO
#endif
#ifndef XHTTP_MODULE_HTTP_SERVER_REPLY_AUTH
#define XHTTP_MODULE_HTTP_SERVER_REPLY_AUTH
#endif
#ifndef XHTTP_MODULE_HTTP_AUTH_DIGEST_INFO
#define XHTTP_MODULE_HTTP_AUTH_DIGEST_INFO
#endif
#endif

/* http_server_reply_auth_digest 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_SERVER_REPLY_AUTH_DIGEST)
#ifndef XHTTP_FEATURE_HTTP_SERVER_REPLY_AUTH_DIGEST
#define XHTTP_FEATURE_HTTP_SERVER_REPLY_AUTH_DIGEST
#endif
#ifndef XHTTP_MODULE_HTTP_SERVER_REPLY_AUTH
#define XHTTP_MODULE_HTTP_SERVER_REPLY_AUTH
#endif
#ifndef XHTTP_MODULE_HTTP_AUTH_DIGEST_CHALLENGE
#define XHTTP_MODULE_HTTP_AUTH_DIGEST_CHALLENGE
#endif
#endif

/* http_server_reply_auth_bearer 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_SERVER_REPLY_AUTH_BEARER)
#ifndef XHTTP_FEATURE_HTTP_SERVER_REPLY_AUTH_BEARER
#define XHTTP_FEATURE_HTTP_SERVER_REPLY_AUTH_BEARER
#endif
#ifndef XHTTP_MODULE_HTTP_SERVER_REPLY_AUTH
#define XHTTP_MODULE_HTTP_SERVER_REPLY_AUTH
#endif
#ifndef XHTTP_MODULE_HTTP_AUTH_BEARER_CHALLENGE
#define XHTTP_MODULE_HTTP_AUTH_BEARER_CHALLENGE
#endif
#endif

/* http_server_reply_auth_basic 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_SERVER_REPLY_AUTH_BASIC)
#ifndef XHTTP_FEATURE_HTTP_SERVER_REPLY_AUTH_BASIC
#define XHTTP_FEATURE_HTTP_SERVER_REPLY_AUTH_BASIC
#endif
#ifndef XHTTP_MODULE_HTTP_SERVER_REPLY_AUTH
#define XHTTP_MODULE_HTTP_SERVER_REPLY_AUTH
#endif
#ifndef XHTTP_MODULE_HTTP_AUTH_BASIC
#define XHTTP_MODULE_HTTP_AUTH_BASIC
#endif
#endif

/* http_server_reply_auth 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_SERVER_REPLY_AUTH)
#ifndef XHTTP_FEATURE_HTTP_SERVER_REPLY_AUTH
#define XHTTP_FEATURE_HTTP_SERVER_REPLY_AUTH
#endif
#ifndef XHTTP_MODULE_HTTP_SERVER_REPLY
#define XHTTP_MODULE_HTTP_SERVER_REPLY
#endif
#ifndef XHTTP_MODULE_HTTP_AUTH
#define XHTTP_MODULE_HTTP_AUTH
#endif
#endif

/* http_server_reply 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_SERVER_REPLY)
#ifndef XHTTP_FEATURE_HTTP_SERVER_REPLY
#define XHTTP_FEATURE_HTTP_SERVER_REPLY
#endif
#ifndef XHTTP_MODULE_HTTP_HEADERS
#define XHTTP_MODULE_HTTP_HEADERS
#endif
#ifndef XHTTP_MODULE_HTTP_BODY
#define XHTTP_MODULE_HTTP_BODY
#endif
#endif

/* http_server_request_auth_digest 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_SERVER_REQUEST_AUTH_DIGEST)
#ifndef XHTTP_FEATURE_HTTP_SERVER_REQUEST_AUTH_DIGEST
#define XHTTP_FEATURE_HTTP_SERVER_REQUEST_AUTH_DIGEST
#endif
#ifndef XHTTP_MODULE_HTTP_SERVER_REQUEST_AUTH
#define XHTTP_MODULE_HTTP_SERVER_REQUEST_AUTH
#endif
#ifndef XHTTP_MODULE_HTTP_AUTH_DIGEST_CREDENTIALS
#define XHTTP_MODULE_HTTP_AUTH_DIGEST_CREDENTIALS
#endif
#endif

/* http_server_request_auth_bearer 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_SERVER_REQUEST_AUTH_BEARER)
#ifndef XHTTP_FEATURE_HTTP_SERVER_REQUEST_AUTH_BEARER
#define XHTTP_FEATURE_HTTP_SERVER_REQUEST_AUTH_BEARER
#endif
#ifndef XHTTP_MODULE_HTTP_SERVER_REQUEST_AUTH
#define XHTTP_MODULE_HTTP_SERVER_REQUEST_AUTH
#endif
#ifndef XHTTP_MODULE_HTTP_AUTH_BEARER
#define XHTTP_MODULE_HTTP_AUTH_BEARER
#endif
#endif

/* http_server_request_auth_basic 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_SERVER_REQUEST_AUTH_BASIC)
#ifndef XHTTP_FEATURE_HTTP_SERVER_REQUEST_AUTH_BASIC
#define XHTTP_FEATURE_HTTP_SERVER_REQUEST_AUTH_BASIC
#endif
#ifndef XHTTP_MODULE_HTTP_SERVER_REQUEST_AUTH
#define XHTTP_MODULE_HTTP_SERVER_REQUEST_AUTH
#endif
#ifndef XHTTP_MODULE_HTTP_AUTH_BASIC
#define XHTTP_MODULE_HTTP_AUTH_BASIC
#endif
#endif

/* http_server_request_auth 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_SERVER_REQUEST_AUTH)
#ifndef XHTTP_FEATURE_HTTP_SERVER_REQUEST_AUTH
#define XHTTP_FEATURE_HTTP_SERVER_REQUEST_AUTH
#endif
#ifndef XHTTP_MODULE_HTTP_SERVER_REQUEST
#define XHTTP_MODULE_HTTP_SERVER_REQUEST
#endif
#ifndef XHTTP_MODULE_HTTP_AUTH
#define XHTTP_MODULE_HTTP_AUTH
#endif
#endif

/* http_server_request 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_SERVER_REQUEST)
#ifndef XHTTP_FEATURE_HTTP_SERVER_REQUEST
#define XHTTP_FEATURE_HTTP_SERVER_REQUEST
#endif
#ifndef XRT_MODULE_HTTP1_BODY
#define XRT_MODULE_HTTP1_BODY
#endif
#ifndef XRT_MODULE_HTTP_TARGET
#define XRT_MODULE_HTTP_TARGET
#endif
#endif

/* http_client_response_auth_digest_session 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_CLIENT_RESPONSE_AUTH_DIGEST_SESSION)
#ifndef XHTTP_FEATURE_HTTP_CLIENT_RESPONSE_AUTH_DIGEST_SESSION
#define XHTTP_FEATURE_HTTP_CLIENT_RESPONSE_AUTH_DIGEST_SESSION
#endif
#ifndef XHTTP_MODULE_HTTP_CLIENT_RESPONSE_AUTH_DIGEST_INFO
#define XHTTP_MODULE_HTTP_CLIENT_RESPONSE_AUTH_DIGEST_INFO
#endif
#ifndef XHTTP_MODULE_HTTP_AUTH_DIGEST_SESSION
#define XHTTP_MODULE_HTTP_AUTH_DIGEST_SESSION
#endif
#endif

/* http_client_response_auth_digest_info 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_CLIENT_RESPONSE_AUTH_DIGEST_INFO)
#ifndef XHTTP_FEATURE_HTTP_CLIENT_RESPONSE_AUTH_DIGEST_INFO
#define XHTTP_FEATURE_HTTP_CLIENT_RESPONSE_AUTH_DIGEST_INFO
#endif
#ifndef XHTTP_MODULE_HTTP_CLIENT_RESPONSE_AUTH
#define XHTTP_MODULE_HTTP_CLIENT_RESPONSE_AUTH
#endif
#ifndef XHTTP_MODULE_HTTP_AUTH_DIGEST_INFO
#define XHTTP_MODULE_HTTP_AUTH_DIGEST_INFO
#endif
#endif

/* http_client_response_auth_digest_choose 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_CLIENT_RESPONSE_AUTH_DIGEST_CHOOSE)
#ifndef XHTTP_FEATURE_HTTP_CLIENT_RESPONSE_AUTH_DIGEST_CHOOSE
#define XHTTP_FEATURE_HTTP_CLIENT_RESPONSE_AUTH_DIGEST_CHOOSE
#endif
#ifndef XHTTP_MODULE_HTTP_CLIENT_RESPONSE_AUTH_DIGEST
#define XHTTP_MODULE_HTTP_CLIENT_RESPONSE_AUTH_DIGEST
#endif
#ifndef XHTTP_MODULE_HTTP_AUTH_DIGEST_CLIENT
#define XHTTP_MODULE_HTTP_AUTH_DIGEST_CLIENT
#endif
#endif

/* http_client_response_auth_digest 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_CLIENT_RESPONSE_AUTH_DIGEST)
#ifndef XHTTP_FEATURE_HTTP_CLIENT_RESPONSE_AUTH_DIGEST
#define XHTTP_FEATURE_HTTP_CLIENT_RESPONSE_AUTH_DIGEST
#endif
#ifndef XHTTP_MODULE_HTTP_CLIENT_RESPONSE_AUTH
#define XHTTP_MODULE_HTTP_CLIENT_RESPONSE_AUTH
#endif
#ifndef XHTTP_MODULE_HTTP_AUTH_DIGEST_CHALLENGE
#define XHTTP_MODULE_HTTP_AUTH_DIGEST_CHALLENGE
#endif
#endif

/* http_client_response_auth_bearer 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_CLIENT_RESPONSE_AUTH_BEARER)
#ifndef XHTTP_FEATURE_HTTP_CLIENT_RESPONSE_AUTH_BEARER
#define XHTTP_FEATURE_HTTP_CLIENT_RESPONSE_AUTH_BEARER
#endif
#ifndef XHTTP_MODULE_HTTP_CLIENT_RESPONSE_AUTH
#define XHTTP_MODULE_HTTP_CLIENT_RESPONSE_AUTH
#endif
#ifndef XHTTP_MODULE_HTTP_AUTH_BEARER_CHALLENGE
#define XHTTP_MODULE_HTTP_AUTH_BEARER_CHALLENGE
#endif
#endif

/* http_client_response_auth_basic 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_CLIENT_RESPONSE_AUTH_BASIC)
#ifndef XHTTP_FEATURE_HTTP_CLIENT_RESPONSE_AUTH_BASIC
#define XHTTP_FEATURE_HTTP_CLIENT_RESPONSE_AUTH_BASIC
#endif
#ifndef XHTTP_MODULE_HTTP_CLIENT_RESPONSE_AUTH
#define XHTTP_MODULE_HTTP_CLIENT_RESPONSE_AUTH
#endif
#ifndef XHTTP_MODULE_HTTP_AUTH_BASIC
#define XHTTP_MODULE_HTTP_AUTH_BASIC
#endif
#endif

/* http_client_response_auth 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_CLIENT_RESPONSE_AUTH)
#ifndef XHTTP_FEATURE_HTTP_CLIENT_RESPONSE_AUTH
#define XHTTP_FEATURE_HTTP_CLIENT_RESPONSE_AUTH
#endif
#ifndef XHTTP_MODULE_HTTP_CLIENT_RESPONSE
#define XHTTP_MODULE_HTTP_CLIENT_RESPONSE
#endif
#ifndef XHTTP_MODULE_HTTP_AUTH
#define XHTTP_MODULE_HTTP_AUTH
#endif
#endif

/* http_client_response 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_CLIENT_RESPONSE)
#ifndef XHTTP_FEATURE_HTTP_CLIENT_RESPONSE
#define XHTTP_FEATURE_HTTP_CLIENT_RESPONSE
#endif
#ifndef XHTTP_MODULE_HTTP_HEADERS
#define XHTTP_MODULE_HTTP_HEADERS
#endif
#endif

/* http_client_prepare_auth_digest_session 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_CLIENT_PREPARE_AUTH_DIGEST_SESSION)
#ifndef XHTTP_FEATURE_HTTP_CLIENT_PREPARE_AUTH_DIGEST_SESSION
#define XHTTP_FEATURE_HTTP_CLIENT_PREPARE_AUTH_DIGEST_SESSION
#endif
#ifndef XHTTP_MODULE_HTTP_CLIENT_PREPARE
#define XHTTP_MODULE_HTTP_CLIENT_PREPARE
#endif
#ifndef XHTTP_MODULE_HTTP_AUTH_DIGEST_SESSION
#define XHTTP_MODULE_HTTP_AUTH_DIGEST_SESSION
#endif
#endif

/* http_client_prepare 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_CLIENT_PREPARE)
#ifndef XHTTP_FEATURE_HTTP_CLIENT_PREPARE
#define XHTTP_FEATURE_HTTP_CLIENT_PREPARE
#endif
#ifndef XHTTP_MODULE_HTTP_CLIENT_REQUEST
#define XHTTP_MODULE_HTTP_CLIENT_REQUEST
#endif
#ifndef XRT_MODULE_HTTP1_BODY
#define XRT_MODULE_HTTP1_BODY
#endif
#ifndef XRT_MODULE_HTTP_HOST
#define XRT_MODULE_HTTP_HOST
#endif
#ifndef XRT_MODULE_HTTP_TARGET
#define XRT_MODULE_HTTP_TARGET
#endif
#ifndef XRT_MODULE_HTTP_EXPECT
#define XRT_MODULE_HTTP_EXPECT
#endif
#ifndef XRT_MODULE_HTTP_TE
#define XRT_MODULE_HTTP_TE
#endif
#ifndef XRT_MODULE_HTTP_CONNECTION
#define XRT_MODULE_HTTP_CONNECTION
#endif
#ifndef XRT_MODULE_HTTP_TRAILER
#define XRT_MODULE_HTTP_TRAILER
#endif
#endif

/* http_client_request_auth_digest 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_CLIENT_REQUEST_AUTH_DIGEST)
#ifndef XHTTP_FEATURE_HTTP_CLIENT_REQUEST_AUTH_DIGEST
#define XHTTP_FEATURE_HTTP_CLIENT_REQUEST_AUTH_DIGEST
#endif
#ifndef XHTTP_MODULE_HTTP_CLIENT_REQUEST_AUTH
#define XHTTP_MODULE_HTTP_CLIENT_REQUEST_AUTH
#endif
#ifndef XHTTP_MODULE_HTTP_AUTH_DIGEST_CREDENTIALS
#define XHTTP_MODULE_HTTP_AUTH_DIGEST_CREDENTIALS
#endif
#endif

/* http_client_request_auth_bearer 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_CLIENT_REQUEST_AUTH_BEARER)
#ifndef XHTTP_FEATURE_HTTP_CLIENT_REQUEST_AUTH_BEARER
#define XHTTP_FEATURE_HTTP_CLIENT_REQUEST_AUTH_BEARER
#endif
#ifndef XHTTP_MODULE_HTTP_CLIENT_REQUEST_AUTH
#define XHTTP_MODULE_HTTP_CLIENT_REQUEST_AUTH
#endif
#ifndef XHTTP_MODULE_HTTP_AUTH_BEARER
#define XHTTP_MODULE_HTTP_AUTH_BEARER
#endif
#endif

/* http_client_request_auth_basic 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_CLIENT_REQUEST_AUTH_BASIC)
#ifndef XHTTP_FEATURE_HTTP_CLIENT_REQUEST_AUTH_BASIC
#define XHTTP_FEATURE_HTTP_CLIENT_REQUEST_AUTH_BASIC
#endif
#ifndef XHTTP_MODULE_HTTP_CLIENT_REQUEST_AUTH
#define XHTTP_MODULE_HTTP_CLIENT_REQUEST_AUTH
#endif
#ifndef XHTTP_MODULE_HTTP_AUTH_BASIC
#define XHTTP_MODULE_HTTP_AUTH_BASIC
#endif
#endif

/* http_client_request_auth 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_CLIENT_REQUEST_AUTH)
#ifndef XHTTP_FEATURE_HTTP_CLIENT_REQUEST_AUTH
#define XHTTP_FEATURE_HTTP_CLIENT_REQUEST_AUTH
#endif
#ifndef XHTTP_MODULE_HTTP_CLIENT_REQUEST
#define XHTTP_MODULE_HTTP_CLIENT_REQUEST
#endif
#ifndef XHTTP_MODULE_HTTP_AUTH
#define XHTTP_MODULE_HTTP_AUTH
#endif
#endif

/* http_client_request 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_CLIENT_REQUEST)
#ifndef XHTTP_FEATURE_HTTP_CLIENT_REQUEST
#define XHTTP_FEATURE_HTTP_CLIENT_REQUEST
#endif
#ifndef XHTTP_MODULE_URL
#define XHTTP_MODULE_URL
#endif
#ifndef XHTTP_MODULE_HTTP_HEADERS
#define XHTTP_MODULE_HTTP_HEADERS
#endif
#ifndef XHTTP_MODULE_HTTP_BODY
#define XHTTP_MODULE_HTTP_BODY
#endif
#endif

/* http_body 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_BODY)
#ifndef XHTTP_FEATURE_HTTP_BODY
#define XHTTP_FEATURE_HTTP_BODY
#endif
#ifndef XRT_MODULE_ATOMIC
#define XRT_MODULE_ATOMIC
#endif
#endif

/* http_headers 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_HEADERS)
#ifndef XHTTP_FEATURE_HTTP_HEADERS
#define XHTTP_FEATURE_HTTP_HEADERS
#endif
#ifndef XRT_MODULE_HTTP
#define XRT_MODULE_HTTP
#endif
#endif

/* http_auth_digest_replay 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_AUTH_DIGEST_REPLAY)
#ifndef XHTTP_FEATURE_HTTP_AUTH_DIGEST_REPLAY
#define XHTTP_FEATURE_HTTP_AUTH_DIGEST_REPLAY
#endif
#ifndef XHTTP_MODULE_HTTP_AUTH_DIGEST
#define XHTTP_MODULE_HTTP_AUTH_DIGEST
#endif
#ifndef XRT_MODULE_CRYPTO_SHA256
#define XRT_MODULE_CRYPTO_SHA256
#endif
#ifndef XRT_MODULE_MUTEX
#define XRT_MODULE_MUTEX
#endif
#endif

/* http_auth_digest_session 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_AUTH_DIGEST_SESSION)
#ifndef XHTTP_FEATURE_HTTP_AUTH_DIGEST_SESSION
#define XHTTP_FEATURE_HTTP_AUTH_DIGEST_SESSION
#endif
#ifndef XHTTP_MODULE_HTTP_AUTH_DIGEST_CLIENT
#define XHTTP_MODULE_HTTP_AUTH_DIGEST_CLIENT
#endif
#ifndef XRT_MODULE_MUTEX
#define XRT_MODULE_MUTEX
#endif
#endif

/* http_auth_digest_client 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_AUTH_DIGEST_CLIENT)
#ifndef XHTTP_FEATURE_HTTP_AUTH_DIGEST_CLIENT
#define XHTTP_FEATURE_HTTP_AUTH_DIGEST_CLIENT
#endif
#ifndef XHTTP_MODULE_HTTP_AUTH_DIGEST_CHALLENGE
#define XHTTP_MODULE_HTTP_AUTH_DIGEST_CHALLENGE
#endif
#ifndef XHTTP_MODULE_HTTP_AUTH_DIGEST_CREDENTIALS
#define XHTTP_MODULE_HTTP_AUTH_DIGEST_CREDENTIALS
#endif
#ifndef XHTTP_MODULE_HTTP_AUTH_DIGEST_INFO
#define XHTTP_MODULE_HTTP_AUTH_DIGEST_INFO
#endif
#ifndef XHTTP_MODULE_HTTP_AUTH_DIGEST_SHA2
#define XHTTP_MODULE_HTTP_AUTH_DIGEST_SHA2
#endif
#endif

/* http_auth_digest_verify 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_AUTH_DIGEST_VERIFY)
#ifndef XHTTP_FEATURE_HTTP_AUTH_DIGEST_VERIFY
#define XHTTP_FEATURE_HTTP_AUTH_DIGEST_VERIFY
#endif
#ifndef XHTTP_MODULE_HTTP_AUTH_DIGEST_CHALLENGE
#define XHTTP_MODULE_HTTP_AUTH_DIGEST_CHALLENGE
#endif
#ifndef XHTTP_MODULE_HTTP_AUTH_DIGEST_CREDENTIALS
#define XHTTP_MODULE_HTTP_AUTH_DIGEST_CREDENTIALS
#endif
#ifndef XHTTP_MODULE_HTTP_AUTH_DIGEST_SHA2
#define XHTTP_MODULE_HTTP_AUTH_DIGEST_SHA2
#endif
#ifndef XHTTP_MODULE_HTTP_AUTH_DIGEST_NONCE
#define XHTTP_MODULE_HTTP_AUTH_DIGEST_NONCE
#endif
#endif

/* http_auth_digest_nonce_random 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_AUTH_DIGEST_NONCE_RANDOM)
#ifndef XHTTP_FEATURE_HTTP_AUTH_DIGEST_NONCE_RANDOM
#define XHTTP_FEATURE_HTTP_AUTH_DIGEST_NONCE_RANDOM
#endif
#ifndef XHTTP_MODULE_HTTP_AUTH_DIGEST_NONCE
#define XHTTP_MODULE_HTTP_AUTH_DIGEST_NONCE
#endif
#ifndef XRT_MODULE_RANDOM_SECURE
#define XRT_MODULE_RANDOM_SECURE
#endif
#endif

/* http_auth_digest_nonce 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_AUTH_DIGEST_NONCE)
#ifndef XHTTP_FEATURE_HTTP_AUTH_DIGEST_NONCE
#define XHTTP_FEATURE_HTTP_AUTH_DIGEST_NONCE
#endif
#ifndef XHTTP_MODULE_HTTP_AUTH_DIGEST
#define XHTTP_MODULE_HTTP_AUTH_DIGEST
#endif
#ifndef XRT_MODULE_CODEC_BASE64
#define XRT_MODULE_CODEC_BASE64
#endif
#ifndef XRT_MODULE_CRYPTO_HMAC_SHA256
#define XRT_MODULE_CRYPTO_HMAC_SHA256
#endif
#endif

/* http_auth_digest_md5 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_AUTH_DIGEST_MD5)
#ifndef XHTTP_FEATURE_HTTP_AUTH_DIGEST_MD5
#define XHTTP_FEATURE_HTTP_AUTH_DIGEST_MD5
#endif
#ifndef XHTTP_MODULE_HTTP_AUTH_DIGEST_SHA2
#define XHTTP_MODULE_HTTP_AUTH_DIGEST_SHA2
#endif
#ifndef XRT_MODULE_CRYPTO_MD5
#define XRT_MODULE_CRYPTO_MD5
#endif
#endif

/* http_auth_digest_sha2 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_AUTH_DIGEST_SHA2)
#ifndef XHTTP_FEATURE_HTTP_AUTH_DIGEST_SHA2
#define XHTTP_FEATURE_HTTP_AUTH_DIGEST_SHA2
#endif
#ifndef XHTTP_MODULE_HTTP_AUTH_DIGEST
#define XHTTP_MODULE_HTTP_AUTH_DIGEST
#endif
#ifndef XRT_MODULE_CRYPTO_SHA256
#define XRT_MODULE_CRYPTO_SHA256
#endif
#ifndef XRT_MODULE_CRYPTO_SHA512_256
#define XRT_MODULE_CRYPTO_SHA512_256
#endif
#endif

/* http_auth_digest_info 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_AUTH_DIGEST_INFO)
#ifndef XHTTP_FEATURE_HTTP_AUTH_DIGEST_INFO
#define XHTTP_FEATURE_HTTP_AUTH_DIGEST_INFO
#endif
#ifndef XHTTP_MODULE_HTTP_AUTH_DIGEST
#define XHTTP_MODULE_HTTP_AUTH_DIGEST
#endif
#endif

/* http_auth_digest_credentials 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_AUTH_DIGEST_CREDENTIALS)
#ifndef XHTTP_FEATURE_HTTP_AUTH_DIGEST_CREDENTIALS
#define XHTTP_FEATURE_HTTP_AUTH_DIGEST_CREDENTIALS
#endif
#ifndef XHTTP_MODULE_HTTP_AUTH_DIGEST
#define XHTTP_MODULE_HTTP_AUTH_DIGEST
#endif
#ifndef XHTTP_MODULE_HTTP_EXT_VALUE
#define XHTTP_MODULE_HTTP_EXT_VALUE
#endif
#endif

/* http_ext_value 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_EXT_VALUE)
#ifndef XHTTP_FEATURE_HTTP_EXT_VALUE
#define XHTTP_FEATURE_HTTP_EXT_VALUE
#endif
#ifndef XHTTP_MODULE_HTTP_LANGUAGE_CORE
#define XHTTP_MODULE_HTTP_LANGUAGE_CORE
#endif
#ifndef XRT_MODULE_CODEC_PERCENT
#define XRT_MODULE_CODEC_PERCENT
#endif
#endif

/* http_auth_digest_challenge 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_AUTH_DIGEST_CHALLENGE)
#ifndef XHTTP_FEATURE_HTTP_AUTH_DIGEST_CHALLENGE
#define XHTTP_FEATURE_HTTP_AUTH_DIGEST_CHALLENGE
#endif
#ifndef XHTTP_MODULE_HTTP_AUTH_DIGEST
#define XHTTP_MODULE_HTTP_AUTH_DIGEST
#endif
#endif

/* http_auth_digest 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_AUTH_DIGEST)
#ifndef XHTTP_FEATURE_HTTP_AUTH_DIGEST
#define XHTTP_FEATURE_HTTP_AUTH_DIGEST
#endif
#ifndef XHTTP_MODULE_HTTP_AUTH
#define XHTTP_MODULE_HTTP_AUTH
#endif
#endif

/* http_auth_bearer_challenge 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_AUTH_BEARER_CHALLENGE)
#ifndef XHTTP_FEATURE_HTTP_AUTH_BEARER_CHALLENGE
#define XHTTP_FEATURE_HTTP_AUTH_BEARER_CHALLENGE
#endif
#ifndef XHTTP_MODULE_HTTP_AUTH_BEARER
#define XHTTP_MODULE_HTTP_AUTH_BEARER
#endif
#ifndef XHTTP_MODULE_URL_PARAM
#define XHTTP_MODULE_URL_PARAM
#endif
#endif

/* url_param 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_URL_PARAM)
#ifndef XHTTP_FEATURE_URL_PARAM
#define XHTTP_FEATURE_URL_PARAM
#endif
#ifndef XHTTP_MODULE_URL
#define XHTTP_MODULE_URL
#endif
#ifndef XRT_MODULE_HTTP_PARAM_HOST
#define XRT_MODULE_HTTP_PARAM_HOST
#endif
#endif

/* http_auth_bearer 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_AUTH_BEARER)
#ifndef XHTTP_FEATURE_HTTP_AUTH_BEARER
#define XHTTP_FEATURE_HTTP_AUTH_BEARER
#endif
#ifndef XHTTP_MODULE_HTTP_AUTH
#define XHTTP_MODULE_HTTP_AUTH
#endif
#endif

/* http_auth_basic 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_AUTH_BASIC)
#ifndef XHTTP_FEATURE_HTTP_AUTH_BASIC
#define XHTTP_FEATURE_HTTP_AUTH_BASIC
#endif
#ifndef XHTTP_MODULE_HTTP_AUTH
#define XHTTP_MODULE_HTTP_AUTH
#endif
#ifndef XRT_MODULE_CODEC_BASE64
#define XRT_MODULE_CODEC_BASE64
#endif
#endif

/* http_auth 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_AUTH)
#ifndef XHTTP_FEATURE_HTTP_AUTH
#define XHTTP_FEATURE_HTTP_AUTH
#endif
#ifndef XRT_MODULE_HTTP_PARAM
#define XRT_MODULE_HTTP_PARAM
#endif
#endif

/* http_proxy_status_write 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_PROXY_STATUS_WRITE)
#ifndef XHTTP_FEATURE_HTTP_PROXY_STATUS_WRITE
#define XHTTP_FEATURE_HTTP_PROXY_STATUS_WRITE
#endif
#ifndef XHTTP_MODULE_HTTP_PROXY_STATUS
#define XHTTP_MODULE_HTTP_PROXY_STATUS
#endif
#ifndef XHTTP_MODULE_HTTP_STRUCTURED_WRITE
#define XHTTP_MODULE_HTTP_STRUCTURED_WRITE
#endif
#endif

/* http_proxy_alias_write 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_PROXY_ALIAS_WRITE)
#ifndef XHTTP_FEATURE_HTTP_PROXY_ALIAS_WRITE
#define XHTTP_FEATURE_HTTP_PROXY_ALIAS_WRITE
#endif
#ifndef XHTTP_MODULE_HTTP_PROXY_ALIAS
#define XHTTP_MODULE_HTTP_PROXY_ALIAS
#endif
#endif

/* http_proxy_alias 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_PROXY_ALIAS)
#ifndef XHTTP_FEATURE_HTTP_PROXY_ALIAS
#define XHTTP_FEATURE_HTTP_PROXY_ALIAS
#endif
#ifndef XHTTP_MODULE_HTTP_PROXY_STATUS
#define XHTTP_MODULE_HTTP_PROXY_STATUS
#endif
#ifndef XRT_MODULE_CODEC_PERCENT
#define XRT_MODULE_CODEC_PERCENT
#endif
#endif

/* http_proxy_status 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_PROXY_STATUS)
#ifndef XHTTP_FEATURE_HTTP_PROXY_STATUS
#define XHTTP_FEATURE_HTTP_PROXY_STATUS
#endif
#ifndef XHTTP_MODULE_HTTP_STRUCTURED
#define XHTTP_MODULE_HTTP_STRUCTURED
#endif
#endif

/* http_cache_status_write 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_CACHE_STATUS_WRITE)
#ifndef XHTTP_FEATURE_HTTP_CACHE_STATUS_WRITE
#define XHTTP_FEATURE_HTTP_CACHE_STATUS_WRITE
#endif
#ifndef XHTTP_MODULE_HTTP_CACHE_STATUS
#define XHTTP_MODULE_HTTP_CACHE_STATUS
#endif
#ifndef XHTTP_MODULE_HTTP_STRUCTURED_WRITE
#define XHTTP_MODULE_HTTP_STRUCTURED_WRITE
#endif
#endif

/* http_cache_status 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_CACHE_STATUS)
#ifndef XHTTP_FEATURE_HTTP_CACHE_STATUS
#define XHTTP_FEATURE_HTTP_CACHE_STATUS
#endif
#ifndef XHTTP_MODULE_HTTP_STRUCTURED
#define XHTTP_MODULE_HTTP_STRUCTURED
#endif
#endif

/* http_cache_store 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_CACHE_STORE)
#ifndef XHTTP_FEATURE_HTTP_CACHE_STORE
#define XHTTP_FEATURE_HTTP_CACHE_STORE
#endif
#ifndef XHTTP_MODULE_HTTP_CACHE_VALIDATE
#define XHTTP_MODULE_HTTP_CACHE_VALIDATE
#endif
#ifndef XHTTP_MODULE_HTTP_VARY
#define XHTTP_MODULE_HTTP_VARY
#endif
#ifndef XRT_MODULE_MAP
#define XRT_MODULE_MAP
#endif
#ifndef XRT_MODULE_MUTEX
#define XRT_MODULE_MUTEX
#endif
#endif

/* http_vary 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_VARY)
#ifndef XHTTP_FEATURE_HTTP_VARY
#define XHTTP_FEATURE_HTTP_VARY
#endif
#ifndef XRT_MODULE_HTTP
#define XRT_MODULE_HTTP
#endif
#endif

/* http_cache_range 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_CACHE_RANGE)
#ifndef XHTTP_FEATURE_HTTP_CACHE_RANGE
#define XHTTP_FEATURE_HTTP_CACHE_RANGE
#endif
#ifndef XHTTP_MODULE_HTTP_CACHE_VALIDATE
#define XHTTP_MODULE_HTTP_CACHE_VALIDATE
#endif
#ifndef XHTTP_MODULE_HTTP_RANGE
#define XHTTP_MODULE_HTTP_RANGE
#endif
#endif

/* http_range 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_RANGE)
#ifndef XHTTP_FEATURE_HTTP_RANGE
#define XHTTP_FEATURE_HTTP_RANGE
#endif
#ifndef XRT_MODULE_HTTP
#define XRT_MODULE_HTTP
#endif
#endif

/* http_cache_validate 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_CACHE_VALIDATE)
#ifndef XHTTP_FEATURE_HTTP_CACHE_VALIDATE
#define XHTTP_FEATURE_HTTP_CACHE_VALIDATE
#endif
#ifndef XHTTP_MODULE_HTTP_CACHE_POLICY
#define XHTTP_MODULE_HTTP_CACHE_POLICY
#endif
#ifndef XHTTP_MODULE_HTTP_FORWARD
#define XHTTP_MODULE_HTTP_FORWARD
#endif
#ifndef XHTTP_MODULE_HTTP_ORIGIN
#define XHTTP_MODULE_HTTP_ORIGIN
#endif
#ifndef XHTTP_MODULE_HTTP_PRECONDITION
#define XHTTP_MODULE_HTTP_PRECONDITION
#endif
#ifndef XHTTP_MODULE_URL
#define XHTTP_MODULE_URL
#endif
#endif

/* http_precondition 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_PRECONDITION)
#ifndef XHTTP_FEATURE_HTTP_PRECONDITION
#define XHTTP_FEATURE_HTTP_PRECONDITION
#endif
#ifndef XHTTP_MODULE_HTTP_ETAG
#define XHTTP_MODULE_HTTP_ETAG
#endif
#ifndef XRT_MODULE_TIME_TEXT
#define XRT_MODULE_TIME_TEXT
#endif
#endif

/* http_etag 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_ETAG)
#ifndef XHTTP_FEATURE_HTTP_ETAG
#define XHTTP_FEATURE_HTTP_ETAG
#endif
#ifndef XRT_MODULE_HTTP
#define XRT_MODULE_HTTP
#endif
#endif

/* http_origin 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_ORIGIN)
#ifndef XHTTP_FEATURE_HTTP_ORIGIN
#define XHTTP_FEATURE_HTTP_ORIGIN
#endif
#ifndef XHTTP_MODULE_URL
#define XHTTP_MODULE_URL
#endif
#endif

/* url 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_URL)
#ifndef XHTTP_FEATURE_URL
#define XHTTP_FEATURE_URL
#endif
#ifndef XRT_MODULE_HTTP_HOST
#define XRT_MODULE_HTTP_HOST
#endif
#endif

/* http_forward 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_FORWARD)
#ifndef XHTTP_FEATURE_HTTP_FORWARD
#define XHTTP_FEATURE_HTTP_FORWARD
#endif
#ifndef XRT_MODULE_HTTP_CONNECTION
#define XRT_MODULE_HTTP_CONNECTION
#endif
#endif

/* http_cache_policy 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_CACHE_POLICY)
#ifndef XHTTP_FEATURE_HTTP_CACHE_POLICY
#define XHTTP_FEATURE_HTTP_CACHE_POLICY
#endif
#ifndef XHTTP_MODULE_HTTP_CACHE_TIME
#define XHTTP_MODULE_HTTP_CACHE_TIME
#endif
#endif

/* http_cache_time 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_CACHE_TIME)
#ifndef XHTTP_FEATURE_HTTP_CACHE_TIME
#define XHTTP_FEATURE_HTTP_CACHE_TIME
#endif
#ifndef XHTTP_MODULE_HTTP_CACHE
#define XHTTP_MODULE_HTTP_CACHE
#endif
#ifndef XRT_MODULE_TIME_TEXT
#define XRT_MODULE_TIME_TEXT
#endif
#endif

/* http_cache 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_CACHE)
#ifndef XHTTP_FEATURE_HTTP_CACHE
#define XHTTP_FEATURE_HTTP_CACHE
#endif
#ifndef XRT_MODULE_HTTP_PARAM
#define XRT_MODULE_HTTP_PARAM
#endif
#endif

/* http_priority_write 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_PRIORITY_WRITE)
#ifndef XHTTP_FEATURE_HTTP_PRIORITY_WRITE
#define XHTTP_FEATURE_HTTP_PRIORITY_WRITE
#endif
#ifndef XHTTP_MODULE_HTTP_PRIORITY
#define XHTTP_MODULE_HTTP_PRIORITY
#endif
#ifndef XHTTP_MODULE_HTTP_STRUCTURED_WRITE
#define XHTTP_MODULE_HTTP_STRUCTURED_WRITE
#endif
#endif

/* http_priority 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_PRIORITY)
#ifndef XHTTP_FEATURE_HTTP_PRIORITY
#define XHTTP_FEATURE_HTTP_PRIORITY
#endif
#ifndef XHTTP_MODULE_HTTP_STRUCTURED
#define XHTTP_MODULE_HTTP_STRUCTURED
#endif
#endif

/* http_digest_sha2 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_DIGEST_SHA2)
#ifndef XHTTP_FEATURE_HTTP_DIGEST_SHA2
#define XHTTP_FEATURE_HTTP_DIGEST_SHA2
#endif
#ifndef XHTTP_MODULE_HTTP_DIGEST_WRITE
#define XHTTP_MODULE_HTTP_DIGEST_WRITE
#endif
#ifndef XRT_MODULE_CRYPTO_SHA256
#define XRT_MODULE_CRYPTO_SHA256
#endif
#ifndef XRT_MODULE_CRYPTO_SHA512
#define XRT_MODULE_CRYPTO_SHA512
#endif
#endif

/* http_digest_write 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_DIGEST_WRITE)
#ifndef XHTTP_FEATURE_HTTP_DIGEST_WRITE
#define XHTTP_FEATURE_HTTP_DIGEST_WRITE
#endif
#ifndef XHTTP_MODULE_HTTP_DIGEST
#define XHTTP_MODULE_HTTP_DIGEST
#endif
#ifndef XHTTP_MODULE_HTTP_STRUCTURED_WRITE
#define XHTTP_MODULE_HTTP_STRUCTURED_WRITE
#endif
#endif

/* http_digest 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_DIGEST)
#ifndef XHTTP_FEATURE_HTTP_DIGEST
#define XHTTP_FEATURE_HTTP_DIGEST
#endif
#ifndef XHTTP_MODULE_HTTP_STRUCTURED
#define XHTTP_MODULE_HTTP_STRUCTURED
#endif
#endif

/* http_structured_write 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_STRUCTURED_WRITE)
#ifndef XHTTP_FEATURE_HTTP_STRUCTURED_WRITE
#define XHTTP_FEATURE_HTTP_STRUCTURED_WRITE
#endif
#ifndef XHTTP_MODULE_HTTP_STRUCTURED
#define XHTTP_MODULE_HTTP_STRUCTURED
#endif
#endif

/* http_structured 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_STRUCTURED)
#ifndef XHTTP_FEATURE_HTTP_STRUCTURED
#define XHTTP_FEATURE_HTTP_STRUCTURED
#endif
#ifndef XRT_MODULE_HTTP
#define XRT_MODULE_HTTP
#endif
#ifndef XRT_MODULE_CODEC_BASE64
#define XRT_MODULE_CODEC_BASE64
#endif
#ifndef XRT_MODULE_UNICODE
#define XRT_MODULE_UNICODE
#endif
#endif

/* http_language 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_LANGUAGE)
#ifndef XHTTP_FEATURE_HTTP_LANGUAGE
#define XHTTP_FEATURE_HTTP_LANGUAGE
#endif
#ifndef XHTTP_MODULE_HTTP_LANGUAGE_CORE
#define XHTTP_MODULE_HTTP_LANGUAGE_CORE
#endif
#endif

/* http_language_core 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_LANGUAGE_CORE)
#ifndef XHTTP_FEATURE_HTTP_LANGUAGE_CORE
#define XHTTP_FEATURE_HTTP_LANGUAGE_CORE
#endif
#ifndef XRT_MODULE_HTTP
#define XRT_MODULE_HTTP
#endif
#endif

/* http_accept 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_HTTP_ACCEPT)
#ifndef XHTTP_FEATURE_HTTP_ACCEPT
#define XHTTP_FEATURE_HTTP_ACCEPT
#endif
#ifndef XHTTP_MODULE_MIME
#define XHTTP_MODULE_MIME
#endif
#endif

/* mime 及其直接依赖。 */
#if defined(XHTTP_MODULE_ALL) || defined(XHTTP_MODULE_MIME)
#ifndef XHTTP_FEATURE_MIME
#define XHTTP_FEATURE_MIME
#endif
#ifndef XRT_MODULE_HTTP_PARAM
#define XRT_MODULE_HTTP_PARAM
#endif
#endif

#endif /* XHTTP_FEATURES_H */
