/* 此文件由 tools/generate_extension_features.py 生成，请勿直接修改。 */
#ifndef XSSH_FEATURES_H
#define XSSH_FEATURES_H

/* xssh 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_XSSH)
#ifndef XSSH_FEATURE_SSH
#define XSSH_FEATURE_SSH
#endif
#ifndef XSSH_MODULE_SSH_PACKET_CODEC_RANDOM
#define XSSH_MODULE_SSH_PACKET_CODEC_RANDOM
#endif
#ifndef XSSH_MODULE_SSH_KEXINIT_RANDOM
#define XSSH_MODULE_SSH_KEXINIT_RANDOM
#endif
#ifndef XSSH_MODULE_SSH_KEX_ECDH
#define XSSH_MODULE_SSH_KEX_ECDH
#endif
#ifndef XSSH_MODULE_SSH_KEX_SHA256
#define XSSH_MODULE_SSH_KEX_SHA256
#endif
#ifndef XSSH_MODULE_SSH_KEX_CURVE25519_RANDOM
#define XSSH_MODULE_SSH_KEX_CURVE25519_RANDOM
#endif
#ifndef XSSH_MODULE_SSH_HOSTKEY_ED25519
#define XSSH_MODULE_SSH_HOSTKEY_ED25519
#endif
#ifndef XSSH_MODULE_SSH_KEY_TEXT
#define XSSH_MODULE_SSH_KEY_TEXT
#endif
#ifndef XSSH_MODULE_SSH_KNOWN_HOST
#define XSSH_MODULE_SSH_KNOWN_HOST
#endif
#ifndef XSSH_MODULE_SSH_KNOWN_HOST_HASH
#define XSSH_MODULE_SSH_KNOWN_HOST_HASH
#endif
#ifndef XSSH_MODULE_SSH_KNOWN_HOST_DB
#define XSSH_MODULE_SSH_KNOWN_HOST_DB
#endif
#ifndef XSSH_MODULE_SSH_FINGERPRINT
#define XSSH_MODULE_SSH_FINGERPRINT
#endif
#ifndef XSSH_MODULE_SSH_PRIVATE_KEY_PEM
#define XSSH_MODULE_SSH_PRIVATE_KEY_PEM
#endif
#ifndef XSSH_MODULE_SSH_PRIVATE_KEY_ED25519
#define XSSH_MODULE_SSH_PRIVATE_KEY_ED25519
#endif
#ifndef XSSH_MODULE_SSH_TRANSPORT_MESSAGE
#define XSSH_MODULE_SSH_TRANSPORT_MESSAGE
#endif
#ifndef XSSH_MODULE_SSH_TRANSPORT_REKEY
#define XSSH_MODULE_SSH_TRANSPORT_REKEY
#endif
#ifndef XSSH_MODULE_SSH_TRANSPORT_STATE
#define XSSH_MODULE_SSH_TRANSPORT_STATE
#endif
#ifndef XSSH_MODULE_SSH_TRANSPORT_CORE
#define XSSH_MODULE_SSH_TRANSPORT_CORE
#endif
#ifndef XSSH_MODULE_SSH_KEX_SESSION
#define XSSH_MODULE_SSH_KEX_SESSION
#endif
#ifndef XSSH_MODULE_SSH_KEX_SESSION_RANDOM
#define XSSH_MODULE_SSH_KEX_SESSION_RANDOM
#endif
#ifndef XSSH_MODULE_SSH_KEX_EXCHANGE
#define XSSH_MODULE_SSH_KEX_EXCHANGE
#endif
#ifndef XSSH_MODULE_SSH_KEX_EXCHANGE_RANDOM
#define XSSH_MODULE_SSH_KEX_EXCHANGE_RANDOM
#endif
#ifndef XSSH_MODULE_SSH_TRANSPORT_TCP
#define XSSH_MODULE_SSH_TRANSPORT_TCP
#endif
#ifndef XSSH_MODULE_SSH_TRANSPORT_TCP_RANDOM
#define XSSH_MODULE_SSH_TRANSPORT_TCP_RANDOM
#endif
#ifndef XSSH_MODULE_SSH_AUTH_PASSWORD
#define XSSH_MODULE_SSH_AUTH_PASSWORD
#endif
#ifndef XSSH_MODULE_SSH_AUTH_PUBLICKEY
#define XSSH_MODULE_SSH_AUTH_PUBLICKEY
#endif
#ifndef XSSH_MODULE_SSH_AUTH_KEYBOARD
#define XSSH_MODULE_SSH_AUTH_KEYBOARD
#endif
#ifndef XSSH_MODULE_SSH_AUTH_HOSTBASED
#define XSSH_MODULE_SSH_AUTH_HOSTBASED
#endif
#ifndef XSSH_MODULE_SSH_AUTH_GUARD
#define XSSH_MODULE_SSH_AUTH_GUARD
#endif
#ifndef XSSH_MODULE_SSH_AUTH_SESSION
#define XSSH_MODULE_SSH_AUTH_SESSION
#endif
#ifndef XSSH_MODULE_SSH_CONNECTION_MESSAGE
#define XSSH_MODULE_SSH_CONNECTION_MESSAGE
#endif
#ifndef XSSH_MODULE_SSH_CHANNEL_MESSAGE
#define XSSH_MODULE_SSH_CHANNEL_MESSAGE
#endif
#ifndef XSSH_MODULE_SSH_CHANNEL_WINDOW
#define XSSH_MODULE_SSH_CHANNEL_WINDOW
#endif
#ifndef XSSH_MODULE_SSH_CHANNEL_REQUEST
#define XSSH_MODULE_SSH_CHANNEL_REQUEST
#endif
#ifndef XSSH_MODULE_SSH_CHANNEL_PTY
#define XSSH_MODULE_SSH_CHANNEL_PTY
#endif
#ifndef XSSH_MODULE_SSH_CHANNEL_STATE
#define XSSH_MODULE_SSH_CHANNEL_STATE
#endif
#ifndef XSSH_MODULE_SSH_CHANNEL_CORE
#define XSSH_MODULE_SSH_CHANNEL_CORE
#endif
#ifndef XSSH_MODULE_SSH_CHANNEL_IO
#define XSSH_MODULE_SSH_CHANNEL_IO
#endif
#ifndef XSSH_MODULE_SSH_FORWARD_MESSAGE
#define XSSH_MODULE_SSH_FORWARD_MESSAGE
#endif
#ifndef XSSH_MODULE_SSH_REPLY_QUEUE
#define XSSH_MODULE_SSH_REPLY_QUEUE
#endif
#ifndef XSSH_MODULE_SSH_CONNECTION_SESSION
#define XSSH_MODULE_SSH_CONNECTION_SESSION
#endif
#ifndef XSSH_MODULE_SSH_CHANNELS
#define XSSH_MODULE_SSH_CHANNELS
#endif
#ifndef XSSH_MODULE_SSH_SESSION_CORE
#define XSSH_MODULE_SSH_SESSION_CORE
#endif
#ifndef XSSH_MODULE_SSH_SESSION_CORE_RANDOM
#define XSSH_MODULE_SSH_SESSION_CORE_RANDOM
#endif
#ifndef XSSH_MODULE_SSH_SESSION_TCP
#define XSSH_MODULE_SSH_SESSION_TCP
#endif
#ifndef XSSH_MODULE_SSH_SESSION_READER
#define XSSH_MODULE_SSH_SESSION_READER
#endif
#ifndef XSSH_MODULE_SSH_SESSION_STREAM
#define XSSH_MODULE_SSH_SESSION_STREAM
#endif
#ifndef XSSH_MODULE_SSH_SESSION_TCP_RANDOM
#define XSSH_MODULE_SSH_SESSION_TCP_RANDOM
#endif
#ifndef XSSH_MODULE_SSH_CLIENT_CORE
#define XSSH_MODULE_SSH_CLIENT_CORE
#endif
#ifndef XSSH_MODULE_SSH_CLIENT_AUTH_ED25519
#define XSSH_MODULE_SSH_CLIENT_AUTH_ED25519
#endif
#ifndef XSSH_MODULE_SSH_CLIENT
#define XSSH_MODULE_SSH_CLIENT
#endif
#ifndef XSSH_MODULE_SSH_CLIENT_DIAL
#define XSSH_MODULE_SSH_CLIENT_DIAL
#endif
#ifndef XSSH_MODULE_SSH_CLIENT_FUTURE
#define XSSH_MODULE_SSH_CLIENT_FUTURE
#endif
#ifndef XSSH_MODULE_SSH_CLIENT_SESSION
#define XSSH_MODULE_SSH_CLIENT_SESSION
#endif
#ifndef XSSH_MODULE_SSH_CLIENT_FORWARD
#define XSSH_MODULE_SSH_CLIENT_FORWARD
#endif
#ifndef XSSH_MODULE_SSH_CLIENT_PTY
#define XSSH_MODULE_SSH_CLIENT_PTY
#endif
#ifndef XRT_MODULE_MEMORY_DEBUG
#define XRT_MODULE_MEMORY_DEBUG
#endif
#endif

/* ssh_client_pty 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_CLIENT_PTY)
#ifndef XSSH_FEATURE_CLIENT_PTY
#define XSSH_FEATURE_CLIENT_PTY
#endif
#ifndef XSSH_MODULE_SSH_CLIENT_SESSION
#define XSSH_MODULE_SSH_CLIENT_SESSION
#endif
#ifndef XSSH_MODULE_SSH_CHANNEL_PTY
#define XSSH_MODULE_SSH_CHANNEL_PTY
#endif
#endif

/* ssh_client_future 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_CLIENT_FUTURE)
#ifndef XSSH_FEATURE_CLIENT_FUTURE
#define XSSH_FEATURE_CLIENT_FUTURE
#endif
#ifndef XSSH_MODULE_SSH_CLIENT
#define XSSH_MODULE_SSH_CLIENT
#endif
#ifndef XRT_MODULE_FUTURE
#define XRT_MODULE_FUTURE
#endif
#ifndef XRT_MODULE_SPIN
#define XRT_MODULE_SPIN
#endif
#endif

/* ssh_client_forward 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_CLIENT_FORWARD)
#ifndef XSSH_FEATURE_CLIENT_FORWARD
#define XSSH_FEATURE_CLIENT_FORWARD
#endif
#ifndef XSSH_MODULE_SSH_CLIENT
#define XSSH_MODULE_SSH_CLIENT
#endif
#ifndef XSSH_MODULE_SSH_FORWARD_MESSAGE
#define XSSH_MODULE_SSH_FORWARD_MESSAGE
#endif
#endif

/* ssh_client_dial 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_CLIENT_DIAL)
#ifndef XSSH_FEATURE_CLIENT_DIAL
#define XSSH_FEATURE_CLIENT_DIAL
#endif
#ifndef XSSH_MODULE_SSH_CLIENT
#define XSSH_MODULE_SSH_CLIENT
#endif
#ifndef XRT_MODULE_NET_TCP_DIAL
#define XRT_MODULE_NET_TCP_DIAL
#endif
#endif

/* ssh_client_session 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_CLIENT_SESSION)
#ifndef XSSH_FEATURE_CLIENT_SESSION
#define XSSH_FEATURE_CLIENT_SESSION
#endif
#ifndef XSSH_MODULE_SSH_CLIENT
#define XSSH_MODULE_SSH_CLIENT
#endif
#ifndef XSSH_MODULE_SSH_CHANNEL_REQUEST
#define XSSH_MODULE_SSH_CHANNEL_REQUEST
#endif
#endif

/* ssh_client 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_CLIENT)
#ifndef XSSH_FEATURE_CLIENT
#define XSSH_FEATURE_CLIENT
#endif
#ifndef XSSH_MODULE_SSH_CLIENT_CORE
#define XSSH_MODULE_SSH_CLIENT_CORE
#endif
#ifndef XSSH_MODULE_SSH_SESSION_STREAM
#define XSSH_MODULE_SSH_SESSION_STREAM
#endif
#ifndef XSSH_MODULE_SSH_CHANNELS
#define XSSH_MODULE_SSH_CHANNELS
#endif
#endif

/* ssh_client_auth_ed25519 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_CLIENT_AUTH_ED25519)
#ifndef XSSH_FEATURE_CLIENT_AUTH_ED25519
#define XSSH_FEATURE_CLIENT_AUTH_ED25519
#endif
#ifndef XSSH_MODULE_SSH_CLIENT_CORE
#define XSSH_MODULE_SSH_CLIENT_CORE
#endif
#ifndef XSSH_MODULE_SSH_AUTH_PUBLICKEY
#define XSSH_MODULE_SSH_AUTH_PUBLICKEY
#endif
#ifndef XSSH_MODULE_SSH_PRIVATE_KEY_ED25519
#define XSSH_MODULE_SSH_PRIVATE_KEY_ED25519
#endif
#endif

/* ssh_client_core 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_CLIENT_CORE)
#ifndef XSSH_FEATURE_CLIENT_CORE
#define XSSH_FEATURE_CLIENT_CORE
#endif
#ifndef XSSH_MODULE_SSH_SESSION_READER
#define XSSH_MODULE_SSH_SESSION_READER
#endif
#ifndef XSSH_MODULE_SSH_SESSION_TCP_RANDOM
#define XSSH_MODULE_SSH_SESSION_TCP_RANDOM
#endif
#ifndef XSSH_MODULE_SSH_KEXINIT_RANDOM
#define XSSH_MODULE_SSH_KEXINIT_RANDOM
#endif
#ifndef XSSH_MODULE_SSH_AUTH_PASSWORD
#define XSSH_MODULE_SSH_AUTH_PASSWORD
#endif
#ifndef XSSH_MODULE_SSH_TRANSPORT_MESSAGE
#define XSSH_MODULE_SSH_TRANSPORT_MESSAGE
#endif
#endif

/* ssh_session_tcp_random 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_SESSION_TCP_RANDOM)
#ifndef XSSH_FEATURE_SESSION_TCP_RANDOM
#define XSSH_FEATURE_SESSION_TCP_RANDOM
#endif
#ifndef XSSH_MODULE_SSH_SESSION_TCP
#define XSSH_MODULE_SSH_SESSION_TCP
#endif
#ifndef XSSH_MODULE_SSH_SESSION_CORE_RANDOM
#define XSSH_MODULE_SSH_SESSION_CORE_RANDOM
#endif
#ifndef XSSH_MODULE_SSH_TRANSPORT_TCP_RANDOM
#define XSSH_MODULE_SSH_TRANSPORT_TCP_RANDOM
#endif
#endif

/* ssh_session_stream 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_SESSION_STREAM)
#ifndef XSSH_FEATURE_SESSION_STREAM
#define XSSH_FEATURE_SESSION_STREAM
#endif
#ifndef XSSH_MODULE_SSH_SESSION_READER
#define XSSH_MODULE_SSH_SESSION_READER
#endif
#endif

/* ssh_session_reader 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_SESSION_READER)
#ifndef XSSH_FEATURE_SESSION_READER
#define XSSH_FEATURE_SESSION_READER
#endif
#ifndef XSSH_MODULE_SSH_SESSION_TCP
#define XSSH_MODULE_SSH_SESSION_TCP
#endif
#endif

/* ssh_session_tcp 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_SESSION_TCP)
#ifndef XSSH_FEATURE_SESSION_TCP
#define XSSH_FEATURE_SESSION_TCP
#endif
#ifndef XSSH_MODULE_SSH_SESSION_CORE
#define XSSH_MODULE_SSH_SESSION_CORE
#endif
#ifndef XSSH_MODULE_SSH_TRANSPORT_TCP
#define XSSH_MODULE_SSH_TRANSPORT_TCP
#endif
#endif

/* ssh_session_core_random 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_SESSION_CORE_RANDOM)
#ifndef XSSH_FEATURE_SESSION_CORE_RANDOM
#define XSSH_FEATURE_SESSION_CORE_RANDOM
#endif
#ifndef XSSH_MODULE_SSH_SESSION_CORE
#define XSSH_MODULE_SSH_SESSION_CORE
#endif
#ifndef XSSH_MODULE_SSH_KEX_EXCHANGE_RANDOM
#define XSSH_MODULE_SSH_KEX_EXCHANGE_RANDOM
#endif
#endif

/* ssh_session_core 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_SESSION_CORE)
#ifndef XSSH_FEATURE_SESSION_CORE
#define XSSH_FEATURE_SESSION_CORE
#endif
#ifndef XSSH_MODULE_SSH_KEX_EXCHANGE
#define XSSH_MODULE_SSH_KEX_EXCHANGE
#endif
#ifndef XSSH_MODULE_SSH_AUTH_SESSION
#define XSSH_MODULE_SSH_AUTH_SESSION
#endif
#ifndef XSSH_MODULE_SSH_CONNECTION_SESSION
#define XSSH_MODULE_SSH_CONNECTION_SESSION
#endif
#endif

/* ssh_channels 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_CHANNELS)
#ifndef XSSH_FEATURE_CHANNELS
#define XSSH_FEATURE_CHANNELS
#endif
#ifndef XSSH_MODULE_SSH_CHANNEL_IO
#define XSSH_MODULE_SSH_CHANNEL_IO
#endif
#ifndef XSSH_MODULE_SSH_CONNECTION_SESSION
#define XSSH_MODULE_SSH_CONNECTION_SESSION
#endif
#ifndef XRT_MODULE_INT_MAP
#define XRT_MODULE_INT_MAP
#endif
#endif

/* ssh_connection_session 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_CONNECTION_SESSION)
#ifndef XSSH_FEATURE_CONNECTION_SESSION
#define XSSH_FEATURE_CONNECTION_SESSION
#endif
#ifndef XSSH_MODULE_SSH_CHANNEL_CORE
#define XSSH_MODULE_SSH_CHANNEL_CORE
#endif
#ifndef XSSH_MODULE_SSH_CONNECTION_MESSAGE
#define XSSH_MODULE_SSH_CONNECTION_MESSAGE
#endif
#ifndef XSSH_MODULE_SSH_REPLY_QUEUE
#define XSSH_MODULE_SSH_REPLY_QUEUE
#endif
#ifndef XSSH_MODULE_SSH_TRANSPORT_CORE
#define XSSH_MODULE_SSH_TRANSPORT_CORE
#endif
#endif

/* ssh_reply_queue 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_REPLY_QUEUE)
#ifndef XSSH_FEATURE_REPLY_QUEUE
#define XSSH_FEATURE_REPLY_QUEUE
#endif
#ifndef XSSH_MODULE_SSH_WIRE
#define XSSH_MODULE_SSH_WIRE
#endif
#endif

/* ssh_forward_message 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_FORWARD_MESSAGE)
#ifndef XSSH_FEATURE_FORWARD_MESSAGE
#define XSSH_FEATURE_FORWARD_MESSAGE
#endif
#ifndef XSSH_MODULE_SSH_CONNECTION_MESSAGE
#define XSSH_MODULE_SSH_CONNECTION_MESSAGE
#endif
#ifndef XSSH_MODULE_SSH_CHANNEL_MESSAGE
#define XSSH_MODULE_SSH_CHANNEL_MESSAGE
#endif
#endif

/* ssh_channel_io 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_CHANNEL_IO)
#ifndef XSSH_FEATURE_CHANNEL_IO
#define XSSH_FEATURE_CHANNEL_IO
#endif
#ifndef XSSH_MODULE_SSH_CHANNEL_CORE
#define XSSH_MODULE_SSH_CHANNEL_CORE
#endif
#ifndef XRT_MODULE_NET_BUFFER
#define XRT_MODULE_NET_BUFFER
#endif
#endif

/* ssh_channel_core 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_CHANNEL_CORE)
#ifndef XSSH_FEATURE_CHANNEL_CORE
#define XSSH_FEATURE_CHANNEL_CORE
#endif
#ifndef XSSH_MODULE_SSH_CHANNEL_MESSAGE
#define XSSH_MODULE_SSH_CHANNEL_MESSAGE
#endif
#ifndef XSSH_MODULE_SSH_CHANNEL_STATE
#define XSSH_MODULE_SSH_CHANNEL_STATE
#endif
#ifndef XSSH_MODULE_SSH_CHANNEL_WINDOW
#define XSSH_MODULE_SSH_CHANNEL_WINDOW
#endif
#endif

/* ssh_channel_state 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_CHANNEL_STATE)
#ifndef XSSH_FEATURE_CHANNEL_STATE
#define XSSH_FEATURE_CHANNEL_STATE
#endif
#ifndef XSSH_MODULE_SSH_WIRE
#define XSSH_MODULE_SSH_WIRE
#endif
#endif

/* ssh_channel_pty 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_CHANNEL_PTY)
#ifndef XSSH_FEATURE_CHANNEL_PTY
#define XSSH_FEATURE_CHANNEL_PTY
#endif
#ifndef XSSH_MODULE_SSH_CHANNEL_REQUEST
#define XSSH_MODULE_SSH_CHANNEL_REQUEST
#endif
#endif

/* ssh_channel_request 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_CHANNEL_REQUEST)
#ifndef XSSH_FEATURE_CHANNEL_REQUEST
#define XSSH_FEATURE_CHANNEL_REQUEST
#endif
#ifndef XSSH_MODULE_SSH_CHANNEL_MESSAGE
#define XSSH_MODULE_SSH_CHANNEL_MESSAGE
#endif
#endif

/* ssh_channel_window 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_CHANNEL_WINDOW)
#ifndef XSSH_FEATURE_CHANNEL_WINDOW
#define XSSH_FEATURE_CHANNEL_WINDOW
#endif
#ifndef XSSH_MODULE_SSH_WIRE
#define XSSH_MODULE_SSH_WIRE
#endif
#endif

/* ssh_channel_message 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_CHANNEL_MESSAGE)
#ifndef XSSH_FEATURE_CHANNEL_MESSAGE
#define XSSH_FEATURE_CHANNEL_MESSAGE
#endif
#ifndef XSSH_MODULE_SSH_WIRE
#define XSSH_MODULE_SSH_WIRE
#endif
#ifndef XRT_MODULE_UNICODE
#define XRT_MODULE_UNICODE
#endif
#endif

/* ssh_connection_message 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_CONNECTION_MESSAGE)
#ifndef XSSH_FEATURE_CONNECTION_MESSAGE
#define XSSH_FEATURE_CONNECTION_MESSAGE
#endif
#ifndef XSSH_MODULE_SSH_WIRE
#define XSSH_MODULE_SSH_WIRE
#endif
#endif

/* ssh_auth_session 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_AUTH_SESSION)
#ifndef XSSH_FEATURE_AUTH_SESSION
#define XSSH_FEATURE_AUTH_SESSION
#endif
#ifndef XSSH_MODULE_SSH_AUTH_GUARD
#define XSSH_MODULE_SSH_AUTH_GUARD
#endif
#ifndef XSSH_MODULE_SSH_AUTH_MESSAGE
#define XSSH_MODULE_SSH_AUTH_MESSAGE
#endif
#ifndef XSSH_MODULE_SSH_TRANSPORT_CORE
#define XSSH_MODULE_SSH_TRANSPORT_CORE
#endif
#endif

/* ssh_auth_guard 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_AUTH_GUARD)
#ifndef XSSH_FEATURE_AUTH_GUARD
#define XSSH_FEATURE_AUTH_GUARD
#endif
#ifndef XSSH_MODULE_SSH_WIRE
#define XSSH_MODULE_SSH_WIRE
#endif
#endif

/* ssh_auth_hostbased 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_AUTH_HOSTBASED)
#ifndef XSSH_FEATURE_AUTH_HOSTBASED
#define XSSH_FEATURE_AUTH_HOSTBASED
#endif
#ifndef XSSH_MODULE_SSH_AUTH_MESSAGE
#define XSSH_MODULE_SSH_AUTH_MESSAGE
#endif
#ifndef XSSH_MODULE_SSH_HOSTKEY
#define XSSH_MODULE_SSH_HOSTKEY
#endif
#endif

/* ssh_auth_keyboard 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_AUTH_KEYBOARD)
#ifndef XSSH_FEATURE_AUTH_KEYBOARD
#define XSSH_FEATURE_AUTH_KEYBOARD
#endif
#ifndef XSSH_MODULE_SSH_AUTH_MESSAGE
#define XSSH_MODULE_SSH_AUTH_MESSAGE
#endif
#endif

/* ssh_auth_publickey 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_AUTH_PUBLICKEY)
#ifndef XSSH_FEATURE_AUTH_PUBLICKEY
#define XSSH_FEATURE_AUTH_PUBLICKEY
#endif
#ifndef XSSH_MODULE_SSH_AUTH_MESSAGE
#define XSSH_MODULE_SSH_AUTH_MESSAGE
#endif
#ifndef XSSH_MODULE_SSH_HOSTKEY
#define XSSH_MODULE_SSH_HOSTKEY
#endif
#endif

/* ssh_auth_password 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_AUTH_PASSWORD)
#ifndef XSSH_FEATURE_AUTH_PASSWORD
#define XSSH_FEATURE_AUTH_PASSWORD
#endif
#ifndef XSSH_MODULE_SSH_AUTH_MESSAGE
#define XSSH_MODULE_SSH_AUTH_MESSAGE
#endif
#endif

/* ssh_auth_message 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_AUTH_MESSAGE)
#ifndef XSSH_FEATURE_AUTH_MESSAGE
#define XSSH_FEATURE_AUTH_MESSAGE
#endif
#ifndef XSSH_MODULE_SSH_WIRE
#define XSSH_MODULE_SSH_WIRE
#endif
#ifndef XRT_MODULE_UNICODE
#define XRT_MODULE_UNICODE
#endif
#endif

/* ssh_transport_tcp_random 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_TRANSPORT_TCP_RANDOM)
#ifndef XSSH_FEATURE_TRANSPORT_TCP_RANDOM
#define XSSH_FEATURE_TRANSPORT_TCP_RANDOM
#endif
#ifndef XSSH_MODULE_SSH_TRANSPORT_TCP
#define XSSH_MODULE_SSH_TRANSPORT_TCP
#endif
#ifndef XSSH_MODULE_SSH_PACKET_RANDOM
#define XSSH_MODULE_SSH_PACKET_RANDOM
#endif
#endif

/* ssh_transport_tcp 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_TRANSPORT_TCP)
#ifndef XSSH_FEATURE_TRANSPORT_TCP
#define XSSH_FEATURE_TRANSPORT_TCP
#endif
#ifndef XSSH_MODULE_SSH_TRANSPORT_CORE
#define XSSH_MODULE_SSH_TRANSPORT_CORE
#endif
#ifndef XRT_MODULE_NET_TCP
#define XRT_MODULE_NET_TCP
#endif
#endif

/* ssh_kex_exchange_random 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_KEX_EXCHANGE_RANDOM)
#ifndef XSSH_FEATURE_KEX_EXCHANGE_RANDOM
#define XSSH_FEATURE_KEX_EXCHANGE_RANDOM
#endif
#ifndef XSSH_MODULE_SSH_KEX_EXCHANGE
#define XSSH_MODULE_SSH_KEX_EXCHANGE
#endif
#ifndef XSSH_MODULE_SSH_KEX_CURVE25519_RANDOM
#define XSSH_MODULE_SSH_KEX_CURVE25519_RANDOM
#endif
#endif

/* ssh_kex_exchange 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_KEX_EXCHANGE)
#ifndef XSSH_FEATURE_KEX_EXCHANGE
#define XSSH_FEATURE_KEX_EXCHANGE
#endif
#ifndef XSSH_MODULE_SSH_KEX_SESSION
#define XSSH_MODULE_SSH_KEX_SESSION
#endif
#ifndef XRT_MODULE_NET_BUFFER
#define XRT_MODULE_NET_BUFFER
#endif
#endif

/* ssh_kex_session_random 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_KEX_SESSION_RANDOM)
#ifndef XSSH_FEATURE_KEX_SESSION_RANDOM
#define XSSH_FEATURE_KEX_SESSION_RANDOM
#endif
#ifndef XSSH_MODULE_SSH_KEX_SESSION
#define XSSH_MODULE_SSH_KEX_SESSION
#endif
#ifndef XSSH_MODULE_SSH_KEX_CURVE25519_RANDOM
#define XSSH_MODULE_SSH_KEX_CURVE25519_RANDOM
#endif
#endif

/* ssh_kex_session 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_KEX_SESSION)
#ifndef XSSH_FEATURE_KEX_SESSION
#define XSSH_FEATURE_KEX_SESSION
#endif
#ifndef XSSH_MODULE_SSH_HOSTKEY_ED25519
#define XSSH_MODULE_SSH_HOSTKEY_ED25519
#endif
#ifndef XSSH_MODULE_SSH_KEX_CURVE25519
#define XSSH_MODULE_SSH_KEX_CURVE25519
#endif
#ifndef XSSH_MODULE_SSH_KEX_ECDH
#define XSSH_MODULE_SSH_KEX_ECDH
#endif
#ifndef XSSH_MODULE_SSH_KEX_SHA256
#define XSSH_MODULE_SSH_KEX_SHA256
#endif
#ifndef XSSH_MODULE_SSH_TRANSPORT_CORE
#define XSSH_MODULE_SSH_TRANSPORT_CORE
#endif
#endif

/* ssh_transport_core 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_TRANSPORT_CORE)
#ifndef XSSH_FEATURE_TRANSPORT_CORE
#define XSSH_FEATURE_TRANSPORT_CORE
#endif
#ifndef XSSH_MODULE_SSH_PACKET_CODEC
#define XSSH_MODULE_SSH_PACKET_CODEC
#endif
#ifndef XSSH_MODULE_SSH_TRANSPORT_REKEY
#define XSSH_MODULE_SSH_TRANSPORT_REKEY
#endif
#ifndef XSSH_MODULE_SSH_TRANSPORT_STATE
#define XSSH_MODULE_SSH_TRANSPORT_STATE
#endif
#endif

/* ssh_transport_state 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_TRANSPORT_STATE)
#ifndef XSSH_FEATURE_TRANSPORT_STATE
#define XSSH_FEATURE_TRANSPORT_STATE
#endif
#ifndef XSSH_MODULE_SSH_KEXINIT
#define XSSH_MODULE_SSH_KEXINIT
#endif
#ifndef XSSH_MODULE_SSH_TRANSPORT_MESSAGE
#define XSSH_MODULE_SSH_TRANSPORT_MESSAGE
#endif
#endif

/* ssh_transport_rekey 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_TRANSPORT_REKEY)
#ifndef XSSH_FEATURE_TRANSPORT_REKEY
#define XSSH_FEATURE_TRANSPORT_REKEY
#endif
#ifndef XSSH_MODULE_SSH_WIRE
#define XSSH_MODULE_SSH_WIRE
#endif
#endif

/* ssh_transport_message 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_TRANSPORT_MESSAGE)
#ifndef XSSH_FEATURE_TRANSPORT_MESSAGE
#define XSSH_FEATURE_TRANSPORT_MESSAGE
#endif
#ifndef XSSH_MODULE_SSH_WIRE
#define XSSH_MODULE_SSH_WIRE
#endif
#endif

/* ssh_private_key_ed25519 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_PRIVATE_KEY_ED25519)
#ifndef XSSH_FEATURE_PRIVATE_KEY_ED25519
#define XSSH_FEATURE_PRIVATE_KEY_ED25519
#endif
#ifndef XSSH_MODULE_SSH_PRIVATE_KEY
#define XSSH_MODULE_SSH_PRIVATE_KEY
#endif
#ifndef XRT_MODULE_CRYPTO_ED25519_SIGN
#define XRT_MODULE_CRYPTO_ED25519_SIGN
#endif
#endif

/* ssh_private_key_pem 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_PRIVATE_KEY_PEM)
#ifndef XSSH_FEATURE_PRIVATE_KEY_PEM
#define XSSH_FEATURE_PRIVATE_KEY_PEM
#endif
#ifndef XSSH_MODULE_SSH_PRIVATE_KEY
#define XSSH_MODULE_SSH_PRIVATE_KEY
#endif
#ifndef XRT_MODULE_PEM
#define XRT_MODULE_PEM
#endif
#endif

/* ssh_private_key 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_PRIVATE_KEY)
#ifndef XSSH_FEATURE_PRIVATE_KEY
#define XSSH_FEATURE_PRIVATE_KEY
#endif
#ifndef XSSH_MODULE_SSH_HOSTKEY
#define XSSH_MODULE_SSH_HOSTKEY
#endif
#endif

/* ssh_fingerprint 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_FINGERPRINT)
#ifndef XSSH_FEATURE_FINGERPRINT
#define XSSH_FEATURE_FINGERPRINT
#endif
#ifndef XSSH_MODULE_SSH_WIRE
#define XSSH_MODULE_SSH_WIRE
#endif
#ifndef XRT_MODULE_CODEC_BASE64
#define XRT_MODULE_CODEC_BASE64
#endif
#ifndef XRT_MODULE_CRYPTO_SHA256
#define XRT_MODULE_CRYPTO_SHA256
#endif
#endif

/* ssh_known_host_db 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_KNOWN_HOST_DB)
#ifndef XSSH_FEATURE_KNOWN_HOST_DB
#define XSSH_FEATURE_KNOWN_HOST_DB
#endif
#ifndef XSSH_MODULE_SSH_KNOWN_HOST_HASH
#define XSSH_MODULE_SSH_KNOWN_HOST_HASH
#endif
#endif

/* ssh_known_host_hash 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_KNOWN_HOST_HASH)
#ifndef XSSH_FEATURE_KNOWN_HOST_HASH
#define XSSH_FEATURE_KNOWN_HOST_HASH
#endif
#ifndef XSSH_MODULE_SSH_KNOWN_HOST
#define XSSH_MODULE_SSH_KNOWN_HOST
#endif
#ifndef XRT_MODULE_CRYPTO_SHA1
#define XRT_MODULE_CRYPTO_SHA1
#endif
#endif

/* ssh_known_host 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_KNOWN_HOST)
#ifndef XSSH_FEATURE_KNOWN_HOST
#define XSSH_FEATURE_KNOWN_HOST
#endif
#ifndef XSSH_MODULE_SSH_KEY_TEXT
#define XSSH_MODULE_SSH_KEY_TEXT
#endif
#endif

/* ssh_key_text 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_KEY_TEXT)
#ifndef XSSH_FEATURE_KEY_TEXT
#define XSSH_FEATURE_KEY_TEXT
#endif
#ifndef XSSH_MODULE_SSH_HOSTKEY
#define XSSH_MODULE_SSH_HOSTKEY
#endif
#ifndef XRT_MODULE_CODEC_BASE64
#define XRT_MODULE_CODEC_BASE64
#endif
#endif

/* ssh_hostkey_ed25519 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_HOSTKEY_ED25519)
#ifndef XSSH_FEATURE_HOSTKEY_ED25519
#define XSSH_FEATURE_HOSTKEY_ED25519
#endif
#ifndef XSSH_MODULE_SSH_HOSTKEY
#define XSSH_MODULE_SSH_HOSTKEY
#endif
#ifndef XRT_MODULE_CRYPTO_ED25519_VERIFY
#define XRT_MODULE_CRYPTO_ED25519_VERIFY
#endif
#endif

/* ssh_hostkey 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_HOSTKEY)
#ifndef XSSH_FEATURE_HOSTKEY
#define XSSH_FEATURE_HOSTKEY
#endif
#ifndef XSSH_MODULE_SSH_WIRE
#define XSSH_MODULE_SSH_WIRE
#endif
#endif

/* ssh_kex_curve25519_random 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_KEX_CURVE25519_RANDOM)
#ifndef XSSH_FEATURE_KEX_CURVE25519_RANDOM
#define XSSH_FEATURE_KEX_CURVE25519_RANDOM
#endif
#ifndef XSSH_MODULE_SSH_KEX_CURVE25519
#define XSSH_MODULE_SSH_KEX_CURVE25519
#endif
#ifndef XRT_MODULE_CRYPTO_X25519_KEYPAIR
#define XRT_MODULE_CRYPTO_X25519_KEYPAIR
#endif
#endif

/* ssh_kex_curve25519 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_KEX_CURVE25519)
#ifndef XSSH_FEATURE_KEX_CURVE25519
#define XSSH_FEATURE_KEX_CURVE25519
#endif
#ifndef XSSH_MODULE_SSH_WIRE
#define XSSH_MODULE_SSH_WIRE
#endif
#ifndef XRT_MODULE_CRYPTO_X25519
#define XRT_MODULE_CRYPTO_X25519
#endif
#endif

/* ssh_kex_sha256 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_KEX_SHA256)
#ifndef XSSH_FEATURE_KEX_SHA256
#define XSSH_FEATURE_KEX_SHA256
#endif
#ifndef XSSH_MODULE_SSH_WIRE
#define XSSH_MODULE_SSH_WIRE
#endif
#ifndef XRT_MODULE_CRYPTO_SHA256
#define XRT_MODULE_CRYPTO_SHA256
#endif
#endif

/* ssh_kex_ecdh 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_KEX_ECDH)
#ifndef XSSH_FEATURE_KEX_ECDH
#define XSSH_FEATURE_KEX_ECDH
#endif
#ifndef XSSH_MODULE_SSH_WIRE
#define XSSH_MODULE_SSH_WIRE
#endif
#endif

/* ssh_kexinit_random 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_KEXINIT_RANDOM)
#ifndef XSSH_FEATURE_KEXINIT_RANDOM
#define XSSH_FEATURE_KEXINIT_RANDOM
#endif
#ifndef XSSH_MODULE_SSH_KEXINIT
#define XSSH_MODULE_SSH_KEXINIT
#endif
#ifndef XRT_MODULE_RANDOM_SECURE
#define XRT_MODULE_RANDOM_SECURE
#endif
#endif

/* ssh_kexinit 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_KEXINIT)
#ifndef XSSH_FEATURE_KEXINIT
#define XSSH_FEATURE_KEXINIT
#endif
#ifndef XSSH_MODULE_SSH_WIRE
#define XSSH_MODULE_SSH_WIRE
#endif
#endif

/* ssh_packet_codec_random 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_PACKET_CODEC_RANDOM)
#ifndef XSSH_FEATURE_PACKET_CODEC_RANDOM
#define XSSH_FEATURE_PACKET_CODEC_RANDOM
#endif
#ifndef XSSH_MODULE_SSH_PACKET_CODEC
#define XSSH_MODULE_SSH_PACKET_CODEC
#endif
#ifndef XSSH_MODULE_SSH_PACKET_RANDOM
#define XSSH_MODULE_SSH_PACKET_RANDOM
#endif
#endif

/* ssh_packet_codec 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_PACKET_CODEC)
#ifndef XSSH_FEATURE_PACKET_CODEC
#define XSSH_FEATURE_PACKET_CODEC
#endif
#ifndef XSSH_MODULE_SSH_PACKET_AES_GCM
#define XSSH_MODULE_SSH_PACKET_AES_GCM
#endif
#endif

/* ssh_packet_aes_gcm 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_PACKET_AES_GCM)
#ifndef XSSH_FEATURE_PACKET_AES_GCM
#define XSSH_FEATURE_PACKET_AES_GCM
#endif
#ifndef XSSH_MODULE_SSH_PACKET
#define XSSH_MODULE_SSH_PACKET
#endif
#ifndef XRT_MODULE_CRYPTO_AES_GCM
#define XRT_MODULE_CRYPTO_AES_GCM
#endif
#endif

/* ssh_packet_random 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_PACKET_RANDOM)
#ifndef XSSH_FEATURE_PACKET_RANDOM
#define XSSH_FEATURE_PACKET_RANDOM
#endif
#ifndef XSSH_MODULE_SSH_PACKET
#define XSSH_MODULE_SSH_PACKET
#endif
#ifndef XRT_MODULE_RANDOM_SECURE
#define XRT_MODULE_RANDOM_SECURE
#endif
#endif

/* ssh_packet 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_PACKET)
#ifndef XSSH_FEATURE_PACKET
#define XSSH_FEATURE_PACKET
#endif
#ifndef XSSH_MODULE_SSH_WIRE
#define XSSH_MODULE_SSH_WIRE
#endif
#endif

/* ssh_wire 及其直接依赖。 */
#if defined(XSSH_MODULE_ALL) || defined(XSSH_MODULE_SSH_WIRE)
#ifndef XSSH_FEATURE_WIRE
#define XSSH_FEATURE_WIRE
#endif
#endif

#endif /* XSSH_FEATURES_H */
